[appendix]
:appendix-caption: Annex
== Examples (Informative)

[[basic-coverage-examples]]
=== Basic Coverage Retrieval Example

// TODO:

[[subsetting-examples]]
=== Subsetting Example

These examples return a subset of a coverage in the negotiated format, including domain set, range type (and metadata if applicable) to the extent than they can be described in that format:

* {datasetAPI}/collections/{collectionId}/coverage?subset=Lat(40:50),Lon(10:20) -- returns a cutout (trim) from the coverage for the extent between corner coordinates (Lat: 40, Lon: 10) and (Lat: 50, Lon: 20)
* {datasetAPI}/collections/{collectionId}/coverage?subset=time("2019-03-27") -- returns a coverage slice at the timestamp (if the coverage is has 2D spatial dimensions plus time, the result will be a 2D image with its full spatial extent)

[[scaling-examples]]
=== Scaling Example

* {datasetAPI}/collections/{collectionId}/coverage?resolutions=Lat(0.5),Lon(0.5) -- returns a coverage re-scaled at a 0.5 degree resolution for both latitude and longitude
* {datasetAPI}/collections/{collectionId}/coverage?resolutions=spatial-distance(0.5) -- for a non-gridded coverage such as a point cloud, returns a coverage re-scaled at a 0.5 meters resolution (vectorial distance between samples)
* {datasetAPI}/collections/{collectionId}/coverage?width=400&height=300 -- returns the entire coverage re-scaled to 300 pixels along its latitude or Northing/Y axis, and 400 samples along its longitude or Easting/X axis in the negotiated format
* {datasetAPI}/collections/{collectionId}/coverage?resolutions=time(P1D) -- returns a coverage re-scaled to a daily temporal resolution for its primary temporal dimension
* {datasetAPI}/collections/{collectionId}/coverage?resolutions=Lat(),Lon(),time() -- returns a coverage using the native spatial and temporal resolution, ensuring the server will not automatically downsample, which might result in an error if the response is too large

[[field-selection-examples]]
=== Field Selection (Range Subsetting) Example

These examples return a range subset of a coverage in the negotiated format, including domain set, range type (and metadata if applicable) to the extent than they can be described in that format:

* {datasetAPI}/collections/{collectionId}/coverage?properties=B02,B03,B04 -- returns only the bands with IDs B02, B03 and B04 from the coverage
* {datasetAPI}/collections/{collectionId}/coverage?properties=3,4,5 -- returns the 4th, 5th and 6th band (0-based indexing, as listed in the Range Type) from the coverage
* {datasetAPI}/collections/{collectionId}/coverage?properties=B07,* -- returns the band B07 and all subsequent bands from the coverage

[[coverage-tiles-examples]]
=== Coverage Tiles Example

// TODO:

////
=== Domainset Subsetting Example
// No longer a thing
////

////

NOTE: Collection filtering should be a profile of Records Local Resource Catalogs for Collections resources defined in a requirements class of OGC API - Common - Part 2: Geospatial Data

[[collections-metadata-examples]]
=== Bounding Box Example

* Using OAPI-Common bbox syntax (fixed, 2D axis sequence): http://acme.com/oapi/collections?bbox=160.6,-55.95,-170,-25.89  -- returns a list of all collections intersecting that is in the New Zealand economic zone.

////
