[[overview]]
== Overview

[[general-overview]]
=== General

_OGC API - Coverages - Part 1: Core_, hereafter sometimes referred to as the _Coverages API_, specifies the fundamental Web API resource paths, responses, schemas and parameters
for retrieving <<term-coverage,coverage>> data organized as a mandatory "Core" requirements class and additional optional requirements classes.
The spatial data community uses the term _coverage_ for homogeneous collections of values located in space/time such as: spatio-temporal sensor, image, simulation, and statistical data.
The _W3C/OGC Spatial Data on the Web Best Practices_ provide an overview of https://www.w3.org/TR/sdw-bp/#coverages[Coverages: describing properties that vary with location (and time)].

Implementations of the OGC API family of standards enable access to resources using the HTTP protocol and its associated operations (GET, PUT, POST, etc.).
_OGC API - Common_ defines a set of capabilities which are shared by several OGC API Standards.
Some of these other OGC API Standards define capabilities to access data using a particular mechanism tailored to a specific resource type.
These OGC Standards can be integrated within the framework defined by _OGC API - Common_, including:

* the concept of a landing page, providing an API definition and declaring conformance (https://docs.ogc.org/is/19-072/19-072.html[_Part 1_]),
* providing access to one or more collections of geospatial data (https://docs.ogc.org/DRAFTS/20-024.html[_Part 2_]),
* providing a representation-agnostic schema for the fields/properties of the data (https://docs.ogc.org/is/23-058r2/23-058r2.html[_Part 3_]).

OGC API Standards also re-use common Web API elements such as resource paths (including associated path parameters), HTTP methods, request and response headers,
response definitions for specific representations, schemas for request payloads and responses, and query parameters.
This common framework ensures consistency and supports the integration of multiple OGC API Standards within a single Web API implementation.

This _OGC API - Coverages_ Standard defines an API with two goals:

* Provide access to <<term-coverage,*_Coverages_*>> conformant to the https://portal.ogc.org/files/?artifact_id=19820[OGC Abstract Specification Topic 6: Schema for coverage geometry and functions].
* Provide functionality comparable to that of the <<web-coverage-service-overview,OGC Web Coverage Service (WCS) standard>>.

Conformant Implementations of this Coverages API Standard enable efficient access to multidimensional <<term-geospatial-data-cube,geospatial data cubes>>, particularly when additional optional requirements classes complementing the functionality
defined in the "Core" requirements class allowing to subset the <<rc_field-selection,fields>>, <<rc_subsetting_spatial,area>>, <<rc_subsetting_temporal,time>> and <<rc_scaling_spatial,resolution of interest>>, are implemented.

This data cube functionality can be further extended by integrating it with advanced processing capabilities
as defined by https://docs.ogc.org/is/18-062r2/18-062r2.html[_OGC API - Processes - Part 1: Core_] and https://docs.ogc.org/DRAFTS/21-009.html[_OGC API - Processes - Part 3: Workflows and Chaining_ (draft)]
(the _collection input_ and _collection output_ requirements classes in particular).

A future part extension to this Coverages API Standard is also foreseen for deriving new coverage fields based
on a simple expression language such as the https://docs.ogc.org/DRAFTS/21-065.html[_OGC Common Query Language (CQL2)_], together with standardized mathematical and aggregation functions.

Resources exposed through an OGC API endpoint may be accessed through a Universal Resource Identifier <<rfc3986,(URI).>>
URIs are composed of three sections:

* Dataset distribution API: The endpoint corresponding to a dataset distribution, where the landing page resource as defined in _OGC API - Common - Part 1: Core_ is available (subsequently referred to as Base URI or `{root}`)
* Access Paths: Unique paths to Resources
* Query: Parameters to adjust the representation of a Resource or Resources, such as requesting a particular subset or downsampled resolution of the data

Access Paths are used to build resource identifiers. Most of these paths are fixed, with the exception of the _OGC API - Common - Part 1_ `/api` service description / documentation.

All resources are also accessible by following links starting from the landing page, with a specific link relation type used from one resource to another, as detailed in <<conventions-link-relations>>.

=== Resource Paths

The following table summarizes the resource paths defined in this standard, as well as those inherited from _OGC API - Common_.

[#coverage-paths,reftext='{table-caption} {counter:table-num}']
._Coverages API_ Resources
[width="100%",cols="3,5",options="header"]
|===
^|Resource URI                                   ^|Description
2+|https://docs.ogc.org/is/19-072/19-072.html[**_OGC API - Common - Part 1_**]
|`{root}/` +
(see <<_landing_page,example B.1.1>>) |Landing page for a dataset distribution
|`{root}/api` +
(see https://github.com/opengeospatial/ogcapi-coverages/tree/master/standard/openapi[example OpenAPI definition])  |API description (e.g., Open API Specification) and documentation (e.g., HTML)
|`{root}/conformance` +
(see <<_conformance_declaration_2,example B.1.2>>)                         |Declaration of supported conformance classes
2+|https://docs.ogc.org/DRAFTS/20-024.html[**_OGC API - Common - Part 2_**]
|`{root}/collections` +
(see <<_list_of_collections,example B.1.3>>)                        |The list of all collections available, some or all of which may be accessible using the resource endpoint defined by the Coverages API Standard. Each of these collections contains a minimal subset of the object collection resource object described immediately below.
|`{root}/collections/{collectionId}` +
(see <<collection-description-example,example B.2.1>>)         |Description for the collection with the unique identifier `{collectionId}`, which may be accessible as a coverage. The resource includes elements such as an `id`, `title`, `description`, available `crs` and `extent`. This `extent` describes the <<term-domain,domain>> of the coverage for each dimension, including the overall envelope, detailed sub-intervals where data is available, and/or a <<term-regular-grid,regular>> or <<term-irregular-grid,irregular>> <<term-grid,`grid`>>. This object also includes links to resources pertaining to this collection. For coverages, a link to the record schema described below will be included. This resource is comparable to a WCS *_DescribeCoverage_* response, with the exception that the schema, corresponding to Coverage Implementation Schema (CIS) _range type_, needs to be retrieved separately.
2+|https://docs.ogc.org/is/23-058r2/23-058r2.html[**_OGC API - Common - Part 3_**]
|`{root}/collections/{collectionId}` `/schema` +
(see <<_schema_resource_range_type,example B.2.2>>)  |Returns the schema for the coverage <<term-field,fields>> or properties of values available at each <<term-direct-position,direct position>>. At minimum, a _JSON Schema_ representation of this resource is available. This resource is comparable to the CIS <<term-range-type,_range type_>> portion of the WCS *_DescribeCoverage_* response, and is retrieved separately from the collection description to accommodate more complex record schemas including several record fields and/or detailed semantic annotations.
2+|<<rc_core,**_OGC API - Coverages - Part 1_**>> (example path)
|`{root}/collections/{collectionId}` `/coverage` +
(see <<_core_data_request,example B.3>>) |Returns the <<term-coverage,coverage>> data, including any self-describing information (such as the _domain set_, _range type_ and _metadata_ components in addition to the _<<term-range,range>> set_ of CIS). This resource is comparable to a WCS *_GetCoverage_* response.
2+|https://docs.ogc.org/is/20-057/20-057.html[**_OGC API - Tiles - Part 1_**]  (example paths)
|`{root}/collections/{collectionId}` `/tiles` +
(see <<_discovering_available_tilesets,example B.12.1>>)                                             |Returns the list of tilesets available for this coverage.
|`{root}/collections/{collectionId}` `/tiles/{tileSetId}` +
(see <<_retrieving_a_tileset_metadata_resource,example B.12.2>>)                                 |Returns an individual coverage tileset for a particular 2D Tile Matrix Set
|`{root}/collections/{collectionId}` `/tiles/{tileSetId}/{tileMatrix}/{tileRow}/{tileCol}` +
(see examples <<_retrieving_tiled_coverage_data_by_slicing_dimensions,B.12.3>> and <<_retrieving_multi_dimensional_tiled_coverage_data,B.12.4>>) |Returns an individual coverage tile for a particular 2D Tile Matrix Set, tile matrix, tile row and tile column
|===

Where:

* `{root}` = URI of the landing page for the API distributing the dataset
* `{collectionId}` = an identifier for a specific coverage (collection)

[[coverage-query-parameters]]
=== Coverage resource query parameters

The table below summarizes the query parameters available for the `{root}/collections/{collectionId}/coverage` endpoint to subset (slice, trim, select fields),
resample and reproject coverage data defined by optional requirements classes.

[#coverage-parameters-table,reftext='{table-caption} {counter:table-num}']
.Overview of query parameters for `/collections/{collectionId}/coverage`
[width="100%",cols="2,4,6,4",options="header"]
|===
^|Query parameter ^|Purpose ^| Examples ^|Defined by +
(requirements class)

|**`bbox`**
|Trim data within a 2D or 3D spatial bounding box
|`bbox=-75.0,40.0,-65.0,50.0` +
(see <<_axis_subsetting_slicing_and_trimming, B.4>>)
|<<rc_subsetting_spatial,*Spatial Subsetting*>>

|**`bbox-crs`**
|Define the coordinate reference system for `bbox`
|`bbox-crs=[EPSG:3395]` +
(see <<_output_crs_selection, B.11>>)
|<<rc_subsetting_spatial,*Spatial Subsetting*>>

|**`datetime`**
|Slice (single value) or trims (interval) data along the primary temporal dimension
|`datetime=2026-01-01/2026-07-03` +
`datetime=2026-01-01T12:00:00Z` +
(see <<_axis_subsetting_slicing_and_trimming, B.4>>, <<_sparse_dimensions_slicing_and_flattening, B.5>>)
|<<rc_subsetting_temporal,*Temporal Subsetting*>>, <<rc_sparse-dimensions-collapse-temporal,*Collapsing Sparse Temporal Dimensions*>>

|**`subset`**
|Slice (single value) or trims (interval) any data axis
|`subset=Lat(40:50),time("2026-07-03")` +
(see <<_axis_subsetting_slicing_and_trimming, B.4>>, <<_sparse_dimensions_slicing_and_flattening, B.5>>, <<_multi_slicing, B.6>>, <<_position_query, B.7>>)
|<<rc_subsetting_spatial,*Spatial Subsetting*>>, +
<<rc_subsetting_temporal,*Temporal Subsetting*>>, +
<<rc_subsetting_general,*General Subsetting*>>, +
<<rc_multi_slicing,*Multi Slicing*>>, +
*Collapsing Sparse  <<rc_sparse-dimensions-collapse-spatial, Spatial>>, +
<<rc_sparse-dimensions-collapse-temporal, Temporal>>, +
<<rc_sparse-dimensions-collapse-general, General>> Dimensions*, +
<<rc_position_query, *Position Query*>>

|**`subset-crs`**
|Define the coordinate reference system for `subset`
|`subset-crs=[EPSG:3395]`
|<<rc_subsetting_spatial,*Spatial Subsetting*>>

|**`width`**
|Set explicit count of cells for the output's dimension corresponding to longitude or easting
|`width=800` +
(see <<_explicit_grid_size_scaling_via_width_and_height, B.8.2>>)
|<<rc_scaling_spatial,*Spatial Scaling*>>

|**`height`**
|Set explicit count of cells for the output's dimension corresponding to latitude or northing
|`height=600` +
(see <<_explicit_grid_size_scaling_via_width_and_height, B.8.2>>)
|<<rc_scaling_spatial,*Spatial Scaling*>>

|**`resolution`**
|Specify distance between cells for resampling
|`resolution=Lat(10),Lon(10),time(P1D)` +
(see <<scaling-examples, B.8>>)
|<<rc_scaling_spatial,*Spatial Scaling*>>, +
<<rc_scaling_temporal,*Temporal Scaling*>>, +
<<rc_scaling_general,*General Scaling*>>

|**`properties`**
|Select specific fields from the <<term-field,field schema>>
|`properties=B02,B03,B04` +
(see <<_field_selection_via_the_properties_query_parameter,B.10.1>>)
|<<rc_field-selection,*Field Selection*>>

|**`exclude-properties`**
|Exclude specific fields from the <<term-field,field schema>>
|`exclude-properties=temp,rh` +
(see <<_excluding_fields_via_the_exclude_properties_query_parameter,B.10.2>>)
|<<rc_field-selection,*Field Selection*>>

|**`crs`**
|Reproject the output data to a target CRS
|`crs=[EPSG:3395]` +
(see <<_output_crs_selection, B.11>>)
|<<rc_crs,*Coordinate Reference System by Reference*>>
|===
