[[rc-domainset-subset-section]]
== Requirements Class DomainSet Subset

The `DomainSet Subset` Requirements Class defines the application of query parameters against the DomainSet of a Coverage resource using the HTTP GET operation. The effect is to generate a subset of the coverage DomainSet. That subset is then returned to the client in the HTTP response.

include::requirements/requirements_class_domainset_subset.adoc[]

NOTE: Path = /collections/{collection_id}/coverage/domainset

Implementors of this Requirements Class must also implement the <<rc-geodata-coverage-section,`GeoData Coverage`>> Requirements Class.

[[req_domainset-subset_dependency-geodata-coverage]]
include::./requirements/domainset-subset/REQ_dependency-geodata-coverage.adoc[]

=== Parameter Requirements

The OGC API - Common - Part 2: Geospatial Data Standard identifies query parameters that have been standardized for use in OGC API standards. This Requirements Class defines how three of those parameters are used to create subsets of hosted CIS Coverage DomainSets.

* <<bbox-parameter-domainset-subset-requirements,bbox>>: Bounding Box
* <<datetime-parameter-domainset-subset-requirements,datetime>>: Date and Time
* <<subset-parameter-domainset-subset-requirements,subset>>: Subset

The behavior generated by these parameters is specific to the operation and resource upon which they are applied. The behaviors specific to the `DomainSet Subset` Requirements Class are defined in the <<domainset-subset-target-resource-requirements,Target Resource Requirements>> section.

The use of these parameters should be documented in the API definition.

include::./recommendations/domainset-subset/REC_subset-parameter-documentation.adoc[]

[[bbox-parameter-domainset-subset-requirements]]
==== Parameter bbox

[[re_domainset_subset-bbox]]
include::../api_modules/bbox/requirements_module_bbox.adoc[]

[[datetime-parameter-domainset-subset-requirements]]
==== Parameter datetime

[[re_domainset_subset-datetime]]
include::../api_modules/datetime/requirements_module_datetime.adoc[]

[[subset-parameter-domainset-subset-requirements]]
==== Parameter subset

[[re_domainset_subset-select]]
include:../api_modules/subset/requirements_module_subset.adoc[]

[[domainset-subset-target-resource-requirements]]
=== Target resource Requirements

The target of the parameters defined in this Requirements Class is the DomainSet of CIS Coverage. The purpose of these parameters is to extract a subset of the <<domainset-clause,Domainset>> resource to be returned in the response to a <<domainset-clause,/coverage/domainset>> request.

==== General Requirements

The payload shall be a valid CIS Domainset as documented in <<coverage-domainset-section,Coverage Domain Set>> section of this Standard.

NOTE: What are the error conditions and corresponding status codes?

==== Spatial and Temporal Filtering

A client may select a subset of the hosted DomainSet using the <<bbox-parameter-subset-requirements,``bbox``>> and the <<datetime-parameter-subset-requirements,``datetime``>> parameters.

The requirements governing the processing of these parameters are:

include::./requirements/domainset-subset/REQ_domainset-subset-bbox-select.adoc[]

include::./requirements/domainset-subset/REQ_domainset-subset-datetime-select.adoc[]

==== Non-spatial Filtering

A client may select a subset of the hosted DomainSet using the <<subset-parameter-subset-requirements,``subset``>> parameter.

The requirements governing the processing of this parameter are:

include::./requirements/domainset-subset/REQ_domainset-subset-select.adoc[]

==== Response Generation

The response returned to the requestor shall be the intersection of the spatial, temporal, and non-spatial filtering.

include::./requirements/domainset-subset/REQ_domainset-subset-response.adoc[]

=== DomainSet Subsetting Examples

include::examples/examples_domainset_subsetting.adoc[]
