== Requirements Class Coverage Subset

The Subset Requirements Class defines parameters for sub-setting n-dimensional Range Sets. Subsetting parameters may be mixed with other parameters, in no particular order, in the query part of a URL.

include::requirements/requirements_class_coverage_subset.adoc[]

The subset parameter is defined in the following Requirement:

include::requirements/coverage-subset/REQ_cov-subset-definition.adoc[]

The following permission is granted to facilitate slicing data sparsely populated across a dimension, such as Earth Observation imagery:

include::recommendations/coverage-subset/PER_subset-slice-sparse-dimensions.adoc[]

The results of using a subset parameter are defined by the following Requirement:

include::requirements/coverage-subset/REQ_cov-subset-success.adoc[]

=== Subsetting Examples

include::examples/examples_subsetting.adoc[]

== Requirements Class Coverage Scaling

The Scaling Requirements Class defines parameters for retrieving data from n-dimensional Range Sets at a resolution different than the original.
Scaling parameters may be mixed with other parameters, in no particular order, in the query part of a URL.

include::requirements/requirements_class_coverage_scaling.adoc[]

The scaling parameters are defined in the following Requirement:

include::requirements/coverage-scaling/REQ_cov-scaling-definition.adoc[]

The results of using a scaling parameter are defined by the following Requirement:

include::requirements/coverage-scaling/REQ_cov-scaling-success.adoc[]

=== Scaling Examples

include::examples/examples_scaling.adoc[]

== Requirements Class Coverage Range Subset

The Range Subset Requirements Class defines parameters for selecting a subset of the bands (defined in the Range Type) to retrieve from Range Sets.
Range subsetting parameters may be mixed with other parameters, in no particular order, in the query part of a URL.

include::requirements/requirements_class_coverage_rangesubset.adoc[]

The range-subset parameter is defined in the following Requirement:

include::requirements/coverage-rangesubset/REQ_cov-rangesubset-definition.adoc[]

The results of using a range-subset parameter are defined by the following Requirement:

include::requirements/coverage-rangesubset/REQ_cov-rangesubset-success.adoc[]

=== Range Subsetting Examples

include::examples/examples_rangesubsetting.adoc[]

== Requirements Class Coverage Tiles

The Tiles Requirements Class defines how to combine the OGC API - Tiles building blocks with the Coverages API to request coverage tiles.
Coverages parameters such as for subsetting additional dimensions not covered by the Tiles 2D Tile Matrix Set (such as time or elevation),
or for range subsetting, can be used together with the path for requesting individual tiles.

include::requirements/requirements_class_coverage_tiles.adoc[]

The capability to request tiles is defined in the following Requirement:

include::requirements/coverage-tiles/REQ_cov-tiles-definition.adoc[]

The results of requesting coverage tiles are defined by the following Requirement:

include::requirements/coverage-tiles/REQ_cov-tiles-success.adoc[]

=== Coverage Tiles Examples

include::examples/examples_coverage_tiles.adoc[]


== Requirements Class DomainSet Subset

The DomainSet Subset Requirements Class defines the use of parameters for sub-setting the domainset of the coverage.

include::requirements/requirements_class_domainset_subset.adoc[]

The subset parameter is defined in the following Requirement:

include::requirements/domainset-subset/REQ_cov-subset-definition.adoc[]

The results of using a subset parameter are defined by the following Requirement:

include::requirements/domainset-subset/REQ_cov-subset-success.adoc[]

=== DomainSet Subsetting Examples

include::examples/examples_domainset_subsetting.adoc[]
