== Terms and Definitions
This document uses the terms defined in Sub-clause 5 of https://github.com/opengeospatial/oapi_common/blob/master/19-072.pdf[OGC API - Common - Part 1: Core] (OGC 19-072), which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== Coverage
function which returns values from its range for any direct position within its domain (as defined in OGC Abstract Topic 6)

NOTE: Although a coverage is most often thought of as a regularly gridded data, the internal model of the coverage function may also consist of other things such as
iregularly gridded data, a point cloud, or a collection of curves, surfaces, or solids, or a purely mathematical function.

=== Regular grid
grid whose grid lines have a constant distance along each grid axis

=== Irregular grid
Grid whose grid lines have individual distances along each grid axis

=== Partition [of a coverage]
separately stored coverage acting, by being referenced in the coverage on hand, as one of its components

=== Resolution [of a grid]
the distance between data points on a regular grid

NOTE: The `resolution` query parameter of this API allows clients to request data resampled to a particular resolution, whether the output is returned in a gridded or non-gridded coverage format,
but that output data may not be suitable for purposes requiring data at the true resolution being requested.

=== Resolution [of data]
the smallest difference between observations or measurements that can be meaningfully distinguished, whether the data is actually gridded or not

=== (Geometric) Sensor model
mathematical description of the relationship between the three-dimensional object space and the corresponding dimensions of the associated coverage produced by a
https://www.iso.org/obp/ui/en/#iso:std:iso:ts:19130:-3:ed-1:v1:en:term:3.5[sensor (3.5)]

NOTE: Adapted from https://www.iso.org/obp/ui/en/#iso:std:iso:ts:19130:-3:ed-1:v1:en:term:3.6[ISO 19130-3 sensor model (3.6)]

=== Transformation grid
grid whose direct positions are given by some transformation algorithm not further specified in this standard

=== Abbreviated terms

CIS::  Coverage Implementation Schema

SWE::  Sensors Web Enablement

UCUM:: Unified Code for Units of Measure

WCS::  Web Coverage Service
