== Scope
This https://docs.opengeospatial.org/DRAFTS/19-087.html[_OGC API - Coverages_] Standard establishes an access mechanism
for coverages as defined by the https://portal.ogc.org/files/?artifact_id=19820[OGC Abstract Specification Topic 6] / https://www.iso.org/standard/40121.html[ISO 19123]
_Schema for coverage geometry and functions_ through a Web API which can be described by an API description language such as the https://www.openapis.org/[OpenAPI specification].

=== API Scope
The functionality specified in the _OGC API - Coverages_ addresses a similar scope as that of the http://docs.opengeospatial.org/is/17-089r1/17-089r1.html[OGC Web Coverage Service (WCS) 2.1 Interface Standard].
It is expected that _OGC API - Coverages_ and WCS implementations will be able to interoperate, allowing developers to pick the solution best suited for their requirements, and to also implement one as a façade on top of the other.

The OGC is using an incremental approach to OGC API standards development. The initial goal is to develop a relatively simple API standard which will meet the needs of a large percentage of the implementation community.
Additional capabilities will be added based on community demand. The functionality defined in _Part 1_ is:

* Description of a coverage, including its domain (dimensions/axes, based on the Uniform Additional Dimensions of https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data])
and range (schema of the fields for the values of each cell, based on https://docs.ogc.org/is/23-058r2/23-058r2.html[OGC API - Common - Part 3: Schemas]) --
these OGC API - Common components provide equivalent functionality to the DomainSet and RangeType of the OGC Coverage Implementation Schema (CIS), but using a different logical model
which is consistent across multiple OGC Web API Standards,
* Retrieval of a coverage with support for content type negotiation,
* Subsetting (trimming or slicing along one or more dimensions/axes of its domain),
* Field selection (retrieving only certain fields of the range, also known as range subsetting),
* Scaling (retrieving a downsampled or upsampled coverage),
* Selection of an output Coordinate Reference System (CRS) which may differ from the native CRS,
* Retrieving part of a coverage as tiles (in combination with http://docs.ogc.org/DRAFTS/20-057.html[_OGC API - Tiles_], each tile corresponding to a specific subset trimmed along two spatial dimensions, and the response downsampled for lower resolution tile matrices),

=== Content Scope
The _OGC API - Coverages_ standard provides access to content which complies with the
https://docs.ogc.org/as/07-011r2/07-011r2/pdf[Topic 6: Schema for coverage geometry and functions] of the
https://www.ogc.org/standards/abstract-specification/[OGC Abstract Specification].
This includes, but is not limited to, support for gridded (regular and irregular) and multi-point coverages (e.g., point clouds).

The content of the coverage can be encoded/formatted using any suitable logical model and physical encodings, such as those defined by http://www.opengis.net/doc/IS/cis/1.1.1[Coverage Implementation Schema (CIS) 1.1],
https://www.ogc.org/standards/netcdf[netCDF], https://covjson.org/[CoverageJSON], https://www.ogc.org/standards/geotiff[GeoTIFF] (including https://www.cogeo.org/[Cloud Optimized GeoTIFF (COG)]),
or https://www.asprs.org/divisions-committees/lidar-division/laser-las-file-format-exchange-activities[LAS]/LAZ (including https://copc.io/[Cloud Optimized Point Cloud (COPC)]).
