== Requirements Class "Core"

[[core-overview]]
=== Overview

include::requirements/requirements_class_core.adoc[]

NOTE: The following is from the Maps API. Replace with similar content for coverages. 

A map distribution of a dataset is a pictorial representation of the 
dataset or the collections it has been divided in. To create a pictorial representation a style is added to the data in the collections. Styles are defined internally and have a identifier. New styles can be added or modified if the OGC API - Maps draft specification works in combination with the OGC API - Styles draft specification (also developed in the Testbed-15). After associating collections to styles, a map can be retrieved by specifying a set of parameters that will determine its resolution (width, height, bounding  box and CRS) or can be retrieved as tiles.

This section defines the core part of the OGC API - Maps draft specification that allows defining a map representation for a collection. To retrieve a fragment of the map, this section needs to be combined with an OGC API - Tiles draft specification or with the OGC API - Maps - Map extension draft specification.

To keep the core of the OGC API - Maps draft specification simple, only includes a mechanism to select the default style but it does not define any mechanism to define or select a style other than the default one. The core specification only assumes that the service is capable of knowing which is the default style while the client ignores all the details about it (including its name).

[[dependencies]]
=== Dependencies

The OGC API-Coverages standard is an extension of the OGC API-Common standard. Therefore, an implementation of API-Coverages must first satisfy the appropriate Requirements Classes from API-Common.

include::requirements/core/REQ_api-common.adoc[]

<<mapping-to-common>> Identifies the API-Common Requirements Classes which are applicable to each section of this Standard. Instructions on when and how to apply these Requirements Classes are provided in each section. 

[#mapping-to-common,reftext='{table-caption} {counter:table-num}']
.Mapping API-Coverages Sections to API-Common Requirements Classes
[width="90%",cols="2,6"]
|====
^|*API-Coverage Section* ^|*API-Common Requirements Class*
|<<landing-page,API Landing Page>>| http://www.opengis.net/spec/ogcapi_common/1.0/req/core
|<<api-definition,API Definition>>| http://www.opengis.net/spec/ogcapi_common/1.0/req/core
|<<conformance-classes,Declaration of Conformance Classes>>| http://www.opengis.net/spec/ogcapi_common/1.0/req/core
|<<collections,Collections>>| http://www.opengis.net/spec/ogcapi_common/1.0/req/collections
|<<collections,OpenAPI 3.0>>| http://www.opengis.net/spec/ogcapi_common/1.0/req/oas30
|<<collections,GeoJSON>>| http://www.opengis.net/spec/ogcapi_common/1.0/req/geojson
|<<collections,HTML>>| http://www.opengis.net/spec/ogcapi_common/1.0/req/html
|====

[[path-summary]]
=== Path Summary

Resources exposed through an OGC API are accessed through a Universal Resource Identifier <<rfc3986,(URI).>> URIs are composed of three sections:

* Service Offering: The service endpoint (subsequently referred to as Base URL) 
* Access Paths: Unique paths to Resources
* Query: Parameters for subsetting a Resource or Resources

<<coverage-paths>> summarizes the access paths defined in this standard.

[#coverage-paths,reftext='{table-caption} {counter:table-num}']
.Coverage API Paths
[width="90%",cols="2,4",options="header"]
|===
^|**Path Template** ^|**Resource**
2+^|**Common**
|{root}/ |Landing page
|{root}/api |API Description
|{root}/conformance |Conformance Classes
|{root}/collections |Metadata describing the spatial collections available from this API.
|{root}/collections/{collectionId} |Metadata describing the collection which has the unique identifier `{collectionId}`
2+^|**Coverages**
|{root}/collections/{collectionId}/coverage |A general description of the coverage identified by {collectionId} including the coverage's envelope.
|{root}/collections/{collectionid}/coverage/description |returns the whole coverage description consisting of domainset, rangetype, and metadata (but not the rangeset)
|{root}/collections/{collectionid}/coverage/domainset |returns the coverage's domain set definition
|{root}/collections/{collectionid}/coverage/rangetype |returns the coverage's range type information (i.e., a description of the data semantics)
|{root}/collections/{collectionid}/coverage/metadata |returns the coverage's metadata (may be empty)
|{root}/collections/{collectionid}/coverage/rangeset |returns the coverage's range set, i.e., the actual values in the coverage's Native Format (see format encoding for ways to retrieve inspecific formats)
|{root}/collections/{collectionid}/coverage/all |returns all of the above namely the coverage's domainset, rangetype, meatadata, and rangeset comparable to a GetCoverage response
|===

Where:

* {root} = URI for the API server
* {collectionId} = an identifier for a specific collection

[[landing-page]]
=== API landing page

The landing page provides links to start exploring the resources offered by the API instance. It mainly consists of a list of links. OGC API-Common already requires some common links. Those links are sufficient for this core.

==== Operation

TBD

==== Response

TBD

NOTE: Schema for the Landing Page

NOTE: Example response document

==== Error situations

See <<http-status-codes,HTTP Status Codes>> for general guidance.

[[api-definition]]
=== API definition

==== Operation

Every API is expected to provide a definition that describes the capabilities of the server and which can be used by developers to understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

include::requirements/core/REQ_api-definition-op.adoc[]

include::recomendations/core/PER_api-definition-uri.adoc[]

Note that multiple API definition formats can be supported.

==== Response

include::requirements/core/REQ_api-definition-success.adoc[]

include::recomendations/core/REC_api-definition-oas.adoc[]

If the server hosts the API definition under the base path of the API (for example, at path `/api`, see above), there is no need to include the path of the API definition in the API definition itself.

The idea is that any OGC API Features implementation can be used by developers that are familiar with the API definition language(s) supported by the server. For example, if an OpenAPI definition is used, it should be possible to create a working client using the OpenAPI definition. The developer may need to learn a little bit about geometry data types, etc., but it should not be required to read this standard to access the data via the API.

In case the API definition is based on OpenAPI 3.0, consider the <<two_appraoches_oas,two approaches>> discussed in OpenAPI requirements class.

==== Error situations

See <<http_status_codes>> for general guidance.

[[conformance-classes]]
=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API 
standards and extensions - and not "just" a specific API / server, the 
API has to declare the requirements classes it implements and conforms 
to.

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

https://github.com/opengeospatial/OGC-API-Maps/blob/master/standard/requirements/maps/core/REQ_conformance-success.adoc[requirements/maps/core/REQ_conformance-success.adoc]

In the conformance page (typically in JSON format) the links follow 
the link schema defined in the OGC API - Common. The following is an 
example fragment of the response of an OGC API maps conformance 
information page.

Example 1. Conformance Information Page fragment

[source,java]
----
{
  "conformsTo": [
  [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core"
  ]
}
----

=== https://github.com/opengeospatial/OGC-API-Maps/blob/master/standard/clause_8_map_core.adoc#collections[<svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg>]

==== Response



=== Coverage Access Paths

In this clause, the path component of https://github.com/opengeospatial/ogc_api_coverages[OGC API - Coverages] access is established.

Access paths follow the XML Schema of http://docs.opengeospatial.org/is/09-146r6/09-146r6.html[CIS] in their structure.

To access coverage service constituents, such as formats supported, OGC 14-121 Web Query Service provides guidance, see https://github.com/opengeospatial/ogc_api_coverages/blob/master/CIS%2BWCS-standards/14-121_Web-Query-Service_2016-06-19.pdf[https://github.com/opengeospatial/ogc_api_coverages/blob/master/CIS%2BWCS-standards/14-121_Web-Query-Service_2016-06-19.pdf].

=== Coverage Access

The second part is about coverage access, which (as described earlier) is driven by the coverage structure and, hence, given:

*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage/description[http://acme.com/oapi/collections/{collectionid}/coverage/description] -- returns the whole coverage description consisting of domainset, rangetype, and metadata (but not the rangeset)

*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage/domainset[http://acme.com/oapi/collections/{collectionid}/coverage/domainset]  -- returns the coverage’s domain set definition

*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage/rangetype[http://acme.com/oapi/collections/{collectionid}/coverage/rangetype]  -- returns the coverage’s range type information (i.e., a description of the data semantics)

*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage/metadata[http://acme.com/oapi/collections/{collectionid}/coverage/metadata]  -- returns the coverage’s metadata (may be empty)

*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage/rangeset[http://acme.com/oapi/collections/{collectionid}/coverage/rangeset]
  -- returns the coverage’s range set, i.e., the actual values in the
coverage’s Native Format (see format encoding for ways to retrieve inspecific formats)

*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage/all[http://acme.com/oapi/collections/{collectionid}/coverage/all]
  -- returns all of the above namely the coverage’s domainset,
rangetype, meatadata, and rangeset comparable to a GetCoverage response

=== Coverage Subsetting

The third part is about query parameters:

*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage?SUBSET=Lat(40,50)&SUBSET=Long(10,20)[http://acme.com/oapi/collections/{collectionid}/coverage?SUBSET=Lat(40]  -- returns a coverage cutout between (40,10) and (50,20), as multipart coverage

*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage/rangeset?SUBSET=Lat(40,50)&SUBSET=Long(10,20)[http://acme.com/oapi/collections/{collectionid}/coverage/rangeset?SUBSET=Lat(40]  -- returns a coverage cutout between (40,10) and (50,20), in the coverage’s Native Format

*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage?SUBSET=time(%222019-03-27%22)[http://acme.com/oapi/collections/{collectionid}/coverage?SUBSET=time("2019-03-27")]  -- returns a coverage slice at the timestamp given (in case the coverage is Lat/Long/time the result will be a 2D image)

=== Coverage Query Parameters

In this clause, the query component of https://github.com/opengeospatial/ogc_api_coverages[OGC API - Coverages] access is established.

Subsetting parameters may be mixed in a query part, in no particular order.

