== Conformance
Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document.
The framework, concepts, and methodology for testing, and the criteria to claim conformance, are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The one Standardization Target for this standard is Web APIs.

_OGC API - Common_ provides a common foundation for OGC API standards.
Some conformance classes of this standard have a dependency on, or are designed to be easily integrated with, conformance classes defined in _OGC API - Common_ _Part 1_ and/or _Part 2,
as well as within Web API conforming to additional OGC API standards.

This standard identifies nineteen Conformance Classes. Each Conformance Class has an associated Requirements Class.
The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.
Only the Core requirements class is mandatory, all others are optional.

The Requirements Classes for _OGC API - Coverages_ are:

=== Requirements classes defining resources

* <<rc-core,*Core*>>
* <<rc-coverage-tiles,*Coverage Tiles*>>
* <<rc-scenes,*Coverage Scenes*>>

The _Core_ Requirements Class is the minimal useful service interface for an OGC Coverages API. The requirements specified in this Requirements Class are mandatory for all implementations of _OGC API - Coverages_.

The _Coverage Tiles_ Requirements Class defines how to combine the _OGC API - Tiles_ building blocks with the Coverages API to request coverage tiles.

The _Scenes_ Requirements Class defines how to present separate components of a coverage as individual scenes, in addition to an overall coverage of the whole collection.

=== Requirements classes defining query parameters

* <<rc-subsetting,*Subsetting*>>
* <<rc-scaling,*Scaling*>>
* <<rc-fieldselection,*Field Selection*>>
* <<rc-crs,*Coordinate Reference System*>>

The _Subset_ Requirements Class provides capabilities to select a sub-set of a `Coverage` using a multi-dimensional "bounding box" which is suitable for any coordinate reference system and any dimension.

The _Scaling_ Requirements Class defines parameters for retrieving data from n-dimensional Range Sets at a resolution different than the original.

The _Field Selection_ (Range Subsetting) Requirements Class defines parameters for selecting a subset of the bands (defined in the Range Type) to retrieve from Range Sets.

The _Coordinate Reference System_ Requirements Class defines the ability to request coverage data in an alternate output coordinate reference system.

=== Requirements classes defining resource representations

* <<rc-encoding-html,HTML>>
* <<rc-encoding-geotiff,GeoTIFF>>
* <<rc-encoding-netcdf,netCDF>>
* <<rc-encoding-cisjson,CIS JSON>>
* <<rc-encoding-coveragejson,CoverageJSON>>
* <<rc-encoding-las,LAS>>
* <<rc-encoding-laszip,LASZip>>
* <<rc-encoding-png,PNG>>
* <<rc-encoding-jpegxl,JPEG XL>>
* <<rc-encoding-jpeg2000,JPEG 2000>>
* <<rc-encoding-zarr,(Geo)Zarr>>
* <<rc-oas30,*OpenAPI 3.0*>>

The Encoding Requirements Classes address support for formats commonly used for encoding coverage data.

The _OpenAPI 3.0_ Requirements Class defines additonal requirements in addition to those defined in _OGC API - Common - Part 1: Core_ to facilitate identifying coverage resources from an OpenAPI 3.0 API Definition.

=== Summary of conformance URIs

[#table_conformance_urls,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
| Corresponding requirements class | Conformance class URI
| <<rc_core,Core>>                 | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/core
| <<rc_scaling,Scaling>>           | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/scaling
| <<rc_subsetting,Subsetting>>     | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/subsetting
| <<rc_subsetting,Field Selection>>| http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/fieldselection
| <<rc_crs,CRS>>                   | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/crs
| <<rc_tiles,Coverage Tiles>>      | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/tiles
| <<rc_scenes,Coverage Scenes>>    | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/scenes
| <<rc_html,HTML>>                 | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/html
| <<rc_tiff,GeoTIFF>>              | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/geotiff
| <<rc_netcdf,netCDF>>             | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/netcdf
| <<rc_cisjson,CIS JSON>>          | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/cisjson
| <<rc_coveragejson,CoverageJSON>> | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/coveragejson
| <<rc_las,LAS>>                   | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/las
| <<rc_laszip,LASZip>>             | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/laszip
| <<rc_png,PNG>>                   | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/png
| <<rc_jpegxl,JPEG XL>>            | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/jpegxl
| <<rc_jpeg2000,JPEG 2000>>        | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/jpeg2000
| <<rc_zarr,(Geo)Zarr>>            | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/zarr
| <<rc_oas30,OpenAPI 3.0>>         | http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/oas30
|===
