[[overview]]
== Overview

[[general-overview]]
=== General

_OGC API - Coverages - Part 1: Core_, hereafter sometimes referred to as the _Coverages API_, specifies the fundamental API building blocks for retrieving coverage data.
The spatial data community uses the term _coverage_ for homogeneous collections of values located in space/time such as: spatio-temporal sensor, image, simulation, and statistical data.
The _W3C/OGC Spatial Data on the Web Best Practices_ provide an overview of https://www.w3.org/TR/sdw-bp/#coverages[Coverages: describing properties that vary with location (and time)].

The OGC API family of standards enable access to resources using the HTTP protocol and its associated operations (GET, PUT, POST, etc.).
_OGC API - Common_ defines a set of capabilities which are shared by several OGC API standards.
Some of these other OGC API standards define capabilities to access data using a particular mechanism tailored to a specific resource type.
These standards can be integrated within the framework defined by _OGC API - Common_, including the concept of a landing page, API definition and conformance declaration (_Part 1_),
as well as providing access to one or more collections of geospatial data (_Part 2_).
OGC API standards also re-use common Web API building blocks such as resource paths (including associated path parameters),
response definitions for specific representations, schemas for request payloads and responses, or query parameters.
This common framework ensures consistency and allow for the integration of multiple OGC API standards within a single Web API implementation.

This _OGC API - Coverages_ standard defines an API with two goals:

* Provide access to *_Coverages_* conformant to the https://portal.ogc.org/files/?artifact_id=19820[OGC Abstract Specification Topic 6: Schema for coverage geometry and functions].
* Provide functionality comparable to that of the <<web-coverage-service-overview,OGC Web Coverage Service (WCS) standard>>.

This API standard allows efficient access to multidimensional geospatial data cubes, particularly when additional optional requirements classes complementing the functionality
defined in the "Core" requirements class allowing to subset the fields, area, time and resolution of interest, are implemented.

This data cube functionality can be further extended by integrating it with advanced processing capabilities
as defined by https://docs.ogc.org/is/18-062r2/18-062r2.html[_OGC API - Processes - Part 1: Core_] and https://docs.ogc.org/DRAFTS/21-009.html[_OGC API - Processes - Part 3: Workflows and Chaining_ (draft)]
(the _collection input_ and _collection output_ requirements classes in particular).

A future part extension to this standard is also foreseen for deriving new coverage fields based
on a simple expression language such as the https://docs.ogc.org/DRAFTS/21-065.html[_OGC Common Query Language (CQL2)_], together with standardized mathematical and aggregation functions.

Resources exposed through an OGC API may be accessed through a Universal Resource Identifier <<rfc3986,(URI).>>
URIs are composed of three sections:

* Dataset distribution API: The endpoint corresponding to a dataset distribution, where the landing page resource as defined in _OGC API - Common - Part 1: Core_ is available (subsequently referred to as Base URI or `{root}`)
* Access Paths: Unique paths to Resources
* Query: Parameters to adjust the representation of a Resource or Resources, such as requesting a particular subset or downsampled resolution of the data

Access Paths are used to build resource identifiers. Most of these paths are fixed, with the exception of the _OGC API - Common - Part 1_ `/api` service description / documentation.

All resources are also accessible by following links starting from the landing page, with a specific link relation type used from one resource to another, as detailed in <<conventions-link-relations>>.

The following table summarizes the resource paths defined in this standard, as well as those inherited from _OGC API - Common_.

[#coverage-paths,reftext='{table-caption} {counter:table-num}']
._Coverages API_ Resources
[width="100%",cols="3,5",options="header"]
|===
^|Resource URI                                   ^|Description
2+|**_OGC API - Common - Part 1_**
|`{root}/`                                    |Landing page for this dataset distribution
|`{root}/api`                                 |API description (e.g., Open API Specification) and documentation (e.g., HTML)
|`{root}/conformance`                         |Declaration of supported conformance classes
2+|**_OGC API - Common - Part 2_** (extended with additional properties for the **_Coverages API_**)
|`{root}/collections`                         |The list of all collections available, some or all of which may be accessible using this _Coverages API_. Each of these collections contains a minimal subset of the object collection resource object described immediately below.
|`{root}/collections/{collectionId}`          |Description for the collection with the unique identifier `{collectionId}`, which may be accessible as a coverage. The resource includes elements such as an `id`, `title`, `description`, available `crs` and `extent`. This `extent` describes the domain of the coverage for each dimension, including the overall envelope, detailed sub-intervals where data is available, and/or a regular or irregular `grid`. This object also includes links to resources pertaining to this collection. For coverages, a link to the record schema described below will be included. This resource is comparable to a WCS *_DescribeCoverage_* response, with the exception that the schema, corresponding to Coverage Implementation Schema (CIS) _range type_, needs to be retrieved separately.
2+|**_OGC API - Coverages - Part 1_**
|`{root}/collections/{collectionId}/schema`   |Returns the schema for the coverage fields or properties of values available at each direct position. At minimum, a _JSON Schema_ representation of this resource is available. This resource is comparable to the CIS _range type_ portion of the WCS *_DescribeCoverage_* response, and is retrieved separately from the collection description to accommodate more complex record schemas including several record fields and/or detailed semantic annotations.
|`{root}/collections/{collectionId}/coverage` |Returns the coverage data, including any self-describing information (such as the _domain set_, _range type_ and _metadata_ components in addition to the _range set_ of CIS). This resource is comparable to a WCS *_GetCoverage_* response.
2+|**_OGC API - Tiles - Part 1_**
|`{root}/collections/{collectionId}/coverage/tiles`                                              |Returns the list of tilesets available for this coverage.
|`{root}/collections/{collectionId}/coverage/tiles/{tileSetId}`                                  |Returns an individual coverage tileset for a particular 2D Tile Matrix Set
|`{root}/collections/{collectionId}/coverage/tiles/{tileSetId}/{tileMatrix}/{tileRow}/{tileCol}` |Returns an individual coverage tile for a particular 2D Tile Matrix Set, tile matrix, tile row and tile column
2+|**_OGC API - Coverages - Part 1_ (Scenes requirements class)**
|`{root}/collections/{collectionId}/scenes`                       |Returns the list of scenes available for this coverage (for multi-scenes coverages, when the _Scenes_ requirement class is supported)
|`{root}/collections/{collectionId}/scenes/{sceneId}`             |Returns the scenes metadata for an individual scene
|`{root}/collections/{collectionId}/scenes/{sceneId}/coverage`    |Returns the coverage data for an individual scene
2+|**_OGC API - Tiles - Part 1_ (for multi-scene coverage)**
|`{root}/collections/{collectionId}/scenes/{sceneId}/coverage/tiles`                                              |Returns the list of tilesets available for this scene's coverage
|`{root}/collections/{collectionId}/scenes/{sceneId}/coverage/tiles/{tileSetId}`                                  |Returns an individual scene coverage tileset for a particular 2D Tile Matrix Set
|`{root}/collections/{collectionId}/scenes/{sceneId}/coverage/tiles/{tileSetId}/{tileMatrix}/{tileRow}/{tileCol}` |Returns an individual scene coverage tile for a particular 2D Tile Matrix Set, tile matrix, tile row and tile column
|===

Where:

* `{root}` = URI of the landing page for the API distributing the dataset
* `{collectionId}` = an identifier for a specific coverage (collection)
