[[rc-geodata-coverage-section]]
== Requirements Class "GeoData-Coverage"

include::requirements/requirements_class_geodata_coverage.adoc[]

API-Common starts with the assumption that spatial resources are organized into collections. An API will expose one or more collections. The API-Common Collections Requirements Class defines how to organize and provide access to a collection of collections.

API-Coverages observes that a coverage is a collection of measured values. Therefore, a coverage is a collection.

The `GeoData-Coverage` Requirements Class extends API-Common to define the requirements for locating, understanding, and accessing a collection which is a coverage. 

Three resources and their operations are defined in this Requirements Class. They are summarized in <<collection-resources>>.

[#collection-resources,reftext='{table-caption} {counter:table-num}']
.Collection Resources
[width="90%",cols="10,10,5,20",options="header"]
|===
^|Resource ^|URI ^|HTTP Method ^|Description
|<<collections-metadata-section,Collections>> |/collections ^|GET |Information which describes the set of available Collections 
|<<collection-description-section,Collection>> |/collections/{collectionId} ^|GET |Information about a specific collection of geospatial data with links to distribution
|<<coverage-access-section,Coverages>> |/collections/{collectionId}/coverage ^|GET |A coverage conformant with the <<CIS_1_1,CIS>> Standard
|===

[[geodata-coverage-dependencies-section]]
=== Dependencies

The OGC API-Coverages standard is an extension of the OGC API - Common - Part 1: Core and Part 2: Geospatial Data Standards. Therefore, an implementation of API-Coverages must first satisfy the appropriate Requirements Classes from API-Common.

include::recommendations/geodata-coverage/REC_dependency-core.adoc[]

A Web API should provide a common look and feel to its clients. Part of that is consistency in the use of protocols and the construction of request URIs. The `core` Requirements Class provides that guidance for OGC Web APIs.  

include::recommendations/geodata-coverage/REC_dependency-landing-page.adoc[]

The landing page resource provides a common starting point for clients to explore an API. Consistency in the structure of a landing page further advances the goal of a common look and feel for OGC Web API. Any implementation which is not intended for hosting on an existing API should implement the `landing page` Requirements Class. 

include::requirements/geodata-coverage/REQ_dependency-collections.adoc[]

The OGC Collections API uses the `/collections` and `/collection` resources defined in API-Common Part 2. Therefore, conformance with the Requirements Class which defines these resources is required.

include::recommendations/geodata-coverage/REC_dependency-simple-query.adoc[]

A query to the `/collections` resource will return a `/collection` resource for every collection hosted through that API. That could be a very large body of data. The `simple query` Conformance Class defines parameters which a client can use to limit which collections to include in the response.

The `Collections` and `Simple Query` Requirements Classes have a direct bearing on the `GeoData Coverage` Requirements Class. The applicable requirements from Common Part 2 are identified in <<collections-requirements-table>>. 

[#collections-requirements-table,reftext='{table-caption} {counter:table-num}']
.Collections Requirements 
[width="90%",cols="2,6a",options="header"]
|====
^|**Section** ^|**Requirements** 
2+^|From Collections Requirements Class
^|Operation |/req/collections/rc-md-op
^|Response |/req/collections/rc-md-success
^|Content |/req/collections/rc-md-links +
/req/collections/rc-timeStamp +
/req/collections/rc-md-items
2+^|From Simple Query Requirements Class
^|Parameter bbox |/req/collections/rc-bbox-definition +
/req/collections/rc-bbox-response
^|Parameter datetime |/req/collections/rc-datetime-definition +
/req/collections/rc-datetime-response
^|Parameter limit |/req/collections/rc-limit-definition +
/req/collections/rc-limit-response
^|Target Resource Filtering |/req/collections/rc-bbox-collection-response +
/req/collections/rc-datetime-collection-response +
/req/collections/rc-limit-collection-response +
/req/collections/rc-numberMatched +
/req/collections/rc-numberReturned
|====

[[collections-metadata-section]]
=== Collections

The `Collections` operation returns a set of metadata which includes descriptions for each of the collections available from this API. All of the collections described on a Coverages API will be be <<CIS_1_1,CIS>> coverages. 

The `Collections` operation is defined in the http://www.opengis.net/spec/ogcapi-common-2/1.0/req/collections Requirements Class. 

Optional query parameters for use with the `Collections` operation are defined in the http://www.opengis.net/spec/ogcapi-common-2/1.0/req/simple-query Requirements Class.

The applicable requirements from Common Part 2 are identified in <<collections-requirements-table>>. 

==== Operation

The `GeoData-Coverage` Requirements Class does not modify the `Collections` operation as defined in API-Common. 

==== Response

The `GeoData-Coverage` Requirements Class does not modify the `Collections` response as defined in API-Common except for the extension of the `Collection Resource` as described in <<collection-resource-definition-section,Collection Resource Definition>>. 

==== Error situations

See <<http-status-codes,HTTP Status Codes>> for general guidance.

[[collection-description-section]]
=== Resource Collection

Each resource collection (Coverage) is described by a set of metadata. That metadata can be accessed directly using the ``/collections/{collectionId}`` path and as an entry in the ``collections`` property of the ``/Collections`` resource.

==== Operation

The `GeoData-Coverage` Requirements Class does not modify the `/collections/{collectionId}` operation as defined in API-Common. 

==== Response

The `GeoData-Coverage` Requirements Class does not modify the `/collections/{collectionId}` response as defined in API-Common except for the extension of the `Collection Resource` as described in <<collection-resource-definition-section,Collection Resource Definition>>. 

==== Error situations

See <<http-status-codes,HTTP Status Codes>> for general guidance.

If the parameter collectionId does not exist on the server, the status code of the response will be 404.

[[collection-resource-definition-section]]
=== Collection Resource Definition

The Collection Resource is the set of metadata which describes a single collection, or in the the case of API-Coverages, a single Coverage. An abbreviated copy of this information is returned for each Coverage in the `/collections` response. 

Due to the multi-dimensional nature of coverages, it is desireable for an API to describe the extent of a coverage along those additional dimensions. The `GeoData Coverage` Requirements Class addresses this need through an extension of the Collection Resource which supports additional dimensions. This is accomplished by replacing the `Extent` module with the `Extent-UAD` module. The `Extent-UAD` module adds an element to the `Extent` module which identifies the content-specific axis as well as the intersecting intervals along those axis.  This extension has been designed so that a Collection with a Extend-UAD will still comply with API-Common Part 2. Likewise, a Collection which is conformant with API-Common Part 2 will also be conformant with API-Coverages.

include::requirements/geodata-coverage/REQ_coverage-collection-definition.adoc[]

include::../api_modules/extent-uad/requirements_module_extent-uad.adoc[]

[[coverage-access-section]]
=== Coverage Access

OGC API Common provides access to metadata about collections. The `GeoData-Coverages` Requirements Class extends that foundation to provide access to the individual Coverages.

A `Coverage` is a collection of measured values. The structure of that collection is defined by the <<CIS_1_1,CIS standard>>. A CIS Coverage contains four principle components:

* A `DomainSet` component describing the coverage’s domain (the set of “direct positions”, i.e., the locations for which values are stored in the coverage)
* A `RangeType` component which describes the coverage's `RangeSet` data structure (in the case of images usually called the “pixel data type”).
* A `RangeSet` component containing the stored values (often referred to as “pixels”, “voxels”) of the coverage.
* A `Metadata` component which represents an extensible slot for metadata. The intended use is to hold any kind of application-specific metadata structures.

A coverage containing the `DomainSet`, `RangeType`, `RangeSet`, and `Metadata`  components is accessible at

* The relative path `/coverage`
* The link relation `ogc:coverage:coverage`

The `DomainSet` and `RangeType` are accessible from resources referenced through links within the `/collections/{collectionId}` resource,
using the relation types `http://www.opengis.net/def/rel/ogc/1.0/coverage-domainset` and
`http://www.opengis.net/def/rel/ogc/1.0/coverage-rangetype`, respectively.
Those links may either point to separate resource, in which case the recommended paths are `/collections/{collectionId}/coverage/domainset` and
`/collections/{collectionId}/coverage/rangetype`, or point to the coverage description resource itself the domain set and/or range type are
embedded. In the latter case those links will point specifically to properties using `#`, e.g.,
`#domainset` and `#rangetype`.

The `RangeSet` may be available as its own resource as well, if supported by the selected representation (format).

If `Metadata` is available, it will also be be available as its own resource.

[[coverage-clause]]
==== Coverage

The `Coverage` operation returns all the components of the coverage (rangeset, domain set, range type, metadata). It is comparable to a WCS GetCoverage operation.

===== Operation

The `Coverage` operation is defined by the following requirement.

include::requirements/geodata-coverage/REQ_coverage-op.adoc[]

===== Response

A successful response to the `Coverage` operation shall meet the following requirement.

include::requirements/geodata-coverage/REQ_coverage-success.adoc[]

[#coverage--schema,reftext='Coverage Response Schema']
.Coverage Response Schema
[source,yaml]
----
include::openapi/schemas/cis/coverage-schema.yaml[]
----

The following JSON fragment is an example of a response to a Coverage request.

[#coverage-all-example,reftext=`Coverage Example`]
.Coverage Example
[source,json]
----
include::examples/JSON/coverage_example.json[]
----

===== Error situations

include::requirements/geodata-coverage/REQ_coverage-failure.adoc[]

See <<http-status-codes,HTTP Status Codes>> for general guidance.

[[coverage-domainset-clause]]
==== Coverage Domain Set

The `Coverage Domain Set` operation returns the coverage’s domain set.

===== Operation

The `Coverage Domain Set` operation is defined by the following requirement.

include::requirements/geodata-coverage/REQ_domainset-op.adoc[]

===== Response

A successful response to the `Coverage Domain Set` operation shall meet the following requirement.

include::requirements/geodata-coverage/REQ_domainset-success.adoc[]

[#coverage-domainset-schema,reftext='Coverage Domain Set Response Schema']
.Coverage Domain Set Response Schema
[source,yaml]
----
include::openapi/schemas/cis/domainSet.yaml[]
----

The following JSON fragment is an example of a response to a Coverage DomainSet request.

[#coverage-domainset-example,reftext=`Coverage DomainSet Example`]
.Coverage DomainSet Example
[source,json]
----
include::examples/JSON/coverage_domainset_example.json[]
----

===== Error situations

See <<http-status-codes,HTTP Status Codes>> for general guidance.

[[coverage-rangetype-clause]]
==== Coverage Range Type

The `Coverage Range Type` operation returns the coverage’s range type information (i.e., a description of the data semantics)

===== Operation

The `Coverage Range Type` operation is defined by the following requirement.

include::requirements/geodata-coverage/REQ_rangetype-op.adoc[]

===== Response

A successful response to the `Coverage Range Type` operation shall meet the following requirement.

include::requirements/geodata-coverage/REQ_rangetype-success.adoc[]

[#coverage-rangetype-schema,reftext='Coverage Range Type Response Schema']
.Coverage Range Type Response Schema
[source,yaml]
----
include::openapi/schemas/cis/rangeType.yaml[]
----

The following JSON fragment is an example of a response to a Coverage RangeType request.

[#coverage-rangetype-example,reftext=`Coverage RangeType Example`]
.Coverage RangeType Example
[source,json]
----
include::examples/JSON/coverage_rangetype_example.json[]
----

===== Error situations

See <<http-status-codes,HTTP Status Codes>> for general guidance.

[[coverage-rangeset-clause]]
==== Coverage Range Set

The `Coverage Range Set` operation returns the coverage’s range set, i.e., the actual values in the coverage’s Native Format (see <<media-types-section,Media Types>> for ways to retrieve inspecific formats)

===== Operation

The `Coverage Range Set` operation is defined by the following requirement.

include::requirements/geodata-coverage/REQ_rangeset-op.adoc[]

===== Response

A successful response to the `Coverage Range Set` operation shall meet the following requirement.

include::requirements/geodata-coverage/REQ_rangeset-success.adoc[]

[#coverage-rangeset-schema,reftext='Coverage Range Set Response Schema']
.Coverage Range Set Response Schema
[source,yaml]
----
include::openapi/schemas/cis/rangeSet.yaml[]
----

The following JSON fragment is an example of a response to a Coverage RangeSet request.

[#coverage-rangeset-example,reftext=`Coverage RangeSet Example`]
.Coverage RangeSet Example
[source,json]
----
include::examples/JSON/coverage_rangeset_example.json[]
----

===== Error situations

See <<http-status-codes,HTTP Status Codes>> for general guidance.

[[coverage-metadata-clause]]
==== Coverage Metadata

The `Coverage Metadata` operation returns the coverage’s metadata (may be empty)

===== Operation

The `Coverage Metadata` operation is defined by the following requirement.

include::requirements/geodata-coverage/REQ_metadata-op.adoc[]

===== Response

A successful response to the `Coverage Metadata` operation shall meet the following requirement.

include::requirements/geodata-coverage/REQ_metadata-success.adoc[]

[#coverage-metadata-schema,reftext='Coverage Metadata Response Schema']
.Coverage Metadata Response Schema
[source,yaml]
----
include::openapi/schemas/cis/metadata.yaml[]
----

The following JSON fragment is an example of a response to a Coverage Metadata request.

[#coverage-metadata-example,reftext=`Coverage Metadata Example`]
.Coverage Metadata Example
[source,json]
----
include::examples/JSON/coverage_metadata_example.json[]
----

===== Error situations

See <<http-status-codes,HTTP Status Codes>> for general guidance.
