== Requirements classes for encodings

NOTE: For encodings which are documented through Conformance Classes, the requirements for those encodings must include explicit requirements for the schema which must be used for validation of each request and response.  The oeprations specified define the scope of this Conformance Class.

NOTE: consider descriminiation between conformance class defined encodings and those which are negotated at a resource level.

This standard does not mandate any particular encoding or format. However, it does provide extensions for encodings which are commonly used in OGC APIs. These extensions include:

* Formats commonly used by Web Browsers (HTML and GeoTIFF)
* Data formats (RDF)
* Coverage formats (GeoTIFF, JPEG-2000, NetCDF)

None of these encodings are mandatory and an implementor of the _Core_ Requirements Class may choose implement none of them. Alternatively, an implementation of the _Core_ Requirements Class may choose to implement a completely different encodings.

<<rec_html,Support for HTML is recommended>>. HTML is the core language of the World Wide Web. An API that supports HTML will support browsing the spatial resources with a web browser and will also enable search engines to crawl and index those resources.

CAUTION: The search engine point is not valid. HTML describes syntax, not semantics (remember why we introduced XML and RDF?). See link:https://github.com/opengeospatial/ogc_api_coverages/issues/13[Issue 13].

<<rec_geojson,Support for GeoJSON is recommended>>. GeoJSON is a commonly used format that is simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using a JSON-based format, it is recommended for use in support data. as long as the data can be represented in GeoJSON for the intended use. Explicitly out-of-scope for GeoJSON are coverages. Further, GeoJSON currently does not consider geometries that have to be represented in a coordinate reference system that is not based on WGS 84 longitude/latitude (e.g. an authoritative national reference system). Consequently, GeoJSON is not recommended for coverages; rather, for JSON the CIS 1.1 JSON encoding is recommended which can represent coverages in an informationally complete way.

<<rec_cisjson,Support for CIS 1.1 JSON is recommended>>

Among the shortcomings of GeoJSON, which have been debated widely, is the substantially restricted support for multi-dimensional coordinates and coordinate reference systems. For exampele, European ETRS89 is not supported.

The recommendations for using HTML and GeoJSON reflect the importance of HTML and the current popularity of JSON-based data formats. As the practices in the Web community evolve, the recommendations will likely be updated in future versions of this standard to provide guidance on using other encodings.

This part of the OAPI standard does not provide any guidance on other encodings. The supported encodings, or more precisely the media types of the supported encodings, can be determined from the API definition. The desired encoding is selected using HTTP content negotiation.

For example, if the server supports link:https://tools.ietf.org/html/rfc8142[GeoJSON Text Sequences] an encoding that is based on JSON text sequences, and GeoJSON, and supports streaming by making the data incrementally parseable, could use the media type `application/geo+json-seq` in the header of a corresponding request to the server.

In addition, HTTP supports compression. Therefore the standard HTTP compression mechanisms can be used to reduce the size of messages between the server and the client.

=== Examples

[NOTE]
========
Update the following content once a coverage example has been agreed on.
========
[NOTE]
========
The following set of examples is proposed, taken from link:http://docs.opengeospatial.org/is/09-146r6/09-146r6.html[OGC CIS] standard's suite of link:http://schemas.opengis.net/cis/1.1/gml[XML], link:http://schemas.opengis.net/cis/1.1/json[JSON], and link:http://schemas.opengis.net/cis/1.1/rdf[RDF] examples.
========

This document uses a simple example throughout the document: a link:http://schemas.opengis.net/cis/1.1/json/examples/10_2D_regular.json[2D single-band orthoimage coverage]. Further examples provided in link:http://schemas.opengis.net/cis/1.1/gml[XML], link:http://schemas.opengis.net/cis/1.1/json[JSON], and link:http://schemas.opengis.net/cis/1.1/rdf[RDF] include:

* link:http://schemas.opengis.net/cis/1.1/json/examples/00_metadata.json[metadata]
* link:http://schemas.opengis.net/cis/1.1/json/examples/05_2D_index.json[2D_index]
* link:http://schemas.opengis.net/cis/1.1/json/examples/10_2D_regular.json[2D regular]
* link:http://schemas.opengis.net/cis/1.1/json/examples/11_2D_regular_fileref.json[2D regular fileref]
* link:http://schemas.opengis.net/cis/1.1/json/examples/12_2D_regular_fileref_multiband.json[2D regular fileref multiband]
* link:http://schemas.opengis.net/cis/1.1/json/examples/15_with-envelope.json[with-envelope]
* link:http://schemas.opengis.net/cis/1.1/json/examples/20_3D_height.json[3D height]
* link:http://schemas.opengis.net/cis/1.1/json/examples/25_3D_time.json[3D time]
* link:http://schemas.opengis.net/cis/1.1/json/examples/30_4D_height+time.json[4D height+time]
* link:http://schemas.opengis.net/cis/1.1/json/examples/40_1D_regular.json[1D regular]
* link:http://schemas.opengis.net/cis/1.1/json/examples/45_2D_distorted.json[2D distorted]
* link:http://schemas.opengis.net/cis/1.1/json/examples/46_irregular+distorted.json[irregular+distorted]
* link:http://schemas.opengis.net/cis/1.1/json/examples/50_3D_partitioned-1.json[3D partitioned]
* link:http://schemas.opengis.net/cis/1.1/json/examples/55_1D_timeseries-partitioned.json[1D timeseries partitioned]
* link:http://schemas.opengis.net/cis/1.1/json/examples/60_3D_timeseries-multipart.json[3D timeseries multipart]
* link:http://schemas.opengis.net/cis/1.1/json/examples/65_1D_timeseries-interleaved.json[1D timeseries interleaved]
* link:http://schemas.opengis.net/cis/1.1/json/examples/70_2D_interpolation.json[2D interpolation]
* link:http://schemas.opengis.net/cis/1.1/json/examples/80_sensormodel.json[sensormodel]
* link:http://schemas.opengis.net/cis/1.1/json/examples/90_point-cloud.json[point cloud]
  




=== Overview

This clause specifies four pre-defined requirements classes for encodings available for use by an OGC API implementation. These encodings are commonly used encodings for spatial data on the web, albeit not always currently for coverages:

* <<rc_cisjson,OGC CIS JSON>> (OGC CIS 1.1 standard, includes binary encodings)
* <<rc_html,HTML>> (currently undefined)
* <<rc_geojson,GeoJSON>> (GeoJSON currently does not support coverages, and "The GeoJSON format differs from other GIS standards in that it was written and is maintained not by a formal standards organization, but by an Internet working group of developers." link:https://everything.explained.today/GeoJSON/[source])

None of these encodings are mandatory and an implementation of the <<rc_core,Core>> requirements class may also implement none of them but implement another encoding instead, such as GeoTIFF or NetCDF. In a WCS secnario, therefore, the same coverage can simultaneously be served to different application domains, such as in XML for EU INSPIRE based applications, JSON for direct browser consumption, RDF for ontological domains, GeoTIFF for GISs, and NetCDF for multi-dimensional scientific analysis. All these encodings are specified in OGC CIS and companion standards, see link:http://external.opengeospatial.org/twiki_public/CoveragesDWG/CoveragesBigPicture[this graphic]. 

<<overview,Clause 6 (Overview)>> includes a discussion about recommended encodings.

=== Requirements class "CIS JSON"
This requirements class relies on the OGC Coverage Implementation Schema and its JSON encoding as defind in the link:http://schemas.opengis.net/cis/1.1/json/coverage-schema.json[JSON schema]. It is "informationally complete": all coverage constituents defined in the standard can be represented, there is no loss of information in this encoding (as opposed to, e.g., image formats which typically cannot carry all coverage metadata). Below examples are given, all from the link:http://schemas.opengis.net/cis/1.1/json/examples/[official OGC schema repository]. Note, however, that a coverage does not need to be delivered in JSON in its entirety; rather, multipart encoding, also defined in OGC CIS, allows having a "canonical" header in XML, JSON, RDF, or similar while components can be factored out and represented in some (more efficient) binary format, such ss TIFF and NetCDF. Any suitable container format (such as zip, miltipart/mime, SAFE, etc.) can "bundle" these components into one coverage file ready for shipping.

.A CIS JSON Coverage Object response (link:http://schemas.opengis.net/cis/1.1/json/examples/10_2D_regular.json[source])
=================

[source,JSON]
----
{
        "@context": ["http://localhost/json-ld/coverage-context.json", {"examples": "http://www.opengis.net/cis/1.1/examples/"}],
        "type": "CoverageByDomainAndRangeType",
        "id": "examples:CIS_10_2D",
        "domainSet":{
                "@context": "http://localhost/json-ld/domainset-context.json",
                "type": "DomainSetType",
                "id": "examples:CIS_DS_10_2D",
                "generalGrid":{
                        "type": "GeneralGridCoverageType",
                        "id": "examples:CIS_DS_GG_10_2D",
                        "srsName": "http://www.opengis.net/def/crs/EPSG/0/4326",
                        "axisLabels": ["Lat", "Long"],
                        "axis": [{
                                "type": "RegularAxisType",
                                "id": "examples:CIS_DS_GG_LAT_10_2D",
                                "axisLabel": "Lat",
                                "lowerBound": -80,
                                "upperBound": -70,
                                "uomLabel": "deg",
                                "resolution": 5
                        },{
                                "type": "RegularAxisType",
                                "id": "examples:CIS_DS_GG_LONG_10_2D",
                                "axisLabel": "Long",
                                "lowerBound": 0,
                                "upperBound": 10,
                                "uomLabel": "deg",
                                "resolution": 5
                        }],
                        "gridLimits": {
                                "type": "GridLimitsType",
                                "id": "examples:CIS_DS_GG_GL_10_2D",
                                "srsName": "http://www.opengis.net/def/crs/OGC/0/Index2D",
                                "axisLabels": ["i", "j"],
                                "axis": [{
                                        "type": "IndexAxisType",
                                        "id": "examples:CIS_DS_GG_GL_I_10_2D",
                                        "axisLabel": "i",
                                        "lowerBound": 0,
                                        "upperBound": 2
                                },{
                                        "type": "IndexAxisType",
                                        "id": "examples:CIS_DS_GG_GL_J_10_2D",
                                        "axisLabel": "j",
                                        "lowerBound": 0,
                                        "upperBound": 2
                                }]
                        }
                }
        },
        "rangeSet": {
                "@context": "http://localhost/json-ld/rangeset-context.json",
                "type": "RangeSetType",
                "id": "examples:CIS_RS_10_2D",
                "dataBlock": {
                        "id": "examples:CIS_RS_DB_10_2D",
                        "type": "VDataBlockType",
                        "values": [1,2,3,4,5,6,7,8,9]
                }
        },
        "rangeType": {
                "@context": "http://localhost/json-ld/rangetype-context.json",
                "type": "DataRecordType",
                "id": "examples:CIS_RT_10_2D",
                "field":[{
                        "type": "QuantityType",
                        "id": "examples:CIS_RT_F_10_2D",
                        "definition": "ogcType:unsignedInt",
                        "uom": {
                                "type": "UnitReference",
                                "id": "examples:CIS_RT_F_UOM_10_2D",
                                "code": "10^0"
                        }
                }]
        }
}
----
=================

.A CIS JSON Coverage Object response with file reference (link:http://schemas.opengis.net/cis/1.1/json/examples/10_2D_regular.json[source])
=================
In the example below, the range set part of the coverage above has been replaced by a file reference (which should be accessible by the coverage recipient, so likely a URL in practice). All other parts (denoted by "...") remain as above.

[source,JSON]
----
...
        "rangeSet": {
                "@context": "http://localhost/json-ld/rangeset-context.json",
                "type": "RangeSetRefType",
                "id": "examples:CIS_RS_11_2D",
                "fileReference": ["regular_fileref.tiff"]
        },
...
----
=================

=== Requirement Class "HTML"

Geographic information that is only accessible in formats like GeoJSON or GML has two issues:

* The data is not discoverable using the most common mechanism for discovering information, that is the search engines of the Web;
* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, it should be done in a way that enables users and search engines to access all data.

This is discussed in detail in
link:https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines[Best Practice 2: Make your spatial data indexable by search engines]
<<SDWBP>>. This standard therefore <<rec_html,recommends supporting HTML as an encoding>>.

include::requirements/requirements_class_html.adoc[]

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::requirements/html/REC_schema-org.adoc[]

=== Requirement Class "GeoJSON"

GeoJSON is a commonly used format for geographic features that is simple to understand and well supported by tools and software libraries; for coverages no support is currently available. 

Instead, JSON coverages can be encoded as defined in the link:https://github.com/opengeospatial/ogc_api_coverages/blob/master/CIS%2BWCS-standards/09-146r6_Coverage_Implementation_Schema_CIS_1.1.pdf[OGC Coverage Implementation Schema] standard which defines a JSON encoding that retains all coverage information; see the previous section for details.

include::requirements/requirements_class_geojson.adoc[]

include::requirements/geojson/REQ_definition.adoc[]

include::requirements/geojson/REQ_content.adoc[]

=== Requirement Class "Geography Markup Language (GML), Simple Features Profile"

[NOTE]
========
The XML encoding of coverages is not defined in GML Simple Features; rather, a GML-oriented coverage representation is defined in OGC CIS, see the link:http://schemas.opengis.net/cis/1.1/gml/[official OGC schema] containing link:http://schemas.opengis.net/cis/1.1/gml/examples-1.1/[many examples].
========
