=== Requirement Class Subset
Without any subsetting parameter the whole coverage extent is the target resource addressed. If a subsetting operation is provided then the coverage subset indicated is the target resource addressed.

Coverage subsetting is indicated through the SUBSET parameter name. The value following the "=" symbol is built as follows:

    SubsetSpec:            SUBSET = axisName (intervalOrPoint)
    axisName:              {NCName}
    intervalOrPoint:       interval | point
    interval:              low : high
    low:                   point | *
    high:                  point | *
    point:                 {number} | "{text}"
    
    Where:
    " = double quote = ASCII code 0x42,
    {NCName} is an XML-style identifier not containing ":" (colon) characters, 
    {number} is an integer or floating-point number, and
    {text} is some general ASCII text (such as a time and date notation in ISO 8601). 
    
include::requirements/requirements_class_subset.adoc[]

==== Subsetting Examples

include::examples/examples_subsetting.adoc[]

=== Coverage Query Parameters

In this clause, the query component of https://github.com/opengeospatial/ogc_api_coverages[OGC API - Coverages] access is established.

Subsetting parameters may be mixed in a query part, in no particular order.



=== Coverage Subsetting

The third part is about query parameters:

*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage?SUBSET=Lat(40,50)&SUBSET=Long(10,20)[http://acme.com/oapi/collections/{collectionid}/coverage?SUBSET=Lat((40_50)&SUBSET=Long(10_20)]  -- returns a cutout from the coverage identified with extent between corner coordinates (40,10) and (50,20) (note: replace the _ in the URL by a comma character - an adoc issue)
*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage/rangeset?SUBSET=Lat(40,50)&SUBSET=Long(10,20)[http://acme.com/oapi/collections/{collectionid}/coverage/rangeset?SUBSET=Lat(40_50)&SUBSET=Long(10_20)]  -- returns the range set of a coverage cutout between (40,10) and (50,20), in the coverage’s Native Format; no domain set, range type, and metadata will be returned (note: replace the _ in the URL by a comma character - an adoc issue)
*   http://acme.com/oapi/collections/%7Bcollectionid%7D/coverage?SUBSET=time(%222019-03-27%22)[http://acme.com/oapi/collections/{collectionid}/coverage?SUBSET=time("2019-03-27")]  -- returns a coverage slice at the timestamp given (in case the coverage is Lat/Long/time the result will be a 2D image)
