[[rc-domainset-subset-section]]
== Requirements Class DomainSet Subset

The DomainSet Subset Requirements Class defines the use of parameters for sub-setting the domainset of the coverage.

include::requirements/requirements_class_domainset_subset.adoc[]

NOTE: The following is an alternative definition for this requiremenents class.

The subset parameter is defined in the following Requirement Module:

include::../api_modules/subset/requirements_module_subset.adoc[]

The `DomainSet Subset` Requirements Class defines the application of the `subset` parameter against the DomainSet component of a Coverage resource using the HTTP GET operation. The effect is to generate a subset of the domain set of the coverage. That subset is then returned to the client in the HTTP response.

NOTE: Path = /collections/{collection_id}/coverage/domainset

NOTE: End insert

The subset parameter is defined in the following Requirement:

include::requirements/domainset-subset/REQ_cov-subset-definition.adoc[]

The results of using a subset parameter are defined by the following Requirement:

include::requirements/domainset-subset/REQ_cov-subset-success.adoc[]

=== DomainSet Subsetting Examples

include::examples/examples_domainset_subsetting.adoc[]
