== Terms and Definitions
This document uses the terms defined in Sub-clause 5 of https://github.com/opengeospatial/oapi_common/blob/master/19-072.pdf[OGC API - Common - Part 1: Core] (OGC 19-072), which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== Coverage
function which returns values from its range for any direct position within its domain (as defined in OGC Abstract Topic 6)

=== Regular grid
grid whose grid lines have a constant distance along each grid axis

=== Irregular grid
Grid whose grid lines have individual distances along each grid axis

=== Displaced grid
grid whose direct positions are topologically aligned to a grid, but whose geometric positions can vary arbitrarily

=== Mesh
coverage consisting of a collection of curves, surfaces, or solids, respectively

=== Partition [of a coverage]
separately stored coverage acting, by being referenced in the coverage on hand, as one of its components

=== Scene
component of a coverage with its domain being a subset of the overall coverage for a coverage consisting of multiple scenes, similar to a partition

(in the context of Earth Observation imagery data products and the _Scenes_ requirements class defined in this standard)

Unlike Coverage Implementation Schema (CIS) _coverages by partitioning_, scenes are an optional capability of the API with corresponding individual resource paths rather than a potential aspect of a coverage resource.
A client can either retrieve a coverage for the overall collection or for an individual scene, but will never receive a special "partitioned coverage" response necessitating special handling considerations.

=== Sensor model
mathematical model for estimating geolocations from recorded sensor data such as digital imagery

=== Transformation grid
grid whose direct positions are given by some transformation algorithm not further specified in this standard
