[[rc-range-subset-section]]
== Requirements Class Range Subset

The Range Subset Requirements Class defines the `properties` parameter for selecting a subset of the DataRecord fields (defined in the Range Type, e.g. individual imagery bands) to retrieve from Range Sets.

The `Range Subset` Requirements Class defines the application of the `properties` parameter against the RangeSet component of a Coverage resource using the HTTP GET operation.
The effect is to generate a subset of the range set of the coverage. That subset is then returned to the client in the HTTP response.

This query parameter affects both the `/collections/{collection_id}/coverage` and `/collections/{collection_id}/coverage/rangeset` resource paths.

Range subsetting parameters may be mixed with other parameters, in no particular order, in the query part of a URL.

include::requirements/requirements_class_coverage_rangesubset.adoc[]

The `properties` parameter is defined in the following Requirement:

include::requirements/coverage-rangesubset/REQ_cov-rangesubset-definition.adoc[]

The results of using a range-subset parameter are defined by the following Requirement:

include::requirements/coverage-rangesubset/REQ_cov-rangesubset-success.adoc[]

=== Range Subsetting Examples

include::examples/examples_rangesubsetting.adoc[]
