== Conventions
This sections provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

=== Identifiers
The normative provisions in this standard are denoted by the URI

http://www.opengis.net/spec/ogcapi-coverages/1.0

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== UML Notation

Diagrams using the Unified Modeling Language (UML) adhere to the following conventions:

* UML elements having a package name of “GML” are those defined in the UML model of GML 3.2.1
* UML elements having a package name of “SWE Common” are those defined in the UML model of SWE Common 2.0
* UML elements not qualified with a package name, or with “CIS”, are those defined in this standard.

Further, in any class where an attribute name or association role name is identical to a name in some superclass the local definition overrides the superclass definition.

=== Namespace Prefix Conventions
UML diagrams and XML code fragments adhere to the namespace conventions shown in Table 2. The namespace prefixes used in this document are not normative and are merely chosen for convenience. The namespaces to which the prefixes correspond are normative, however. 

Whenever a data item from a CIS-external namespace is referenced this constitutes a normative dependency on the data structure imported together with all requirements defined in the namespace referenced.

[#namespace-mapping-conventions,reftext='{table-caption} {counter:table-num}']
.Namespace mapping conventions
[width="90%",cols="^2,^2,6,6",options="header"]
|====
|*UML prefix* |*GML prefix* ^|*Namespace URL* ^|*Description*
|CIS |cis |http://www.opengis.net/cis/1.1 |Coverage Implementation Schema 1.1
|CIS10 |cis10 |http://www.opengis.net/gmlcov/1.0 |Coverage Implementation Schema 1.0
|GML |gml |http://www.opengis.net/gml/3.2 |GML 3.2.1
|GML33 |gml33 |http://www.opengis.net/gml/3.3 |GML 3.3
|SWE Common |swe |http://www.opengis.net/swe/2.0 |SWE Common 2.0
|SML |sml |http://www.opengis.net/sensorml/2.0 |SensorML 2.0
|====
