[[rc_scaling_spatial]]
== Requirements Class "Spatial Scaling"

=== Overview

The "Spatial Scaling" Requirements Class defines the `resolution`, `width` and `height` query parameters for retrieving a coverage at a specific spatial resolution.
The spatial dimensions are named `Lat` and `Lon` for a geographic output CRS, and `N` and `E` for a projected CRS.
For a three-dimensional output CRS, resolution can also be specified for a third spatial dimension `h`, which corresponds to the height above the ellipsoid for a geographic CRS such as CRS84h or EPSG:4979,
and to the third dimension often called _z_ in a Cartesian 3D CRS such as EPSG:4978.
Common aliases for these dimensions are also recommended to be supported by servers, but clients should only use these required spatial dimension names to ensure interoperability.

IMPORTANT: A client requesting a coverage at a specific spatial resolution needs to be aware that this will likely result in resampling / interpolation of the data, and therefore does not necessarily
imply that the resulting data will be suited for purpose, particularly if the native resolution of the source data is coarser than the requested resolution.
Although the servers are encouraged to perform the best possible interpolation (see <<scaling-spatial-interpolation-recommendation>>),
the client has no control over how the quality of the interpolation that the server will decide to perform when upsampling or downsampling data.

include::requirements/requirements_class_coverage_scaling_spatial.adoc[]

[[rc_scaling_temporal]]
== Requirements Class "Temporal Scaling"

=== Overview

The "Temporal Scaling" Requirements Class defines the `resolution` query parameter and a dimension named `time` for retrieving a coverage at a specific temporal resolution using ISO 8601 period notation.

IMPORTANT: A client requesting a coverage at a specific temporal resolution needs to be aware that this will likely result in resampling / interpolation of the data, and therefore does not necessarily
imply that the resulting data will be suited for purpose, particularly if the native resolution of the source data is coarser than the requested resolution.
Although the servers are encouraged to perform the best possible interpolation (see <<scaling-temporal-interpolation-recommendation>>),
the client has no control over how the quality of the interpolation that the server will decide to perform when upsampling or downsampling data.

include::requirements/requirements_class_coverage_scaling_temporal.adoc[]

[[rc_scaling_general]]
== Requirements Class "General Scaling"

=== Overview

The "General Scaling" Requirements Class defines the `resolution` query parameter for additional dimensions beyond 3D space and the primary temporal dimension
for retrieving a coverage at a specific resolution for those dimensions.
These additional dimensions are named as described as additional property keys besides `"spatial"` and `"temporal"` in the `"extent"` section of the collection description.
Additional temporal dimensions support the ISO 8601 period notation if its temporal reference system (`trs`)
is specified as `https://www.opengis.net/def/crs/OGC/0/GregorianDateTime`.

IMPORTANT: A client requesting a coverage at a specific resolution needs to be aware that this will likely result in resampling / interpolation of the data, and therefore does not necessarily
imply that the resulting data will be suited for purpose, particularly if the native resolution of the source data is coarser than the requested resolution.
Although the servers are encouraged to perform the best possible interpolation (see <<scaling-general-interpolation-recommendation>>),
the client has no control over how the quality of the interpolation that the server will decide to perform when upsampling or downsampling data.

include::requirements/requirements_class_coverage_scaling_general.adoc[]
