=== Requirements Class Subset

The `core` Requirements Class provides parameters for filtering the re

In this clause, the query component of https://github.com/opengeospatial/ogc_api_coverages[OGC API - Coverages] access is established.

Subsetting parameters may be mixed in a query part, in no particular order.

Without any subsetting parameter the whole coverage extent is the target resource addressed. If a subsetting operation is provided then the coverage subset indicated is the target resource addressed.

Coverage subsetting is indicated through the SUBSET parameter name. The value following the "=" symbol is built as follows:

    SubsetSpec:            SUBSET = axisName (intervalOrPoint)
    axisName:              {NCName}
    intervalOrPoint:       interval | point
    interval:              low : high
    low:                   point | *
    high:                  point | *
    point:                 {number} | "{text}"
    
    Where:
    " = double quote = ASCII code 0x42,
    {NCName} is an XML-style identifier not containing ":" (colon) characters, 
    {number} is an integer or floating-point number, and
    {text} is some general ASCII text (such as a time and date notation in ISO 8601). 

    
include::requirements/requirements_class_subset.adoc[]

==== Subsetting Examples

include::examples/examples_subsetting.adoc[]

=== Coverage Query Parameters

