== Requirements Class "GeoData-Coverage"

[[geodata-coverage-overview]]
=== Overview

include::requirements/requirements_class_geodata_coverage.adoc[]

The `GeoData-Coverage` Requirements Class defines the requirements for locating, understanding, and accessing a geospatial data resource as a coverage. The `GeoData-Coverage` Requirements Class is presented in five sections:

. <<api-platform-section,API Platform>>: a set of common capabilities
. <<collection-access-section,Collection Access>>: operations for accessing collections of `Coverages`
. <<coverage-access-section,Coverage Access>>: operations for accessing `Coverage` resources
. <<parameters-section,Parameters>>: parameters for use in the API-Coverage operations.
. <<general-section,General>>: general principles for use with this standard.

[[geodata-coverage-dependencies-section]]
=== Dependencies

The OGC API-Coverages standard is an extension of the OGC API - Common - Part 1: Core and Part 2: Geospatial Data Standards. Therefore, an implementation of API-Coverages must first satisfy the appropriate Requirements Classes from API-Common.

include::requirements/common-core/REQ_api-common.adoc[]

[[api-platform-section]]
=== Platform

API-Common defines a set of common capabilities which are applicable to any OGC Web API. Those capabilities provide the platform upon which resource-specific APIs can be built. This section describes those capabilities and any modifications needed to better support Coverage resources.

[[landing-page]]
==== API landing page

The purpose of the landing page is to provide clients with a starting point for using the API. It provides the basic information needed to understand the purpose, structure, and capabilities of the API. The landing page also serves as the starting point for navigation. Any resource exposed through an API can be accessed using a path or link starting from the landing page.

The resources exposed by API-Common Core include:

*   A description of the API,
*   A declaration of conformance classes,
*   A list of coverages available.

Those resources are sufficient for this standard.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core
|====

===== Operation

The `Landing Page` operation is defined in the `Core` conformance class of API-Common. No modifications are needed to support `Coverage` resources. The `Core` conformance class specifies only one way of performing this operation:

. Issue a `GET` request on the `{datasetAPI}/` path

Support for `GET` on the `{datasetAPI}/` path is required by API-Common.

===== Response

A successful response to the `Landing Page` operation is defined in API-Common. The schema for this resource is provided in <<landingPage-schema>>.

[#landingPage-schema,reftext='Landing Page Response Schema']
.Landing Page Response Schema
[source,yaml]
----
include::openapi/schemas/common-core/landingPage.yaml[]
----

The following JSON fragment is an example of a response to an OGC API-Coverages Landing Page operation.

[#landingPage-example,reftext=`Landing Page Example`]
.Landing Page Example
[source,json]
----
include::examples/JSON/landingPage_example.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[api-definition]]
==== API definition

Every API is required to provide a definition document that describes the capabilities of that API. This definition document can be used by developers to understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core
|====

===== Operation

This operation is defined in the `Core` conformance class of API-Common. No modifications are needed to support `Coverage` resources. The `Core` conformance class describes two ways of performing this operation:

. Issue a `GET` request on the `{datasetAPI}/api` path
. Follow the `service-desc` or `service-doc` link on the landing page

Only the link is required by API-Common.

===== Response

A successful response to the API Definition request is a resource which documents the design of the API. API-Common leaves the selection of format for the API Definition response to the API implementor. However, the options are limited to those which have been defined in the API-Common standard. At this time OpenAPI 3.0 is the only option provided.

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[conformance-classes]]
==== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the conformance classes it claims to have implemented.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core
|====

===== Operation

This operation is defined in the `Core` conformance class of API-Common. No modifications are needed to support `Coverage` resources. The `Core` conformance class describes two ways of performing this operation:

. Issue a `GET` request on the `{datasetAPI}/conformance` path
. Follow the `conformance` link on the landing page

Both techniques are required by API-Common.

===== Response

A successful response to the Conformance operation is a list of URLs. Each URL identifies an OGC Conformance Class for which this API claims conformance. The schema for this resource is defined in API-Common and provided for reference in <<conformance-schema>>.

include::requirements/geodata-coverage/REQ_geodata_coverage-conformance.adoc[]

[#conformance-schema,reftext='Conformance Response Schema']
.Conformance Response Schema
[source,yaml]
----
include::openapi/schemas/common-core/confClasses.yaml[]
----

The following JSON fragment is an example of a response to an OGC API-Coverages conformance operation.

[#conformance-example,reftext=`Conformance Information Example`]
.Conformance Information Example
[source,json]
----
include::examples/JSON/conformance_example.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[collection-access-section]]
=== Collection Access

API-Common starts with the assumption that spatial resources are organized into collections. An API will expose one or more collections. The API-Common Collections Conformance Class defines how to organize and provide access to a collection of collections.

API-Coverages observes that a coverage is a collection of measured values. Therefore, a coverage is a collection.

This standard extends the API-Common `Collections` conformance class to support collections of coverages, then extends that class to support `Coverage` unique capabilities.

[[collections]]
==== Collections

The `Collections` operation returns a set of metadata which describes the collections available from this API. Each collection on a Coverages API will be a coverage. The coverages returned in the response can be limited using the <<bbox-section,Bounding Box>>, <<datatime-section,Date-Time>>, and <<limit-section,Limit>> parameters. 

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections
|====

===== Operation

This operation is defined in the `Collections` conformance class of API-Common. No modifications are needed to support `Coverage` resources. The `Collections` conformance class describes two ways of performing this operation:

. Issue a `GET` request on `{datasetAPI}/collections` path
. Follow the `data` link on the landing page

Support for both the `{datasetAPI}/collections` path and the `data` link is required by API-Common.

===== Response

A successful response to the `Collections Operation` is a document which includes [underline]#summary# metadata for each collection accessible though the API. To keep the size of this response manageable, the summary metadata should be limited to just those elements which are essential for clients and those which are needed to support the filtering parameters. 

include::recommendations/geodata-coverage/REC_coverageinfo.adoc[]

[#collections-schema,reftext='Collections Response Schema']
.Collections Response Schema
[source,yaml]
----
include::openapi/schemas/common-geodata/collections.yaml[]
----

The following JSON fragment is an example of a response to an OGC API-Coverages Collections operation.

[#conllections-example,reftext=`Collections Example`]
.Collections Example
[source,json]
----
include::examples/JSON/collections_example.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[collectionInfo]]
==== Collection Information

Collection Information is the set of metadata which describes a single collection, or in the the case of API-Coverages, a single Coverage. An abbreviated copy of this information is returned for each Coverage in the `/collections` response.

.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections
|====

===== Operation

This operation is defined in the `Collections` conformance class of API-Common. No modifications are required to support `Coverage` resources. However, on a coverages API the the collections are also coverages. So in this standard the term `collectionId` is used instead of `collectionid`. The two terms are equivalent.

The `Collections` conformance class describes two ways of performing this operation:

. Issue a `GET` request on the `{datasetAPI}/collections/{collectionId}` path
. Follow the `ogc:common:collection` link on the ?????

NOTE: What is the origin of the "ogc:common:collection" link?

The {collectionId} parameter is the unique identifier for a single coverage on the API. The list of valid values for {collectionId} is provided in the /collections response.

Support for the `/collections/{collectionId}` path is recommended by API-Common.
Support for the ogc:common:collection link is required.

===== Response

A successful response to the Collection Operation is a set of metadata which describes the collection identified by the {collectionId} parameter. This metadata is an extension to the set defined by API-Common. The additional elements are specific to Coverage resources.

[#collectionInfo-schema,reftext='Collection Information Response Schema']
.Collection Information Response Schema
[source,yaml]
----
include::openapi/schemas/coverages-core/coverageInfo.yaml[]
----

The following JSON fragment is an example of a response to an OGC API-Coverages Collection Information operation.

[#collection-info-example,reftext=`Collection Information Example`]
.Collection Information Resource Example
[source,json]
----
include::examples/JSON/collection_info_example.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[coverage-access-section]]
=== Coverage Access

In this clause, API-Common is extended to support `Coverage` resources.

A `Coverage` is a collection of measured values. The structure of that collection is defined by the <<CIS_1_1,CIS standard>>. CIS contains four principle components:

* A `DomainSet` component describing the coverage’s domain (the set of “direct positions”, i.e., the locations for which values are stored in the coverage)
* A `RangeType` component which describes the coverage's `RangeSet` data structure (in the case of images usually called the “pixel data type”).
* A `RangeSet` component containing the stored values (often referred to as “pixels”, “voxels”) of the coverage.
* A `Metadata` component which represents an extensible slot for metadata. The intended use is to hold any kind of application-specific metadata structures.

A coverage containing the `DomainSet`, `RangeType`, `RangeSet`, and `Metadata`  components is accessible at

* The relative path `/coverage`
* The link relation `ogc:coverage:coverage`

The `DomainSet` and `RangeType` are accessible from resources linked by links within the `/collections/{collectionId}` resource,
using the relation types `http://www.opengis.net/def/rel/ogc/1.0/coverage-domainset` and
`http://www.opengis.net/def/rel/ogc/1.0/coverage-rangetype`, respectively.
Those links may either point to separate resource, in which case the recommended paths are `/collections/{collectionId}/coverage/domainset` and
`/collections/{collectionId}/coverage/rangetype`, or point to the coverage description resource itself the domain set and/or range type are
embedded. In the latter case those links will point specifically to properties using `#`, e.g.,
`#domainset` and `#rangetype`.

The `RangeSet` may be available as its own resource as well, if supported by the selected representation (format).

If `Metadata` is available, it will also be be available as its own resource.

The paths discussed in this section are all branches off of the `/collections/{collectionId}` root.

[[coverage-clause]]
==== Coverage

The `Coverage` operation returns all the components of the coverage (rangeset, domain set, range type, metadata). It is comparable to a WCS GetCoverage operation.

===== Operation

The `Coverage` operation is defined by the following requirement.

include::requirements/geodata-coverage/REQ_coverage-op.adoc[]

===== Response

A successful response to the `Coverage` operation shall meet the following requirement.

include::requirements/geodata-coverage/REQ_coverage-success.adoc[]

[#coverage--schema,reftext='Coverage Response Schema']
.Coverage Response Schema
[source,yaml]
----
include::openapi/schemas/cis/coverage-schema.yaml[]
----

The following JSON fragment is an example of a response to a Coverage request.

[#coverage-all-example,reftext=`Coverage Example`]
.Coverage Example
[source,json]
----
include::examples/JSON/coverage_example.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[parameters-section]]
=== Parameters
The API-Coverages standard inherits basic query and subsetting parameters from API-Common. This section provides a short description of each parameter and identifies the relevant requirements.

All of the permissions and recommendations in API-Common regarding the these parameters also apply to API-Coverages implementations.


[[coverage-domainset-clause]]
==== Coverage Domain Set

The `Coverage Domain Set` operation returns the coverage’s domain set definition

===== Operation

The `Coverage Domain Set` operation is defined by the following requirement.

include::requirements/geodata-coverage/REQ_domainset-op.adoc[]

===== Response

A successful response to the `Coverage Domain Set` operation shall meet the following requirement.

include::requirements/geodata-coverage/REQ_domainset-success.adoc[]

[#coverage-domainset-schema,reftext='Coverage Domain Set Response Schema']
.Coverage Domain Set Response Schema
[source,yaml]
----
include::openapi/schemas/cis/domainSet.yaml[]
----

The following JSON fragment is an example of a response to a Coverage DomainSet request.

[#coverage-domainset-example,reftext=`Coverage DomainSet Example`]
.Coverage DomainSet Example
[source,json]
----
include::examples/JSON/coverage_domainset_example.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[coverage-rangetype-clause]]
==== Coverage Range Type

The `Coverage Range Type` operation returns the coverage’s range type information (i.e., a description of the data semantics)

===== Operation

The `Coverage Range Type` operation is defined by the following requirement.

include::requirements/geodata-coverage/REQ_rangetype-op.adoc[]

===== Response

A successful response to the `Coverage Range Type` operation shall meet the following requirement.

include::requirements/geodata-coverage/REQ_rangetype-success.adoc[]

[#coverage-rangetype-schema,reftext='Coverage Range Type Response Schema']
.Coverage Range Type Response Schema
[source,yaml]
----
include::openapi/schemas/cis/rangeType.yaml[]
----

The following JSON fragment is an example of a response to a Coverage RangeType request.

[#coverage-rangetype-example,reftext=`Coverage RangeType Example`]
.Coverage RangeType Example
[source,json]
----
include::examples/JSON/coverage_rangetype_example.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[coverage-rangeset-clause]]
==== Coverage Range Set

The `Coverage Range Set` operation returns the coverage’s range set, i.e., the actual values in the coverage’s Native Format (see <<media-types-section,Media Types>> for ways to retrieve inspecific formats)

===== Operation

The `Coverage Range Set` operation is defined by the following requirement.

include::requirements/geodata-coverage/REQ_rangeset-op.adoc[]

===== Response

A successful response to the `Coverage Range Set` operation shall meet the following requirement.

include::requirements/geodata-coverage/REQ_rangeset-success.adoc[]

[#coverage-rangeset-schema,reftext='Coverage Range Set Response Schema']
.Coverage Range Set Response Schema
[source,yaml]
----
include::openapi/schemas/cis/rangeSet.yaml[]
----

The following JSON fragment is an example of a response to a Coverage RangeSet request.

[#coverage-rangeset-example,reftext=`Coverage RangeSet Example`]
.Coverage RangeSet Example
[source,json]
----
include::examples/JSON/coverage_rangeset_example.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[coverage-metadata-clause]]
==== Coverage Metadata

The `Coverage Metadata` operation returns the coverage’s metadata (may be empty)

===== Operation

The `Coverage Metadata` operation is defined by the following requirement.

include::requirements/geodata-coverage/REQ_metadata-op.adoc[]

===== Response

A successful response to the `Coverage Metadata` operation shall meet the following requirement.

include::requirements/geodata-coverage/REQ_metadata-success.adoc[]

[#coverage-metadata-schema,reftext='Coverage Metadata Response Schema']
.Coverage Metadata Response Schema
[source,yaml]
----
include::openapi/schemas/cis/metadata.yaml[]
----

The following JSON fragment is an example of a response to a Coverage Metadata request.

[#coverage-metadata-example,reftext=`Coverage Metadata Example`]
.Coverage Metadata Example
[source,json]
----
include::examples/JSON/coverage_metadata_example.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

*TODO*: Move `geodata-filteredList` conformance class into its own clause, which may end up only in OGC API - Common - Part 2: Geospatial data has Coverage doesn't add anything.

*TODO*: Create new clauses for conformance classes for `coverage-bbox` and `coverage-dateTime` (or potentially make this a single one), which are additional ways to sub-select the actual coverage data being returned that a service may opt to suport.

*TODO*: Limit and Paged response may apply to both listing collections (`geodata-filteredList`) and the coverage itself.
Is it a requirement to support Limit for either of these? Is it separate conformance classes?
It would be difficult for static servers, and paging makes less sense for coverages than it does for many small features.

[[bbox-section]]
==== Parameter bbox

The Bounding Box (bbox) parameter is defined in API-Common. The following requirement governs use of that parameter in a Coverage API.

include::requirements/geodata-filteredList/REQ_bbox-parameter.adoc[]

[[datetime--section]]
==== Parameter datetime

The Date-Time (datetime) parameter is defined in API-Common. The following requirement governs use of that parameter in a Coverage API.

include::requirements/geodata-filteredList/REQ_datetime-parameter.adoc[]

[[limit-section]]
==== Parameter Limit

The Limit (limit) parameter is defined in API-Common. The following requirement governs use of that parameter in a Coverage API.

include::requirements/geodata-filteredList/REQ_limit-parameter.adoc[]

==== Combinations of Filter Parameters

Any combination of `bbox`, `datetime` and
parameters for filtering on coverage properties is allowed. Note that the requirements on these parameters imply that only coverages matching all the predicates are in the result set; i.e., the logical operator between the predicates is 'AND.'

==== Paged Response

One consequence of the Limit parameter is that the full result set is not delivered to the user. However, users frequently want to know how big the result set it and how to access the rest of it. The following requirement add information to the response to address that need.

include::requirements/geodata-coverage/REQ_paged-response.adoc[]

[[general-section]]
=== General

[[http-response]]
==== HTTP Response

Each HTTP request shall result in a response that meets the following requirement.

include::requirements/common-core/REQ_http-response.adoc[]

The YAML schema for these results is provided in <<http-response-schema>>.

[#http-response-schema,reftext='HTTP Response Schema']
.HTTP Response Schema
[source,yaml]
----
include::openapi/schemas/common-core/exception.yaml[]
----

[[http-status-codes]]
==== HTTP status codes

The *Status Codes* listed in <<status_codes>> are of particular relevance to implementors of this standard. Status codes 200, 400, and 404 are called out in API requirements. Therefore, support for these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<status_codes>> are not mandatory, but are important for the implementation of a well functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[#status_codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes[[table_2]]
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`304` |An <<web_caching,entity tag was provided in the request>> and the resource has not been changed since the previous request.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorised to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |The `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

The API Description Document describes the HTTP status codes generated by that API. This should not be an exhaustive list of all possible status codes. It is not reasonable to expect an API designer to control the use of HTTP status codes which are not generated by their software. Therefore, it is recommended that the API Description Document limit itself to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

include::recommendations/geodata-coverage/PER_additional-status-codes.adoc[]
