[[rc-coverage-subset-section]]
== Requirements Class Coverage Subset

include::requirements/requirements_class_coverage_subset.adoc[]

The `Coverage Subset` Requirements Class defines the application of query parameters against a Coverage resource using the HTTP GET operation. The effect is to generate a subset of the coverage and all of its' parts. That subset is then returned to the client in the HTTP response.

Implementors of this Requirements Class must also implement the <<rc-geodata-coverage-section,`GeoData Coverage`>> Requirements Class.

include::./requirements/coverage-subset/REQ_dependency-geodata-coverage.adoc[]

=== Parameter Requirements

The OGC API - Common - Part 2: Geospatial Data Standard identifies query parameters that have been standardized for use in OGC API standards. This Requirements Class defines how three of those parameters are used to create subsets of a hosted CIS Coverage.

* <<bbox-parameter-subset-requirements,bbox>>: Bounding Box
* <<datetime-parameter-subset-requirements,datetime>>: Date and Time
* <<subset-parameter-subset-requirements,subset>>: Subset

The behavior generated by these parameters is specific to the operation and resource upon which they are applied. The behaviors specific to the `Coverage Subset` Requirements Class are defined in the <<subset-target-resource-requirements,Target Resource Requirements>> section.

The use of these parameters should be documented in the API definition.

include::./recommendations/coverage-subset/REC_subset-parameter-documentation.adoc[]

[[bbox-parameter-subset-requirements]]
==== Parameter bbox

[[rm_bbox]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Module*
2+|http://www.opengis.net/spec/ogcapi-common-2/1.0/rm/bbox
|Target type |Web API Query Parameter
|===

The `bbox` parameter is used to select resources based on the geospatial footprint or extent.

The `bbox` parameter is defined as follows:

include::./requirements/coverage-subset/REQ_rc-bbox-definition.adoc[]

While the processing of the `bbox` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

include::./requirements/coverage-subset/REQ_rc-bbox-response.adoc[]

"Intersects" means that a coordinate that is part of the spatial geometry of the resource falls within the area specified in the parameter `bbox`. This includes the boundaries of the geometries. For curves the boundary includes the start and end position. For surfaces the boundary includes the outer and inner rings.

In case of a degenerate bounding box, the resulting geometry is used. For example, if the lower left corner is the same as the upper right corner, all resources match where the geometry intersects with this point.

This standard does not specify requirements for the parameter `bbox-crs`. Those requirements will be specified in a later version of this standard.

The bounding box for WGS 84 longitude/latitude is, in most cases, the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the box spans the anti-meridian (180th meridian) the first value (west-most box edge) is larger than the third value (east-most box edge).

.The bounding box of the New Zealand Exclusive Economic Zone
=================
The bounding box of the New Zealand Exclusive Economic Zone in WGS84 (from 160.6째E to 170째W and from 55.95째S to 25.89째S) would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89`.
=================

Note that the server will return an error if a latitude value of ``160.0`` is used.

If the vertical axis is included, the third and the sixth number are the bottom and the top of the 3-dimensional bounding box.

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/parameters/bbox.yaml[bbox.yaml].

[[datetime-parameter-subset-requirements]]
==== Parameter datetime

[[rm_datetime]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Module*
2+|http://www.opengis.net/spec/ogcapi-common-2/1.0/rm/datetime
|Target type |Web API Query Parameter
|===

The `datetime` parameter selects resources based on their temporal extent. The definition of temporal extent is specific to the resource type being filtered.

The `datetime` parameter is defined as follows:

include::./requirements/coverage-subset/REQ_rc-datetime-definition.adoc[]

While the processing of the `datetime` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

include::./requirements/coverage-subset/REQ_rc-datetime-response.adoc[]

"Intersects" means that the time (instant or period) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the resource (again, a time instant or period). For time periods this includes the start and end time.

[width="90%",cols="2,6a"]
|====
| Note | ISO 8601-2 distinguishes open start/end timestamps (double-dot) and unknown start/end timestamps (empty string). For queries, an unknown start/end has the same effect as an open start/end.
|====

.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`datetime=2018-02-12T23%3A20%3A52Z`
=================

For resources with a temporal property that is a timestamp (like `lastUpdate`), a date-time value would match all resources where the temporal property is identical.

For resources with a temporal property that is a date or a time interval, a date-time value would match all resources where the timestamp is on that day or within the time interval.

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z`
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/parameters/datetime.yaml[datetime.yaml].


[[subset-parameter-subset-requirements]]
==== Parameter subset

[cols="1,4",width="90%"]
|===
2+|*Requirements Module*
2+|http://www.opengis.net/spec/ogcapi-common-2/1.0/rm/subset
|Target type |Web API Query Parameter
|===

The `subset` parameter is used to select a subset of a geospatial resource.

The `subset` parameter is defined as follows:

include::requirements/coverage-subset/REQ_subset-definition.adoc[]

While the processing of the `subset` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

include::requirements/coverage-subset/REQ_subset-response.adoc[]


[[subset-target-resource-requirements]]
=== Target resource Requirements

The target of the parameters defined in this Requirements Class is a CIS Coverage. The purpose of these parameters is to extract a subset of the <<coverage-clause,Coverage>> resource to be returned in the response to a <<coverage-clause,/coverage>> request.

==== General Requirements

The payload shall be either a CIS document encoded per (encoding vs schema chart) or a reference to such a document.

NOTE: Is this a new coverage? Should we return the coverage ID rather than coverage itself?

NOTE: Can a service truncate the return if it is too big?  How should this truncation be done and what is returned to the user.

* Consider returing a URI instead of the content if the content is too large.
* Or - return a reduced resolution coverage with a URI to the full resolution response

NOTE: What are the error conditions and corresponding status codes?

==== Domain Subsetting

Strategy: select the domainset for this coverage then send it to domainset subsetting to process.

==== Metadata Subsetting

Strategy: Update the UAD_Extent to reflect the new domainset. Make any modifications to the CIS metadata (which is undifined) to bring it in line with the new coverage.

==== RangeType Subsetting

No changes to the range type are required.

==== RangeSet Subsetting

This should be done, but may not be possible in all cases.

==== Building the Response

What requirements (if any) are applicable to building a response from the pieces generated above?

=== Subsetting Examples

include::examples/examples_subsetting.adoc[]
