[[requirements-class-cisjson-clause]]
== Requirements Class CIS JSON

The following requirements apply to an OGC API-Coverage implementation when the following conditions apply:

. The API advertises conformance to the CIS JSON Conformance Class
. The client negotiates a JSON or CIS JSON format

The CIS JSON Requirements Class restricts requirements defined in the `GeoData-Coverage` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `GeoData-Coverage` requirements which lay within each scope.

include::requirements/requirements_class_cisjson.adoc[]

=== Common

This section covers the requirements inherited from the API-Common standard. Its scope includes responses for the following operations:

* `{datasetAPI}/`: Dataset API Landing Page
* `{datasetAPI}/api`: API Description
* `{datasetAPI}/conformance`: Conformance Classes
* `{datasetAPI}/collections`: Collections
* `{datasetAPI}/collections/{coverageid}`: Collection Information

include::requirements/cisjson/REQ_api-common.adoc[]

It is also necessary to advertise conformance with this Requirements Class.

include::requirements/cisjson/REQ_cisjson-conformance.adoc[]

=== Coverage

This section covers the <<coverage-clause,Coverage>> response for the
`{datasetAPI}/collections/{coverageid}/coverage` operation.

include::requirements/cisjson/REQ_coverage-success.adoc[]

=== Coverage Domain Set

This section covers the <<coverage-domainset-clause,Coverage Domain Set>> response for the
`{datasetAPI}/collections/{coverageid}/coverage/domainset` operation.

include::requirements/cisjson/REQ_domainset-success.adoc[]

=== Coverage Range Type

This section covers the <<coverage-rangetype-clause,Coverage Range Type>> response for the
`{datasetAPI}/collections/{coverageid}/coverage/rangetype` operation.

include::requirements/cisjson/REQ_rangetype-success.adoc[]

=== Coverage Range Set

This section covers the <<coverage-rangeset-clause,Coverage Range Set>> response for the
`{datasetAPI}/collections/{coverageid}/coverage/rangeset` operation.

include::requirements/cisjson/REQ_rangeset-success.adoc[]

=== Coverage Metadata

This section covers the <<coverage-metadata-clause,Coverage Metadata>> response for the
`{datasetAPI}/collections/{coverageid}/coverage/metadata` operation.

include::requirements/cisjson/REQ_metadata-success.adoc[]

