[[media-types-section]]
== Media Types

This standard does not mandate any particular encoding or format. However, it does provide extensions for encodings which are commonly used in OGC APIs. These extensions include:

* <<requirements-class-cisjson-clause,CIS JSON>>
* <<requirements-class-html-clause,HTML>>

Neither of these encodings are mandatory. An implementor of this standard may choose to implement neither of them, selecting different encodings instead.

In addition to the Requirements Classes, there are additional coverage formats which implementors should be aware of. These formats apply to encodings of pixel data. Since this data is typically binary, it is largely opaque to the API.

=== HTML Encoding
Support for HTML is recommended. HTML is the core language of the World Wide Web. An API that supports HTML will support browsing the spatial resources with a web browser and will also enable search engines to crawl and index those resources.

=== CIS JSON Encoding
Support for CIS JSON is recommended. JSON is a commonly used format that is simple to understand and well supported by tools and software libraries.

JSON structures documented in this standard are defined using JSON Schema. These schema are available in JSON and YAML formats from http://schemas.opengis.net/tbd[http://schemas.opengis.net/tbd]

When coverage resources (the coverage as a whole, range set, domain set, range type, meta data) advertise the `application/json` media type, it refers to the CIS JSON encoding.

This API-Coverages standard is built around the <<CIS_1_1,OGC Coverage Implementation Schema (CIS)>>.
CIS content often includes multi-dimensional coordinates and coordinate reference systems in sensor and analytic space.
These "Engineering" coordinate reference systems cannot be represented using WGS-84.

The <<CIS_JSON_Schema,OGC JSON Schema for CIS>> standard addresses that need by defining a JSON schema for the CIS standard.
This format should be used when the `application/json` media type is specified to encode all of the `{datasetAPI}/collections/{collectionId}/coverage*` resources.
A CIS JSON representation of the range type and domain set for the coverage is also required to be either embedded in properties or linked from the /collections/{collectionId} resource.

Other encodings such as CoverageJSON must use an alternate media type.

=== Binary
A coverage can also be distributed in binary form, for which a number of formats are commonly used:

* CIS RDF
* NetCDF
* GeoTIFF
* PNG
* JPEG
* JPEG-2000

OGC CIS also defines multipart encoding of the different components of a coverage.
This allows the result to have a "canonical" header while components can be factored out and represented in some (more efficient) binary format.
Any suitable container format (such as zip, multipart/mime, SAFE, etc.) can "bundle" these components into one coverage file ready for shipping.

With OGC API - Coverages, given that the description of the coverage is easily available at the /collections/{collectionId} resource, with the
range type and domain set either embedded or linked from that resource, an implementation may prefer to keep single-part binary formats encoding
all components to the best it can, as they might be more directly interoperable.

=== Media Types
A description of the media types is mandatory for any OGC standard which involves data encodings. The list of suitable media types for the API-Coverages standard in provided in <<api-coverage-media-types>>.

Coverages can be encoded in any suitable data format, including formats as GML, CIS JSON, GeoTIFF, and NetCDF. Further, coverages can be represented by a single document (stream or file) or by a hierarchically organized set of documents, each of which can be encoded individually – for example, the domain set, range type, and metadata may be encoded in easily parseable GML, CIS JSON, or RDF while the range set is encoded in some compact binary format like NetCDF or JPEG2000. Such partitioning allows for coverages tiled in space, time, or mixed, thereby enabling mosaics, time-interleaved coverages, and efficiently subsettable datacubes.

[#api-coverage-media-types,reftext='{table-caption} {counter:table-num}']
.API-Coverages media Types
[width="90%",cols="2,4"]
|====
^|*Encoding* ^|*media type*
|HTML |text/html
|JSON / CIS JSON|application/json (TODO: either OGC API will adopt a mechanism for negotiation by profile, or a more specific media type will be registered)
|CIS RDF| application/ld+json (TODO: either OGC API will adopt a mechanism for negotiation by profile, or a more specific media type will be registered)
|CoverageJSON| application/prs.coverage+json
|GeoTIFF |image/tiff; application=geotiff
|PNG |image/png
|JPEG |image/jpeg
|JPEG-2000|image/jp2
|NetCDF |application/x-netcdf
|====

NOTE: Consider adding a table showing valid media types for each CIS component.

[[media-type-defaults]]
=== Default Encodings

The media type used to encode a response to a request shall be determined through the HTTP content negotiation protocol as specified in API-Common.
If not using content negotiation, the encoding must follow the media type described in the link to the resource from the collection.


[[requirements-class-cisjson-clause]]
== Requirements Class CIS JSON

The following requirements apply to an OGC API-Coverage implementation when the following conditions apply:

. The API advertises conformance to the CIS JSON Conformance Class
. The client negotiates a JSON or CIS JSON format

The CIS JSON Requirements Class restricts requirements defined in the `GeoData-Coverage` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `GeoData-Coverage` requirements which lay within each scope.

include::requirements/requirements_class_cisjson.adoc[]

=== Common

This section covers the requirements inherited from the API-Common standard. Its scope includes responses for the following operations:

* `{datasetAPI}/`: Dataset API Landing Page
* `{datasetAPI}/api`: API Description
* `{datasetAPI}/conformance`: Conformance Classes
* `{datasetAPI}/collections`: Collections
* `{datasetAPI}/collections/{collectionId}`: Collection Information

include::requirements/cisjson/REQ_api-common.adoc[]

It is also necessary to advertise conformance with this Requirements Class.

include::requirements/cisjson/REQ_cisjson-conformance.adoc[]

=== Coverage

This section covers the <<coverage-clause,Coverage>> response for the
`{datasetAPI}/collections/{collectionId}/coverage` operation.

include::requirements/cisjson/REQ_coverage-success.adoc[]

=== Coverage Domain Set

This section covers the <<coverage-domainset-clause,Coverage Domain Set>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/domainset` operation.

include::requirements/cisjson/REQ_domainset-success.adoc[]

=== Coverage Range Type

This section covers the <<coverage-rangetype-clause,Coverage Range Type>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/rangetype` operation.

include::requirements/cisjson/REQ_rangetype-success.adoc[]

=== Coverage Range Set

This section covers the <<coverage-rangeset-clause,Coverage Range Set>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/rangeset` operation.

include::requirements/cisjson/REQ_rangeset-success.adoc[]

=== Coverage Metadata

This section covers the <<coverage-metadata-clause,Coverage Metadata>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/metadata` operation.

include::requirements/cisjson/REQ_metadata-success.adoc[]


[[requirements-class-html-clause]]
== Requirements Class HTML

The following requirements apply to an OGC API-Coverage implementation when the following conditions apply:

. The API advertises conformance to the HTML Conformance Class
. The client negotiates an HTML format

The HTML Requirements Class restricts requirements defined in the `GeoData-Coverage` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `GeoData-Coverage` requirements which lay within each scope.

include::requirements/requirements_class_html.adoc[]

=== Common

This section covers the requirements inherited from the API-Common standard. Its scope includes responses for the following operations:

* `{datasetAPI}/`: Dataset API Landing Page
* `{datasetAPI}/api`: API Description
* `{datasetAPI}/conformance`: Conformance Classes
* `{datasetAPI}/collections`: Collections
* `{datasetAPI}/collections/{collectionId}`: Collection Information

include::requirements/html/REQ_api-common.adoc[]

It is also necessary to advertise conformance with this Requirements Class.

include::requirements/html/REQ_html-conformance.adoc[]

=== Coverage

This section covers the <<coverage-clause,Coverage>> response for the
`{datasetAPI}/collections/{collectionId}/coverage` operation.

include::requirements/html/REQ_coverage-success.adoc[]

=== Coverage Domain Set

This section covers the <<coverage-domainset-clause,Coverage Domain Set>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/domainset` operation.

include::requirements/html/REQ_domainset-success.adoc[]

=== Coverage Range Type

This section covers the <<coverage-rangetype-clause,Coverage Range Type>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/rangetype` operation.

include::requirements/html/REQ_rangetype-success.adoc[]

=== Coverage Range Set

This section covers the <<coverage-rangeset-clause,Coverage Range Set>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/rangeset` operation.

include::requirements/html/REQ_rangeset-success.adoc[]

=== Coverage Metadata

This section covers the <<coverage-metadata-clause,Coverage Metadata>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/metadata` operation.

include::requirements/html/REQ_metadata-success.adoc[]

