[[rc-coverage-subset-section]]
== Requirements Class Coverage Subset

include::requirements/requirements_class_coverage_subset.adoc[]

The `Coverage Subset` Requirements Class defines the application of query parameters against a Coverage resource using the HTTP GET operation. The effect is to generate a subset of the coverage and all of its' parts. That subset is then returned to the client in the HTTP response.

Implementors of this Requirements Class must also implement the <<rc-geodata-coverage-section,`GeoData Coverage`>> Requirements Class.

include::./requirements/coverage-subset/REQ_dependency-geodata-coverage.adoc[]

=== Parameter Requirements

The OGC API - Common - Part 2: Geospatial Data Standard identifies query parameters that have been standardized for use in OGC API standards. This Requirements Class defines how three of those parameters are used to create subsets of a hosted CIS Coverage.

* <<bbox-parameter-subset-requirements,bbox>>: Bounding Box
* <<datetime-parameter-subset-requirements,datetime>>: Date and Time
* <<subset-parameter-subset-requirements,subset>>: Subset

The behavior generated by these parameters is specific to the operation and resource upon which they are applied. The behaviors specific to the `Coverage Subset` Requirements Class are defined in the <<subset-target-resource-requirements,Target Resource Requirements>> section.

The use of these parameters should be documented in the API definition.

include::./recommendations/coverage-subset/REC_subset-parameter-documentation.adoc[]

[[bbox-parameter-subset-requirements]]
==== Parameter bbox

include::../../oapi_common/api_modules/bbox/requirements_module_bbox.adoc[]

[[datetime-parameter-subset-requirements]]
==== Parameter datetime

include::../../oapi_common/api_modules/datetime/requirements_module_datetime.adoc[]

[[subset-parameter-subset-requirements]]
==== Parameter subset

include::../api_modules/subset/requirements_module_subset.adoc[]

[[subset-target-resource-requirements]]
=== Target resource Requirements

The target of the parameters defined in this Requirements Class is a CIS Coverage. The purpose of these parameters is to extract a subset of the <<coverage-clause,Coverage>> resource to be returned in the response to a <<coverage-clause,/coverage>> request.

==== General Requirements

The payload shall be either a CIS document encoded per (encoding vs schema chart) or a reference to such a document.

NOTE: Is this a new coverage? Should we return the coverage ID rather than coverage itself?

NOTE: Can a service truncate the return if it is too big?  How should this truncation be done and what is returned to the user.

* Consider returing a URI instead of the content if the content is too large.
* Or - return a reduced resolution coverage with a URI to the full resolution response

NOTE: What are the error conditions and corresponding status codes?

==== Domain Subsetting

Strategy: select the domainset for this coverage then send it to domainset subsetting to process.

==== Metadata Subsetting

Strategy: Update the UAD_Extent to reflect the new domainset. Make any modifications to the CIS metadata (which is undifined) to bring it in line with the new coverage.

==== RangeType Subsetting

No changes to the range type are required.

==== RangeSet Subsetting

This should be done, but may not be possible in all cases.

==== Building the Response

What requirements (if any) are applicable to building a response from the pieces generated above?

=== Subsetting Examples

include::examples/examples_subsetting.adoc[]
