== Conformance
Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document.
The framework, concepts, and methodology for testing, and the criteria to claim conformance, are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The one Standardization Target for this standard is Web APIs.

The _OGC API - Common_ Standard provides a common foundation for other OGC API standards.
Some conformance classes of this OGC API - Coverages Standard have a dependency on, or are designed to be easily integrated with, conformance classes defined in _OGC API - Common_ _Part 1_ and/or _Part 2_,
as well as within a Web API conforming to additional OGC API Standards.

This Standard identifies twenty-eight Conformance Classes. Each Conformance Class has an associated Requirements Class.
The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.
Only the Core requirements class is mandatory, all other requirement classes are optional.

The Requirements Classes for _OGC API - Coverages_ are:

=== Requirements classes defining resources

* <<rc_core,*Core*>>
* <<rc_tiles,*Tiled Coverage Data*>>

The _Core_ Requirements Class is the minimal useful service interface for an implementation of OGC API - Coverages Standard. The requirements specified in the Core Requirements Class are mandatory for all implementations of _OGC API - Coverages_.

The _Tiled Coverage Data_ Requirements Class defines how to combine the _OGC API - Tiles_ requirements with the Coverages API to request tiled coverage data.

=== Requirements classes defining query parameters

* <<rc_subsetting_spatial,*Spatial Subsetting*>> (and related <<rc_sparse-dimensions-collapse-spatial,*Collapsing Sparse Spatial Dimensions*>>)
* <<rc_subsetting_temporal,*Temporal Subsetting*>> (and related <<rc_sparse-dimensions-collapse-temporal,*Collapsing Sparse Temporal Dimension*>>)
* <<rc_subsetting_general,*General Subsetting*>>  (and related <<rc_sparse-dimensions-collapse-general,*Collapsing Sparse General Dimensions*>>)
* <<rc_multi_slicing,*Multi Slicing*>>
* <<rc_scaling_spatial,*Spatial Scaling*>>
* <<rc_scaling_temporal,*Temporal Scaling*>>
* <<rc_scaling_general,*General Scaling*>>
* <<rc_field-selection,*Field Selection*>>
* <<rc_crs,*Coordinate Reference System by Reference*>>

The _Spatial, Temporal, and General Subsetting_ Requirements Classes provide capabilities to select a <<term-subsetting,subset>> of a coverage using a multi-dimensional "bounding box" which is suitable for any coordinate reference system and any dimension.

The _Multi Slicing_ Requirements Class extends the subsetting Requirements Class with the ability to request multiple <<term-slicing,slices>> at specific coordinates, including for <<term-irregular-grid, irregular grids>> and <<term-variable-type,categorical>> values.

The _Spatial, Temporal and General Scaling_ Requirements Classes define query parameters for retrieving data from an n-dimensional <<term-range,range>> set at a <<term-resolution,resolution>> different than the <<term-native-resolution,native resolution>> (<<term-resampling,resampling>>).

The _Field Selection_ (Range Subsetting) Requirements Class defines query parameters for selecting a subset of the <<term-field,fields>> (defined in the <<term-range-type, Range Type>> which is described in the schema resource of the collection) to retrieve from Range Sets.

The _Coordinate Reference System by Reference_ Requirements Class defines the ability to request coverage data in an alternate output coordinate reference system.

=== Requirements classes defining resource representations

* <<rc_position_query,*Position Query*>>
* <<rc_encoding-html,HTML>>
* <<rc_encoding-geotiff,GeoTIFF>>
* <<rc_encoding-cog,Cloud Optimized GeoTIFF>>
* <<rc_encoding-netcdf,netCDF>>
* <<rc_encoding-cisjson,CIS JSON>>
* <<rc_encoding-coveragejson,CoverageJSON>>
* <<rc_encoding-las,LAS>>
* <<rc_encoding-laszip,LASzip>>
* <<rc_encoding-png,PNG>>
* <<rc_encoding-jpegxl,JPEG XL>>
* <<rc_encoding-jpeg2000,JPEG 2000>>
* <<rc_encoding-zarr,(Geo)Zarr>>

The _Position Query_ Requirements Classes defines a simple JSON representation for the response to querying a coverage at a <<term-direct-position,direct position>>,
which is usually zero-dimensional (if not including the geometry of resulting <<term-cell,cell(s)>>),
having lost all its dimensionality through complete <<term-slicing,slicing>>.

The <<encodings-section,Representations Requirements Classes>> address support for formats commonly used for encoding coverage data.

=== Requirements class related to API definition

The <<rc_api_operations,*API Operations*>> Requirements Class defines additional requirements in addition to those defined in _OGC API - Common - Part 1: Core_ to facilitate identifying coverage
resources from an API definition.

=== Summary of conformance URIs

[#table_conformance_urls,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
| Corresponding requirements class              | Conformance class URI
| <<rc_core,Core>>                              | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/core
| <<rc_subsetting_spatial,Spatial Subsetting>>  | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/subsetting-spatial
| <<rc_subsetting_temporal,Temporal Subsetting>>| https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/subsetting-temporal
| <<rc_subsetting_general,General Subsetting>>  | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/subsetting-general
| <<rc_sparse-dimensions-collapse-spatial,Collapsing Sparse Spatial Dimensions>>  | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/sparse-dimensions-collapse-spatial
| <<rc_sparse-dimensions-collapse-temporal,Collapsing Sparse Temporal Dimension>> | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/sparse-dimensions-collapse-temporal
| <<rc_sparse-dimensions-collapse-general,Collapsing Sparse General Dimensions>>  | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/sparse-dimensions-collapse-general
| <<rc_multi_slicing,Multi Slicing>>            | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/multi-slicing
| <<rc_position_query,Position Query>>          | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/position-query
| <<rc_scaling_spatial,Spatial Scaling>>        | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/scaling-spatial
| <<rc_scaling_temporal,Temporal Scaling>>      | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/scaling-temporal
| <<rc_scaling_general,General Scaling>>        | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/scaling-general
| <<rc_field-selection,Field Selection>>        | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/field-selection
| <<rc_crs,CRS>>                                | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/crs
| <<rc_tiles,Tiled Coverage Data>>              | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/tiles
| <<rc_html,HTML>>                              | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/html
| <<rc_geotiff,GeoTIFF>>                        | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/geotiff
| <<rc_cog,Cloud Optimized GeoTIFF>>            | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/cog
| <<rc_netcdf,netCDF>>                          | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/netcdf
| <<rc_cisjson,CIS JSON>>                       | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/cisjson
| <<rc_coveragejson,CoverageJSON>>              | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/coveragejson
| <<rc_las,LAS>>                                | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/las
| <<rc_laszip,LASzip>>                          | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/laszip
| <<rc_png,PNG>>                                | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/png
| <<rc_jpegxl,JPEG XL>>                         | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/jpegxl
| <<rc_jpeg2000,JPEG 2000>>                     | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/jpeg2000
| <<rc_zarr,(Geo)Zarr>>                         | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/zarr
| <<rc_api_operations,API Operations>>          | https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/api-operations
|===
