[[rc_table_scaling_general]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/scaling-general
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

==== Query parameter `resolution`

[[req_coverage_scaling-general-resolution]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-scaling-general/resolution*
^|A |For data with a additional dimensions beyond spatial and a primary temporal dimension, the coverage retrieval operation SHALL support a `resolution` query parameter
specifying the resolution for the additional dimensions in positive units of those dimensions (as well as potentially supporting additional dimensions specified by other requirements classes).
^|B |The server SHALL support as a value for this parameter a comma-separated list of dimensions names followed by a resolution value in parentheses.
^|C |The server SHALL support an empty resolution value as referring to the native resolution for that particular dimension.
^|D |The server SHALL support as axis name all of the additional dimensions listed in the collection description's extent other than `spatial` and `temporal`.
^|E |A 400 error status code SHALL be returned if an axis name in the `resolution` parameter value does not correspond to an additional dimension described in the collection extent,
or to any other axis supported in the context of other requirements classes (such as spatial and temporal scaling).
^|F |For a regularly gridded coverage, the resolution (the distance between two samples along that dimension) for each of the listed dimension(s) SHALL correspond to the specified value.
^|G |For an irregularly gridded coverage, the distance between two samples along each of the listed dimension(s) SHALL be at minimum the value specified as the resolution for the corresponding dimension.
^|H |For a non-gridded coverage, when explicitly listing each dimension, the distance between two samples along each of the listed dimension(s) SHALL be at minimum the value specified as the resolution
for the corresponding dimension.
^|I |For additional dimensions where a `trs` of `https://www.opengis.net/def/crs/OGC/0/GregorianDateTime` is specified, the implementation SHALL support an ISO 8601 period notation.
|===

[[scaling-general-interpolation-recommendation]]
==== Recommendation for interpolation guidance

This Core part of the OGC API - Coverages Standard does not define a mechanism for the client to request a specific interpolation method.
However, the following recommendation provides guidance for implementations such as some important considerations to take into account when performing interpolation.
This guidance applies whether the resampling is performed as a result of the use of the scaling query parameters by the client,
or for automatic resampling in order to avoid returning too much data (as described in the downsampling permission below).

This guidance also applies to interpolation which could also be performed by clients.
Including an accurate description of the domain and range in a coverage response provided by the server allows to select a proper interpolation method.
The collection description and the collection logical schema also provides this information for all fields and dimensions of the full resolution coverage,
such as the `variableType` of a particular dimension, the `x-ogc-variableType` of a particular field, as well as a description of the gridded dimensions,
including the region of validity of individual grid cells where applicable.

[[rec_coverage_scaling-general-interpolation]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:per-id}* |*/rec/scaling-general/interpolation*
^|A | Implementations SHOULD NOT perform interpolation using a method other than _nearest neighbor_ for fields of a variable type other than `continuous`.
^|B | Implementations SHOULD NOT perform interpolation using a method other than _nearest neighbor_ for values along a dimension based on a variable with variable type other than `continuous`.
^|C | Implementations SHOULD use the best available interpolation method which will not significantly degrade response time or put too much strain on the server resources.
^|D | When interpolating gridded data, implementations SHOULD take into account the region of validity of values for individual grid cells, as identified in `relativeBounds` or `boundsCoordinates` of
the dimension's grid description (within the collection description's `extent`), typically considering the center of that region of validity for interpolation calculations.
When `relativeBounds` (for regular grids) or `boundsCoordinates` (for irregular grids) are omitted,
the coordinates (`firstCoordinate + n * resolution` for regular grids, `coordinates` for irregular grids) are assumed as being centered within the region of validity.
^|E | Implementations SHOULD include in all coverage responses an accurate description of the domain and range of the returned coverage, as well as a description of any interpolation
applied to the source data to produce that output, to the extent that the negotiated output format supports carrying that information.
|===

==== Downsampling permission

[[per_coverage_scaling-general-permission]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/coverage-scaling-general/downsampling*
^|A |In the case where a response to a request without a `resolution` parameters would be larger than an advertised server limit, an implementation
MAY automatically downsample the coverage to a suitable resolution instead of returning a 4xx client error.
|===

NOTE: A client retrieving a coverage from an implementation advertising support for this "General Scaling" requirements class should explicitly use e.g., `resolution=pressure()` if it wants to ensure
retrieving the coverage in its native resolution and prefers receiving an error instead of a downsampled version of the data.

==== Permission to support legacy scaling query parameters

[[per_coverage_scaling-general-permission-legacy]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/coverage-scaling-general/legacy*
^|A |Implementations MAY additionally support the `scale-factor` and `scale-axes` legacy query parameters expressing resolution as the factor by which the data's native resolution has been downsampled (a factor of 2 meaning two times coarser).
^|B |Implementations MAY additionally support the `scale-size` legacy query parameter expressing the number of samples expected in the output for each dimension.
|===

IMPORTANT: To ensure interoperability, clients should use the `resolution` query parameter rather than the legacy ones.
