[[rc_core-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|Target type   |Web API
|Dependency    |http://www.opengis.net/spec/ogcapi-common-2/1.0/req/umd-collection
|Dependency    |http://www.opengis.net/spec/ogcapi-common-3/1.0/req/schemas
|===

=== Requirements

==== Collection description

This "Core" requirements class of OGC API - Coverages depends on the https://docs.ogc.org/DRAFTS/20-024.html#rc-umd-collection-section["Uniform Multi-dimension Collection" requirements class] defined in
_Common - Part 2: Geospatial data_, in addition to the basic https://docs.ogc.org/DRAFTS/20-024.html#rc-collections-section["Collections" requirements class], allowing to describe the domain of the coverage,
akin to the CIS DomainSet.
If the coverage represents gridded data, the grid description requirements apply, allowing to describe regular and regular grids for each gridded dimension.
For both regular and irregular grids, a `cellsCount` property specifies the number of cells.
For regular grids, a `firstCoordinate` and `resolution` is specified, with optional `relativeBounds`.
For irregular grids, a list of `coordinates` is specified, with optional `boundsCoordinates` pairs.

[[req_core-collection_description]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collection-description*
^|A |For every collection accessible using the _Coverages API_, the description  SHALL
include in its `links` array a link to a coverage resource at `/collections/{collectionId}/coverage` using the link relation type `[ogc-rel:coverage]`.
This `links` array SHALL be present within the elements of the `collections` array of the `/collections` resource, as well as at the `/collections/{collections}` resource.
^|B |Each of these collection resources SHALL also include in its `links` array a link to a schema describing the coverage fields at `/collections/{collectionId}/schema`
using the link relation type `[ogc-rel:schema]`.
^|C |At least one collection SHALL be accessible as a coverage.
^|D |If the collection is available more efficiently (e.g., if it is stored in the server in that CRS) using a particular CRS (the native CRS, also _called storage CRS_) that is not
http://www.opengis.net/def/crs/OGC/1.3/CRS84, a `storageCrs` property in the collection object of a geospatial collection SHALL be the URI for that CRS.
This `storageCrs` also corresponds to the default output CRS (used when the `crs` query parameter is not specified and/or the CRS requirements class is not supported).
^|E |If a `storageCrs` property is used and that is not https://www.opengis.net/def/crs/OGC/1.3/CRS84, an overall bounding box (and optional inner bounding boxes for sparse data)
SHALL be provided in a `storageCrsBbox` property within the `spatial` dimension of the `extent` following the same schema as the CRS84 `bbox`.
|===

////
No longer specified here, since it is already specified in Common - Part 2:
^|C |Each of these collection resources SHALL use the uniform additional dimensions schema to describe its domain as part of the `extent` property of that collection.
This implies using an `interval` array property to describe the overall envelope and optionally sub-intervals for sparsely populated data.
The first element of the array is the overall envelope, while any additional elements detail where data is available within that overall interval.
Each of these elements are themselves an array of start and end bound values.
^|D |Any additional temporal dimension SHALL include in a `trs` property a URI corresponding to the temporal reference system associated with that dimension.
^|E |For additional dimensions which are neither temporal nor spatial, the dimension SHALL include a `definition` property corresonding to a URI for the observed or measured property.
^|F |If applicable, units SHALL be specified in a `unit` property specifying the unit and an (optional) `unitLang` property specifying the language (defaulting to UCUM).
^|G |The name (JSON dictionary key) of each additional dimension SHALL correspond to the axis abbreviation for the CRS of that axis, to valid axis names for use with query parameters defined in optional requirements classes such as `subset` and `resolution`, as well as to axis names in the coverage response, if applicable.
^|H |If a particular dimension of the coverage is gridded, the description of that dimension in the extent SHALL describe this grid using the `grid` property, providing a `cellsCount`, as well as a `resolution` for regular grid or a set of `coordinates` for irregular grids.
^|I |For data referenced in relation to planet Earth, the coordinates in the `bbox` of the `spatial` dimensions of the `extent` SHALL be provided either as WGS 84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84[http://www.opengis.net/def/crs/OGC/1.3/CRS84]) or as WGS 84 longitude/latitude/ellipsoidal height (http://www.opengis.net/def/crs/OGC/0/CRS84h[http://www.opengis.net/def/crs/OGC/0/CRS84h]).
////

NOTE: A CURIE `{authority}[-{objectType}]:{id}` would map to the following OGC URI: `http://www.opengis.net/def/{objectType}/{authority}/0/{id}`. If `-{objectType}` is missing, the default object type is _crs_.

NOTE: The schema for the collection resource is available at https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/collectionDesc.yaml.

NOTE: A property indicating for which planetary body a CRS is applicable is being considered as part of CRS definitions, which will facilitate validating the requirement
for Earth-referenced data collections to be described using OGC:CRS84.

TODO: Discuss the ability to include a http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] definition and/or
https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/common-geodata/projJSON.yaml[PROJ-JSON] definition of the CRS instead of a URI.

==== Collection schema (`/collections/{collectionId}/schema`)

This "Core" requirements class of OGC API - Coverages depends on the "Schemas" requirements class defined in _OGC API - Common - Part 3: Schemas_
(identical to https://docs.ogc.org/DRAFTS/23-058.html[OGC API - Features - Part 5: Schemas]),
in addition to the basic "Collections" requirements class, allowing to describe the fields of the coverage, akin to the CIS RangeType.

[[req_core-coverage_fields_schema]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/coverage-fields-schema*
^|A |The API SHALL support the HTTP GET operation at the path `/collections/{collectionId}/schema` to retrieve the schema of the coverage fields,
including support for JSON Schema when negoiating the `application/schema+json` media type.
^|B |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|C |The content of that response SHALL include a list of the fields for the coverage, including an identifier (the property key), a `title`, a `type` and an optional `description`.
^|D |Each field SHALL include an `x-ogc-propertySeq` property with an integer value establishing a sequential order for the fields.
|===

NOTE: This schema is a logical schema, and not intended to be used directly for validation.
The use of JSON Schema is therefore not limited to describe only coverages encoded in JSON-based encodings.

NOTE: A meta-schema for JSON Schema used as part of the _2D Tile Matrix Set and Tileset Metadata standard_ suitable for this resource is available at
https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/tms/propertiesSchema.yaml .

==== Coverage data retrieval (`/collections/{collectionId}/coverage`)

[[req_core-get_coverage]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/get-coverage*
^|A |The implementation SHALL support the HTTP GET operation at the path `/collections/{collectionId}/coverage` to retrieve the coverage.
^|B |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|C |The content of that response SHALL be the coverage data, along with the suported self-description capabilities of the negotiated content type.
^|D |The response SHALL be encoded using the format(s) negotiated through the HTTP protocol.
^|E |If no format is negotiated, then the response SHALL be encoded using the format associated with the media type described in the link object which links to this resource, contained within the coverage (collection) resource.
^|F |The coverage response SHALL be in the native (`storageCrs`) specified in the collection description, or http://www.opengis.net/def/crs/OGC/1.3/CRS84 if none is specified, unless overridden by a specific query parameter (see <<rc_crs>>).
|===

==== Response headers

[[req_core-coverage_response_headers]]
[width="90%",cols="2,6"]
|===
^|A |The coverage response headers SHALL include a `Content-Crs:` header with the URI of the CRS of the coverage response, except if the content is in the http://www.opengis.net/def/crs/OGC/1.3/CRS84 CRS.
^|B |If the returned coverage has a spatial extent, the headers of the response SHALL include a `Content-Bbox:` header with the actual geospatial boundary of the coverage.
^|C |If applicable, the `Content-Bbox:` coordinates SHALL be in the response CRS (indicated in `Content-Crs:`, or http://www.opengis.net/def/crs/OGC/1.3/CRS84 if it is not present) and SHALL contain
four or six comma-separated numbers representing the lower-left and upper right corners of the response honoring the CRS coordinates order.
^|D |If the coverage includes a temporal dimension which can be expressed in RFC3339 format, the headers of the response SHALL include a `Content-Datetime:` header in that format with the actual datetime instant
(if returning a temporal slice) or datetime interval (if the response includes a temporal dimension) of the returned coverage.
|===

==== Query parameter `resolution` (empty values for native resolution)

[[req_core-native-resolution]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/native-resolution*
^|A |An implementation SHALL accept a `resolution` query parameter for a GET operation on the coverage resource,
for empty resolution values (e.g., `resolution=Lat(),Lon(),time()`) indicating a request for the native resolution of the corresponding dimension(s),
whether the implementation supports or not the <<rc_scaling_spatial, "Spatial Scaling">>, <<rc_scaling_spatial, "Temporal Scaling">> and/or <<rc_scaling_spatial, "General Scaling">> requirements classes.
^|B |An implementation not supporting scaling for a dimension for which a non-empty value has been specified using the `resolution` query parameter SHALL return a 4xx error.
|===

NOTE: An implementation not supporting scaling for any dimension (not conforming to any of the scaling requirements classes) can simply ignore the `resolution` query parameter, and return the data at the
native resolution as if the query parameter was not used. The implementation would return an error if the selected subset or the whole coverage requested exceeds the server limits at this native resolution.

IMPORTANT: Clients wishing to ensure they always retrieve a native resolution coverage can include in their coverage data request a `resolution` query parameter specifying all dimensions with empty values:
`resolution=Lat(),Lon(),time()` (including any additional dimension), regardless of whether the server implements any of the Scaling requirements classes. For most large datasets, these clients
would also need to include subsetting parameters (`subset`, `bbox` and/or `datetime`, assuming the server supports the corresponding subsetting requirements classes) to avoid an error response due
to requesting more data than allowed by the server limits.

==== Server limits recommendations

[[rec_core-limits]]
[width="90%",cols="2,6"]
|===
^|*Recommendation {counter:per-id}* |*/per/core/limits*
^|A |The implementation SHOULD advertise maximum limits for individual dimensions and/or combined data size that it is willing to return in a `coverage` object property of
an `x-OGC-limits` property of the service metadata `info` object property of a JSON document linked to from the landing page using the `service-meta` link relation.
^|B |The implementation SHOULD include in this `coverage` property of the service metadata `x-OGC-limits`: `maxWidth`, `maxHeight` and `maxCells` integer properties for
implementations supporting gridded coverages, and/or a `maxPoints` integer property for implementations supporting point clouds coverages.
^|C |The implementation SHOULD return a 4xx error for coverage requests exceeding any of those limits.
|===

NOTE: An example of service metadata is provided in https://docs.ogc.org/is/19-072/19-072.html#service-metadata-examples[_OGC API – Common – Part 1: Core_].
The service metadata might be embedded directly within an OpenAPI API definition, meaning that the `service-meta` and `service-desc` links may point to the same JSON document.
