[[rc_subsetting-general-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/subsetting-general
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

[[subset-general-parameter-subset-requirements]]
==== Query parameter `subset`

[[req_subsetting-general_subset]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting-general/subset*
^|A |The coverage request operation SHALL support a parameter `subset` to subset one or more of the dimensions of the coverage (as described in the collection information)
with the following characteristics (using an Extended Backus Naur Form (EBNF) fragment):

[source,EBNF]
----
  SubsetSpec:       "subset"=axisName(intervalOrPoint)
  axisName:         {text}
  intervalOrPoint:  interval \| point
  interval:         low : high
  low:              point \| *
  high:             point \| *
  point:            {number} \| "{text}"

  Where:
     \" = double quote = ASCII code 0x42,
     {number} is an integer or floating-point number, and
     {text} is some general ASCII text (such as a time and date notation in ISO 8601).
----

^|B |Only that part of the coverage that falls within the bounds of the subset expression SHALL be returned.
^|C |If a single point is provided for an axis, the coverage response SHALL be the result of a slicing operation for the dimension corresponding to that axis, reducing the dimension.
^|D |If an interval is provided for an axis, the coverage response SHALL be the result of a trimming operation for the dimension corresponding to that axis, preserving the dimension.
^|E |The server SHALL support as axis name all of the additional dimensions listed in the collection description's extent other than `spatial` and `temporal`.
^|F |A 400 error status code SHALL be returned if an axis name in the `subset` parameter value does not correspond to an additional dimension described in the collection extent, or to any other axis supported in the context of other requirements classes (such as spatial and temporal subsetting).
^|G |If the _intervalOrPoint_ values fall entirely outside the range of valid values defined for the identified axis, a 204 or 404 status code SHALL be returned.
^|H |If a lower limit of the subset interval is populated with an asterisk `*`, then the minimum extent of the coverage along that axis SHALL be selected.
^|I |If a upper limit of the subset interval is populated with an asterisk `*`, then the maximum extent of the coverage along that axis SHALL be selected.
^|J |Multiple subset parameters SHALL be interpreted, as if all dimension subsetting values were provided in a single subset parameter (comma-separated)^1^.

2+|1 Example: subset=Lat(-90:90)&subset=Lon(-180:180)&subset=time("2018-02-12T23:20:52Z")&subset=atm_pressure_hpa(500) is equivalent to subset=Lat(-90:90),Lon(-180:180),time("2018-02-12T23:20:52Z"),atm_pressure_hpa(500)
2 Note that this is only valid of the spatial dimensions. The ‘additional’ dimensions rely on the names of the extent of the collection.
|===

NOTE: When the _intervalOrPoint_ values fall partially outside of the range of valid values defined by the CRS for the identified axis,
the service is expected to return the non-empty portion of the coverage resulting from the subset.
For subsetting on the range set, and for coverage media types with no geo-referencing mechanisms (e.g. PNG), NO_DATA values or transparency should be used.
If a georeferencing mechanism is available within the negotiated media type, the service could decide whether to use NO_DATA values
or simply return the properly geo-referenced values within the domain set.

==== Permission for Slicing Sparse Dimensions

[[per_subsetting-general_slice-sparse-dimension]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/subsetting-general/slice-sparse-dimension*
^|A |The empty portions in a coverage resulting from a slice operation on an axis (e.g. time), combined with a trimming operations on other axes (e.g. latitude and longitude)
 which would either be empty or not cover the full extent of the trim operation MAY be filled with data values from the same trim operation
 combined with a slicing operation on a different value of the slicing axis which would return non-empty values.
 For example, the closest or last previous time for which data is available for a certain geospatial extent may be returned.
 An Earth Observation use case for this permission is to allow retrieving a slice of the last available imagery on or before a certain date,
 taking into account that a certain geographic area may only be observed every few days.
^|B |This permission applies to both explicit slice operations using subset, as well as to implicit slicing from requesting an output format only supporting
 a lower dimensionality than the data (e.g. requesting a 2D image from a 3D coverage as PNG or GeoTIFF).
^|C |A query parameter defined by a custom or standardized extension MAY be made available to enable, disable or alter that behavior.
|===

IMPORTANT: Slicing (a `subset` specifying a single value for a particular dimension) is mutually exclusive with scaling on that same dimension
as per <<req_subsetting-spatial_subset>> (using the `resolution` query parameter as defined in the relevant Scaling requirements class).

==== Recommendation for interpolation preference when supporting slicing on sparse dimensions

[[rec_subsetting-general_slice-prefer-header]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/subsetting-general/slice-prefer-header*
^|A |When supporting slicing on sparse dimensions, the Implementation SHOULD understand a `Prefer:` request header
(as defined in https://datatracker.ietf.org/doc/html/rfc7240[RFC 7240]) value provided by the client hinting at the preferred
<<conventions-interpolation-methods, interpolation method>>.
^|B |The implementation SHOULD support an `interpolation=` value for that `Prefer:` header selecting one specific interpolation method using a safe CURIEs or URI, such as from the OGC
definition server (https://www.opengis.net/def/interpolation/OGC/1), for specific dimensions being sliced. Example: `Prefer: interpolation=pressure([ogc-interpolation:linear])`
^|C |The implementation SHOULD support a `properties-interpolation=` value for that `Prefer:` header selecting one specific interpolation method for specifics field being returned,
which will override interpolation methods specified in any `interpolation` preference for any dimension, using a safe CURIEs or URI, such as from the OGC
definition server (https://www.opengis.net/def/interpolation/OGC/1). Example: `Prefer: properties-interpolation=landCover([ogc-interpolation:nearest-neighbor])`.
^|D |The implementation SHOULD also support in the context of that `properties-interpolation=` value the selection of an interpolation method for a specific
field and dimension, which will override interpolation for that field only for that dimension, using the `dimension:URI` syntax inside the parentheses, for example:
`Prefer: properties-interpolation=landCover(pressure:[ogc-interpolation:nearest-neighbor])`.
^a|E | The implementation SHOULD consider supporting the following interpolations methods, with the following meaning in the context of the slicing sparsed dimensions permission:

- `[ogc-interpolation:next]`: Use the next available data point from the sliced dimension,
- `[ogc-interpolation:previous]`: Use the previous available data point from the sliced dimension,
- `[ogc-interpolation:nearest-neighbor]`: Use the nearest data point from the sliced dimension,
- `[ogc-interpolation:linear]`: Perform a linear interpolation between the previous and next available data point from the sliced dimension,
- `[ogc-interpolation:quadratic]`: Perform a quadratic interpolation between the previous and next available data point from the sliced dimension,
- `[ogc-interpolation:none]`: Only return a value if the sliced dimension corresponds exactly to an available data point, return NODATA otherwise (hit or miss)
|===

==== Recommendation for default interpolation method when supporting slicing on sparse dimensions

[[rec_subsetting-general_slice-default-interpolation]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/subsetting-general/slice-default-interpolation*
^|A | The implementation SHOULD use either `[ogc-interpolation:previous]` or `[ogc-interpolation:nearest-neighbor]`
when no preference is specified by the client.
|===

==== Requirement for indicating a preference has been applied when supporting slicing on sparse dimensions

[[rec_subsetting-general_slice-preference-applied]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting-general/slice-preference-applied*
^|A | If an Implementation supports <<rec_slice_general_prefer, client preferences for interpolation>>,
the Implementation SHALL use a response header `Preference-Applied:` when it applied the preference specified by the client, for example,
`Preference-Applied: interpolation=pressure([ogc-interpolation:linear])` and `Preference-Applied: properties-interpolation=landcover([ogc-interpolation:nearest-neighbor])`.
|===

==== Requirement for strict or lenient preference handling when supporting slicing on sparse dimensions

[[req_subsetting-general_slice-preference-handling]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting-general/slice-preference-handling*
^|A | If an Implementation supports <<rec_subsetting-general_slice-prefer-header, client preferences for interpolation>>,
the Implementation SHALL support the `Prefer: handling` parameter defined in https://www.rfc-editor.org/rfc/rfc7240#section-4.4[RFC 7249 Section 4.4] where a value of `handling=lenient` would simply ignore an unsupported preference,
while a value of `handling=strict` SHALL return a 4xx error if the server is not able to fulfill the preference of the client
(note that the handling parameter applies to the request as a whole, rather than to any specific preference).
^|B | If no handling preference is specified, the Implementation SHALL default to lenient handling for the purpose of
interpolation preferences.
|===
