[[rc_scaling]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/scaling
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

==== `scale-factor`, `scale-size` and `scale-axes` parameters

The scaling parameters are defined in the following Requirement:

[[req_coverage_scaling-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-scaling/definition*
^|A |The operation SHALL support a parameter `scale-size` with the following characteristics (using an Extended Backus Naur Form (EBNF) fragment):

[source,EBNF]
----
  ScalingSpec:       "scale-size"=axisName({number})[,axisName({number})]*
  axisName:          {text}

  Where:
     {number} is an integer or floating-point number, and

----
^|B |The operation SHALL support `scale-factor` numeric parameter.
^|C |The operation SHALL support a parameter `scale-axes` with the following characteristics (using an Extended Backus Naur Form (EBNF) fragment):

[source,EBNF]
----
  ScalingSpec:       "scale-axes"=axisName({number})[,axisName({number})]*
  axisName:          {NCName}

  Where:
     {number} is an integer or floating-point number, and
----

^|D |The axis name SHALL be the same as one of the `axisLabels` defined in the DomainSet, and shall match the abbreviations defined by the CRS
(as defined bythe <gml:axisAbbrev> tags).  or else return a 400 status code.
|===

The results of using a scaling parameter are defined by the following Requirement:

[[req_coverage_scaling-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-scaling/success*
^|A |The `scale-size=AxisName(count)`, `scale-factor=factor` and `scale-axes=AxisName(factor)` parameters SHALL be supported for the coverage and range set resources.
^|B |When `scale-size` is used, the returned coverage SHALL contain exactly the specified number of sample values along each axis which is specified, and the original number of sample values for unspecified axes.
^|C |When `scale-factor` is used, for each axis, the returned coverage SHALL contain the number of original sampled values, divided by _factor_.
^|D |When `scale-axes` is used, for each axis specified, the returned coverage SHALL contain the number of original sampled values, divided by the _factor_ specified for that axis, and the original number of sample values for unspecified axes.
^|E |When `scale-size` is used together with subsetting, the requested number of samples SHALL be mapped to the subset dimensions specified, even if those dimensions fall partially outside the extent of the coverage.
|===

==== Downsampling permission

[[req_coverage_scaling-permission]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/per/coverage-scaling/downsampling*
^|A |In the case where a response to a request without a `scale-factor`, `scale-axes` or `scale-size` parameters would be larger than an advertised server limit, an implementation
MAY automatically downsample the coverage to a suitable resolution instead of returning a 4xx client error.
|===

NOTE: A client retrieving a coverage from an implementation advertising support for this "Scaling" requirements class should explicitly use `scale-factor=1` if it wants to ensure
retrieving the coverage in its native resolution and prefers receiving an error instead of a downsampled version of the data.
