[[rc_table_multi_slicing]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/multi-slicing
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

==== Multi slicing for query parameter `subset`

[[req_coverage_multi_slicing_multi_slicing]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-multi-slicing/multi-slicing*
^|A |The coverage retrieval operation SHALL support a comma-separated list of coordinate values for the `subset` query parameter for each dimension supported by the Spatial Subsetting,
Temporal Subsetting and General Subsetting requirements classes
^|B |For the dimensions for which a multi-slice subset query parameter is specified, the coverage response SHALL only contain values for the coordinates explicitly listed.
|===

[[per_coverage_multi_slicing_nodata]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/coverage-multi-slicing/nodata*
^|A |For responses in an encoding unsuitable for sparse data or irregular grids (such as GeoTIFF 1.x),
a regular grid encompassing the overall interval of all slices with null values for coordinates not explicitly requested MAY be used.
|===
