[[rc_core-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|Target type   |Web API
|Dependency    |http://www.opengis.net/spec/ogcapi-common-2/1.0/req/umd-collection
|Dependency    |http://www.opengis.net/spec/ogcapi-common-2/1.0/req/schemas
|===

=== Requirements

==== Extended collection list response (`/collections`)

[[req_core-collection_list]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collection-list*
^|A |For every collection accessible using the _Coverages API_, the content of the elements of `collections` for the `/collections` resource SHALL include in its `links` array a link to a coverage resource at `/collections/{collectionId}/coverage` using the link relation type `[ogc-rel:coverage]`.
^|B |At least one collection SHALL be accessible as a coverage.
|===

==== Extended collection description response (`/collections/{collectionId}`)

This "Core" requirement class of OGC API - Coverages depends on the "Uniform Multi-dimension Collection" requirement class defined in _Common - Part 2: Geospatial data_,
in addition to the basic "Collections" requirement class, allowing to describe the domain of the coverage, akin to the CIS DomainSet.

[[req_core-collection_description]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collection-description*
^|A |For every collection accessible using the _Coverages API_, the collection description resource SHALL include in its `links` array a link to a coverage resource at `/collections/{collectionId}/coverage` using the link relation type `[ogc-rel:coverage]`.
^|B |Each of these collection resources SHALL also include in its `links` array a link to a coverage schema at `/collections/{collectionId}/schema` using the link relation type `[ogc-rel:schema]`.
^|C |Each of these collection resources SHALL use the uniform additional dimensions schema to describe its domain as part of the `extent` property of that collection.
This implies using an `interval` array property to describe the overall envelope and optionally sub-intervals for sparsely populated data.
The first element of the array is the overall envelope, while any additional elements detail where data is available within that overall interval.
Each of these elements are themselves an array of start and end bound values.
^|D |Any additional temporal dimension SHALL include in a `trs` property a URI or safe CURIE corresponding to the temporal reference system associated with that dimension.
^|E |For additional dimensions which are neither temporal nor spatial, the dimension SHALL include a `definition` property corresonding to a URI for the observed or measured property.
^|F |If applicable, units SHALL be specified in a `unit` property specifying the unit and an (optional) `unitLang` property specifying the language (defaulting to UCUM).
^|G |The name (JSON dictionary key) of each additional dimension SHALL correspond to the axis abbreviation for the CRS of that axis, to valid axis names for use with query parameters defined in optional requirements classes such as `subset` and `scale-axes`, as well as to axis names in the coverage response, if applicable.
^|H |If a particular dimension of the coverage is gridded, the description of that dimension in the extent SHALL describe this grid using the `grid` property, providing a `cellsCount`, as well as a `resolution` for regular grid or a set of `coordinates` for irregular grids.
^|I |For data referenced in relation to planet Earth, the coordinates in the `bbox` of the `spatial` dimensions of the `extent` SHALL be provided either as WGS 84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84[http://www.opengis.net/def/crs/OGC/1.3/CRS84]) or as WGS 84 longitude/latitude/ellipsoidal height (http://www.opengis.net/def/crs/OGC/0/CRS84h[http://www.opengis.net/def/crs/OGC/0/CRS84h]).
^|J |The `storageCrs` property SHALL be set to the native CRS of the coverage, also corresponding to the default output CRS (used when the `crs` parameter is not specified and/or the CRS requirements class is not supported).
^|K |The `crs` property in the collection object of a geospatial collection SHALL contain URIs or safe CURIEs for the list of CRSs supported by the server for that collection.
^|L |If the collection is available more efficiently (e.g., if it is stored in the server in that CRS) using a particular CRS (the native CRS, also _called storage CRS_) that is not http://www.opengis.net/def/crs/OGC/1.3/CRS84, a `storageCrs` property in the collection object of a geospatial collection SHALL be the URI or the safe CURIE for that CRS.
^|M |If a `storageCrs` property is used and that is not https://www.opengis.net/def/crs/OGC/1.3/CRS84, an overall bounding box (and optional inner bounding boxes for sparse data) SHALL be provided in a `storageCrsBbox` property within the `spatial` dimension of the `extent` following the same schema as the CRS84 `bbox`.
|===

NOTE: A CURIE `{authority}[-{objectType}]:{id}` would map to the following OGC URI: `http://www.opengis.net/def/{objectType}/{authority}/0/{id}`. If `-{objectType}` is missing, the default object type is _crs_.

NOTE: A schema for this extended collection resource is available at https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/common-geodata/collectionInfo.yaml.

NOTE: A property indicating for which planetary body a CRS is applicable is being considered as part of CRS definitions, which will facilitate validating this requirement.

TODO: Discuss the ability to include a http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] definition and/or
https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/common-geodata/projJSON.yaml[PROJ-JSON] definition of the CRS instead of a URI.

==== Collection schema response (`/collections/{collectionId}/schema`)

This "Core" requirement class of OGC API - Coverages depends on the "Schemas" requirement class defined in _Common - Part 2: Geospatial data_,
in addition to the basic "Collections" requirement class, allowing to describe the range of the coverage, akin to the CIS RangeType.

[[req_core-coverage_schema]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/coverage-schema*
^|A |The API SHALL support the HTTP GET operation at the path `/collections/{collectionId}/schema` to retrieve the schema of the coverage fields.
^|B |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|C |The content of that response SHALL include a list of the fields for the coverage, including an identifier (the property key), a `title`, a `type` and an optional `description`.
^|D |Each field SHALL include an `x-ogc-property-seq` property with an integer value establishing a sequential order for the fields.
|===

NOTE: A meta-schema for JSON Schema used as part of the _2D Tile Matrix Set and Tileset Metadata standard_ suitable for this resource is available at https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/tms/propertiesSchema.yaml .
This resource should also match the draft https://docs.ogc.org/DRAFTS/23-058.html[_OGC API - Features - Part 5: Schemas_].

==== Coverage data retrieval (`/collections/{collectionId}/coverage`)

[[req_core-get_coverage]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/get-coverage*
^|A |The implementation SHALL support the HTTP GET operation at the path `/collections/{collectionId}/coverage` to retrieve the coverage.
^|B |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|C |The content of that response SHALL be the coverage data, along with the suported self-description capabilities of the negotiated content type.
^|D |The response SHALL be encoded using the format(s) negotiated through the HTTP protocol.
^|E |If no format is negotiated, then the response SHALL be encoded using the format associated with the media type described in the link object which links to this resource, contained within the coverage (collection) resource.
^|F |The coverage response SHALL be in the native (`storageCrs`) specified in the collection description, or http://www.opengis.net/def/crs/OGC/1.3/CRS84 if none is specified, unless overridden by a specific query parameter (see <<rc_crs>>).
^|G |The headers SHALL include a `Content-Crs:` header with the URI or the safe CURIEs of the CRS of the coverage response, except if the content is in the http://www.opengis.net/def/crs/OGC/1.3/CRS84 CRS.
^|H |If the returned coverage has a spatial extent, the headers of the response SHALL include a `Content-Bbox:` header with the actual geospatial boundary of the coverage.
^|I |If applicable, the `Content-Bbox:` coordinates SHALL be in the response CRS (indicated in `Content-Crs:`, or http://www.opengis.net/def/crs/OGC/1.3/CRS84 if it is not present) and SHALL contain four comma separated numbers representing the lower-left and upper right corners of the response honoring the CRS coordinates order.
^|J |An implementation not supporting the <<rc_scaling, "Scaling" requirements class>> SHALL still accept a `scale-factor` query parameter for a GET operation on the coverage resource, but only for a value of exactly `1` (returning a 4xx error otherwise). In this case, the implementation will simply ignore the parameter, and either return the data at the native resolution as if the parameter was not used, or return an error if the selected subset or the whole coverage requested would exceed the server limits. This allows for clients wishing to ensure they always retrieve a native resolution coverage by always including a `scale-factor=1` parameter.
|===

[[rec_core-limits]]
[width="90%",cols="2,6"]
|===
^|*Recommendation {counter:per-id}* |*/per/core/limits*
^|A |The implementation SHOULD advertise maximum limits for individual dimensions and/or combined data size that it is willing to return in the `x-OGC-limits.coverage` property of the service metadata, provided as an extension of the info section of the API definition, as indicated in https://docs.ogc.org/is/19-072/19-072.html[_OGC API – Common – Part 1: Core_].
^|B |The implementation SHOULD include in the `x-OGC-limits.coverage` `maxWidth`, `maxHeight` and `maxCells` integer properties for implementations supporting gridded coverages, and/or a `maxPoints` integer property for implementations supporting point clouds coverages.
^|C |The implementation SHOULD return an 4xx error for coverage requests exceeding any of those limits.
|===

[[per_core-cis-metadata]]
[width="90%",cols="2,6"]
|===
^|*Permission {counter:per-id}* |*/per/core/cis-metadata*
^|A |The implementation MAY omit the CIS domain-specific metadata by default as part of the coverage response.
|===
