[[rc_table_,multi_slicing]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/multi-slicing
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

==== Query parameter `resolution`

[[req_coverage_scaling-spatial-resolution]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-scaling-spatial/resolution*
^|A |The coverage retrieval operation SHALL support a `resolution` query parameter specifying the resolution for one or more of the spatial dimensions in positive units of the spatial CRS
(as well as potentially supporting additional dimensions specified by other requirements classes).
^|B |The server SHALL support an empty resolution value as referring to the native resolution for that particular dimension.
^|C |The server SHALL support as a value for this parameter a comma-separated list of dimensions names followed by a resolution value in parentheses.
^|D |For a geographic output CRS, axis names `Lat` and `Lon` SHALL be supported which are to be interpreted as the best matching spatial axis in the output CRS definition.
^|E |For a projected output CRS, axis names `E` and `N` SHALL be supported, which are to be interpreted as the best matching spatial axis in the output CRS definition.
^|F |If a third spatial dimension is supported (if the data's spatial extent bounding box is three-dimensional), the implementation SHALL also support a `h` dimension.
This is the elevation above the ellipsoid in EPSG:4979 or CRS84h for geographic CRS, and _z_ for 3D Cartesian CRS such as EPSG:4978, which are to be interpreted as the vertical axis in the CRS definition.
^|G |A 400 error status code SHALL be returned if an axis name in the `resolution` parameter value does not correspond to one of the axes of the output CRS,
to an alias (see recommendation below), or to any other axis supported in the context of other requirements classes (such as temporal and general scaling).
^|H |For a regularly gridded coverage, the resolution (the distance between two samples along that dimension) for each of the listed dimension(s) SHALL correspond to the specified value.
^|I |For an irregularly gridded coverage, the distance between two samples along each of the listed dimension(s) SHALL be at minimum the value specified as the resolution for the corresponding dimension.
^|J |For a non-gridded coverage (e.g., a point cloud), when explicitly listing each dimension, the distance between two samples along each of the listed dimension(s) SHALL be at minimum the value specified as the resolution for the corresponding dimension.
^|K |For a non-gridded coverage (e.g., a point cloud), the server SHALL support a special dimension named `spatial-distance` representing the minimum vectorial distance (e.g., square root of &#916;N^2^ + &#916;E^2^ + Δh^2^) between two samples.
^|L |When returning the native resolution for one or more dimension for multiple fields with different resolutions (as specified in the schema's `x-ogc-resolution`) in output formats which do not support
returning those different fields together at these different resolutions, the Implementation SHALL use the finest resolution for all fields.
|===

==== Query parameters `width` and `height`

[[req_coverage_scaling-spatial-width_and_height]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-scaling-spatial/width-and-height*
^|A |For coverages with a spatial dimension corresponding to the horizontal spatial axis as represented on a 2D map, such as longitude or easting, the operation SHALL support a parameter `width` for the coverage resource taking an integer parameter corresponding to the number of cells that should be returned along that axis.
^|B |For coverages with a spatial dimension corresponding to the vertical spatial axis as represented on a 2D map, such as latitude or northing, the operation SHALL support a parameter `height` for the coverage resource taking an integer parameter corresponding to the number of cells that should be returned along that axis.
^|C |The returned coverage SHALL contain exactly the specified number of sample values along each axis which is specified by provided scaling  parameters, the original number of sample values for unspecified axes, and any defined server limits.
^|D |When `width` and/or `height` is used together with subsetting, the requested number of samples SHALL be mapped to the subset dimensions specified, even if those dimensions fall partially outside the extent of the coverage.
|===

[[scaling-spatial-dimension-aliases-recommendation]]
==== Recommendation for spatial dimensions aliases

Because the definitions of CRSs of the same type sometimes use different names to refer to dimensions that can be considered equivalent for the purposes of scaling, and in some cases the axis name abbreviation changed over time,
this Standard recommends that Implementations recognize common equivalent names to facilitate the task of clients to identify a particular dimension.
Generic clients intended to be interoperable with all Implementations of this Standard should not use these aliases, but only the axis names specified in the above requirement.

[[rec_coverage_scaling-crs-axis-aliases]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:per-id}* |*/rec/scaling-spatial/resolution-crs-axis-aliases*
^|A |Axis abbreviations as defined in the CRS definition SHOULD be interpreted as synonymous of the corresponding prescribed axis names, providing they do not conflict with other prescribed axis names or the aliases described below.
^|B |`e` (in lowercase), `X` (lowercase/uppercase) or `Easting` (lowercase/uppercase) SHOULD be interpreted as synonymous of `E`.
^|C |`n` (in lowercase), `Y` (lowercase/uppercase) or `Northing` (lowercase/uppercase) SHOULD be interpreted as synonymous of `N`.
^|D |`Z`, (lowercase/uppercase) or `H` (uppercase) SHOULD be interpreted as synonymous of `h`.
^|D |`lon` (in lowercase), `Long` (lowercase/uppercase) or `Longitude` (lowercase/uppercase) SHOULD be interpreted as synonymous of `Lon`.
^|E |`lat` (in lowercase) or `Latitude` (lowercase/uppercase) SHOULD be interpreted as synonymous of `Lat`.
|===

IMPORTANT: To ensure interoperability, clients should always use the prescribed spatial axis names (`Lat`, `Lon`, `h`, `E`, `N`) and not rely on any of the aliases.

[[scaling-spatial-interpolation-recommendation]]
==== Recommendation for interpolation guidance

This Core part of the OGC API - Coverages Standard does not define a mechanism for the client to request a specific interpolation method.
However, the following recommendation provides guidance for implementations such as some important considerations to take into account when performing interpolation.
This guidance applies whether the resampling is performed as a result of the use of the scaling query parameters by the client,
or for automatic resampling in order to avoid returning too much data (as described in the downsampling permission below).

This guidance also applies to interpolation which could also be performed by clients.
Including an accurate description of the domain and range in a coverage response provided by the server allows to select a proper interpolation method.
The collection description and the collection logical schema also provides this information for all fields and dimensions of the full resolution coverage,
such as the `x-ogc-variableType` of a particular field, as well as a description of the gridded dimensions,
including the region of validity of individual grid cells where applicable.

[[rec_coverage_scaling-spatial-interpolation]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:per-id}* |*/rec/scaling-spatial/interpolation*
^|A | Implementations SHOULD NOT perform interpolation using a method other than _nearest neighbor_ for fields of a variable type other than `continuous`.
^|B | Implementations SHOULD use the best available interpolation method which will not significantly degrade response time or put too much strain on the server resources.
^|C | When interpolating gridded data, implementations SHOULD take into account the region of validity of values for individual grid cells, as identified in `relativeBounds` or `boundsCoordinates` of
the dimensions' grid description (within the collection description's `extent`), typically considering the center of that region of validity for interpolation calculations.
When `relativeBounds` (for regular grids) or `boundsCoordinates` (for irregular grids) are omitted,
the coordinates (`firstCoordinate + n * resolution` for regular grids, `coordinates` for irregular grids) are assumed as being centered within the region of validity.
^|D | Implementations SHOULD include in all coverage responses an accurate description of the domain and range of the returned coverage, as well as a description of any interpolation
applied to the source data to produce that output, to the extent that the negotiated output format supports carrying that information.
|===

==== Downsampling permission

[[per_coverage_scaling-spatial-permission]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/coverage-scaling-spatial/downsampling*
^|A |In the case where a response to a request without a `resolution`, `width`, or `height` parameters would be larger than an advertised server limit, an implementation
MAY automatically downsample the coverage to a suitable resolution instead of returning a 4xx client error.
^|B |In the case where a `resolution`, `width` or `height` does not explicitly specify dimensions for all spatial axes of the coverage, an implementation MAY automatically proportionately
adjust one or more unspecified dimensions.
|===

NOTE: A client retrieving a coverage from an implementation advertising support for this "Spatial Scaling" requirements class should explicitly use `resolution=Lat(),Lon()` if it wants to ensure
retrieving the coverage in its native spatial resolution and prefers receiving an error instead of a downsampled version of the data.

==== Permission to support legacy scaling query parameters

[[per_coverage_scaling-spatial-permission-legacy]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/coverage-scaling-spatial/legacy*
^|A |Implementations MAY additionally support the `scale-factor` and `scale-axes` legacy query parameters expressing resolution as the factor by which the data's native resolution has been downsampled. For example, `scale-factor=2.0` meaning two times coarser; `scale-axes=Lat(1),Lon(1)` means native spatial resolution for a 2D geographic CRS.
^|B |Implementations MAY additionally support the `scale-size` legacy query parameter expressing the number of samples expected in the output for each dimension. For example, `scale-size=Lat(300),Lon(400)` means 400 samples across the longitude axis and 300 samples across the latitude axis.
|===

IMPORTANT: To ensure interoperability, clients should use the `resolution` and/or `width` and `height` query parameters rather than the legacy ones.
