[[rc_sparse-dimensions-collapse-general-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/sparse-dimensions-collapse-general
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/subsetting-general
|===

=== Requirements

==== Requirement for Slicing Sparse Dimensions

[[req_sparse-dimensions-collapse-general_slice-sparse-dimension]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sparse-dimensions-collapse-general/slice-sparse-dimension*
^|A |For a slicing operation on a general dimension combined with a trimming operation on other axes
(such as latitude and longitude), the Implementation SHALL fill empty portions (NODATA) with data values from other
nearby non-empty values along that general dimension.
For example, the closest pressure level for which data is available for a certain geospatial extent may be returned.
|===

IMPORTANT: Slicing (a `subset` specifying a single value for a particular dimension) is mutually exclusive with scaling on that same dimension
(using the `resolution` query parameter as defined in the relevant Scaling requirements class) as per <<subset-general-parameter-subset-requirements>>.

NOTE: Clients wishing to avoid this filling behavior can specify a request header such as
`Prefer: interpolation=pressure([ogc-interpolation:none]),
which most Implementations of this requirements class would support as per the
<<rec_sparse-dimensions-collapse-general_slice-prefer-header, recommendation for interpolation preferences>>.

==== Requirement for Flattening Sparse Dimensions

[[req_sparse-dimensions-collapse-general_flattening-sparse-dimension]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sparse-dimensions-collapse-general/flattening-sparse-dimension*
^|A |For a trimming operation on a general dimension combined with a trimming operation on other axes
(such as latitude and longitude), requested for a format which does not support including that general dimension in the response,
the Implementation SHALL flatten the resulting coverage, collapsing that general dimension while preserving non-empty portions
based on a default or selected <<conventions-interpolation-methods, interpolation method>> preference.
For example, requesting a 2D image in PNG for a specific pressure level from a 3D coverage with space and pressure.
|===

NOTE: See also the <<downsampling-permission,recommendations and permissions>> related to collapsing sparse dimensions and interpolation shared by the Spatial, Temporal and General Scaling Collapsing Sparse Dimensions requirements classes.
