[[rc_laszip]]

[requirements_class]
.LASzip
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/laszip
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
inherit:: https://portal.ogc.org/files/?artifact_id=74523[OGC 17-030r1 LAS Specification 1.4 Community Standard]
inherit:: https://www.cs.unc.edu/~isenburg/lastools/download/laszip.pdf[LASzip: lossless compression of LiDAR data]
requirement:: /req/laszip/coverage
====

==== Requirements

[[requirements-class-laszip-clause]]

===== LASzip representation

[[req_laszip_coverage]]
[requirement]
====
[%metadata]
identifier:: /req/laszip/coverage
part:: If a particular collection such as point cloud is suitable for a LASzip representation, the coverage resource as defined in the Coverages API Core requirement class SHALL support negotiating a LASzip: lossless compression of LiDAR data[LASzip] response using the `application/vnd.laszip` media type.
part:: The response SHALL be a LASzip point cloud which validates against the LASzip format, which can be used for lossless compression of point cloud data encoded in the OGC LAS Community Standard, using a Point Data Record Format suitable for the data being returned.
====
