[[rc_cisjson]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/cisjson
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|Dependency  |http://www.opengis.net/spec/CIS/1.1/req/json-coverage
|===

==== Requirements

[[requirements-class-cisjson-clause]]

The following requirements apply to an OGC API-Coverage implementation when the following conditions apply:

. The API advertises conformance to the CIS JSON Conformance Class
. The client negotiates a JSON or CIS JSON format

The CIS JSON Requirements Class restricts requirements defined in the `GeoData-Coverage` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `GeoData-Coverage` requirements which lay within each scope.

===== Coverage

This section covers the <<coverage-clause,Coverage>> response for the
`{datasetAPI}/collections/{collectionId}/coverage` operation.

[[req_cisjson_coverage-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cisjson/coverage-success*
^|A |A successful coverage request SHALL be reported as a response with a HTTP status code `200`.
^|B |The response SHALL be a CIS JSON document which validates against the JSON schema link:https://raw.githubusercontent.com/opengeospatial/ogcapi-coverages/master/standard/openapi/schemas/coverage.json[coverage.json].
|===

===== Profiling CIS components to include

// TODO: This will be adjusted to describe a `profile=domainset` query parameter

[[rec_cisjson_domainset-success]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/cisjson/domainset-success*
^|A |The coverage request operation SHOULD support a `profile` query parameter allowing to select specific CIS one or more coverage components to include (domainset, rangetype, rangeset and/or metadata).
^|B |If supported, the response SHOULD only contain the selected element(s). For example, `../coverage?profile=domainset,rangetype` should only return the domain set and range type for the coverage.
^|C |If both this capability and subsetting are supported, the subsetting SHOULD be applied to both the domainset and the rangeset components of the response.
^|D |The implementation SHOULD return the metadata when explicitly requested to do so with the `profile` queyr parameter.
|===
