[[rc_table_position_query]]

[requirements_class]
.Position Query
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/position-query
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
requirement:: /req/position-query/position-query
====

=== Requirements

==== Position query for subsetting parameters (`subset`, `datetime`)

[[req_coverage_position_query_position_query]]
[requirement]
====
[%metadata]
identifier:: /req/position-query/position-query
part:: The coverage retrieval operation SHALL support the ability to slice on all dimensions using the `subset` and/or `datetime` query parameters effectively reducing the dimensionality
of the response to zero dimensions (a point).
part:: An implementation SHALL support negotiating a JSON response (through request header `Accept: application/json`) for such point query which in a common scenario consists of an object with one
property being the name of the field (for each default or selected field) and its associated values.
part:: In the case where the coverage is a multi-function (for example, a multi-polygon feature collection backing data store), the response SHALL instead be an array of such objects.
part:: In the case where a single field is being returned (whether the coverage consists of a single field, the default list of fields is a single field, or the client requests a single field through the
Field Selection requirements class), the response SHALL be the value of the field directly (rather than an object with the field name), or in the case of the coverage multi-function, an array of values.
====

NOTE: This position query requirements class relies on the definition of the `subset` and `datetime` query parameters defined in the
<<rc_subsetting_spatial,Spatial Subsetting>>, <<rc_subsetting_temporal,Temporal Subsetting>> and <<rc_subsetting_general,General Subsetting>> requirement classes.
However, the Position Query requirements class does not specify a dependency on these other requirements classes to allow implementing only the "Core" requirements class (returning the entire coverage), as well
as the ability to query specific points, without providing the ability to return fragments of the coverage larger than a single point.

[[rec_coverage_position_query_interpolation]]
[recommendation]
====
[%metadata]
identifier:: /rec/position-query/interpolation
part:: In the case where the requested position does not fall within the defined bounds (region of validity) of an individual cell, an implementation SHOULD
decide whether to perform an interpolation or not, and select the best suitable interpolation, based on the <<term-variable-type,variable type>> of each <<term-field,field>> being returned,
as well as the variable type of each dimension being sliced on.
====

NOTE: See also the recommendations to support <<spatial-aliases-recommendation,spatial>> and primary <<temporal-aliases-recommendation,temporal>> dimension name aliases
applicable to this requirements class.

NOTE: See also the <<interpolation-guidance-recommendation,recommendations and permissions>> related to interpolation.
