[[rc_zarr]]

[requirements_class]
.(Geo)Zarr
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/zarr
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
inherit:: https://zarr-specs.readthedocs.io/en/latest/v2/v2.0.html[Zarr2, Zarr Storage Specification Version 2]
inherit:: <<ZIPISO, ISO/IEC 21320-1:2015 Information technology - Document Container File (Zip)>>
requirement:: /req/zarr/coverage
====

==== Requirements

[[requirements-class-zarr-clause]]

===== Zarr representation

[[req_zarr_coverage]]
[requirement]
====
[%metadata]
identifier:: /req/zarr/coverage
part:: Coverage responses for the coverage resource, as defined in the Coverages API Core requirements class, SHALL support negotiating a https://zarr-specs.readthedocs.io/en/latest/v2/v2.0.html[Zarr] response packaged in a https://www.iso.org/standard/60101.html[Zip] file using the `application/zarr+zip` media type.
part:: The Zarr response SHALL use the appropriate data types most closely matching the coverage fields.
part:: The response SHALL contain all selected fields.
part:: If the response contains multiple fields, the fields SHALL be encoded as bands ordered following the `x-ogc-propertySeq` sequence.
====

[[rec_zarr_geozarr]]
[recommendation]
====
[%metadata]
identifier:: /rec/zarr/geozarr
part:: Georeferencing information SHOULD be included in the response using the https://github.com/zarr-developers/geozarr-spec[GeoZarr] candidate Standard.
====
