[[rc_geotiff]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/geotiff
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|Dependency  |https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf
|Dependency  |https://docs.ogc.org/is/19-008r4/19-008r4.html
|===

// [[GeoTIFF]] OGC 19-008: *OGC GeoTIFF Standard*, Version 1.1, http://docs.opengeospatial.org/is/19-008r4/19-008r4.html
// [[[TIFF_V6,TIFF V6.0]]], Adobe Developers Association: TIFF Specification Revision 6.0. (1992) https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf[https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf]

==== Requirements

[[requirements-class-geotiff-clause]]

===== GeoTIFF representation

[[req_geotiff_coverage]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/geotiff/coverage*
^|A |Two-dimensional coverage responses for the coverage resource as defined in the Core requirement class SHALL support negotiating a https://docs.ogc.org/is/19-008r4/19-008r4.html[GeoTIFF] response using the `image/tiff; application=geotiff` media type.
^|B |The response SHALL be a GeoTIFF document which validates against the GeoTIFF and TIFF standard.
^|C |If the response contains multiple fields, the fields SHALL be encoded as bands ordered following the `x-OGC-property-seq` sequence.
|===

===== GeoTIFF parameters

[[rec_geotiff_compression]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/geotiff/compression*
^|A |The coverage resource SHOULD support a `compression` parameter.
^|B |The possible values for the `compression` parameter SHOULD be `none`, `packbits`, `huffman`, `lzw`, `deflate`.
^|C |The GeoTIFF coverage response SHOULD use the compression method specified.
|===

[[rec_geotiff_predictor]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/geotiff/predictor*
^|A |The coverage resource SHOULD support a `predictor` parameter.
^|B |The possible values for the `compression` parameter SHOULD be `none`, `horizontal`, `floating-point`.
^|C |The GeoTIFF coverage response SHOULD use the predictor specified.
|===

[[rec_geotiff_interleave]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/geotiff/interleave*
^|A |The coverage resource SHOULD support a `interleave` parameter.
^|B |The possible values for the `interleave` parameter SHOULD be `pixel` (PlanarConfiguration value 1 for chunky, PLANARCONFIG_CONTIG in libtiff) and `band`
(PlanarConfiguration value 2 for planar configuration, PLANARCONFIG_SEPARATE in libtiff).
^|C |The GeoTIFF coverage response SHOULD use the interleave setting specified (corresponding to the PlanarConfiguration in TIFF terminology).
|===

[[rec_geotiff_tiling]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/geotiff/tiling*
^|A |The coverage resource SHOULD support a boolean `tiling` parameter.
^|B |The GeoTIFF coverage response SHOULD use tiling if `tiling` is true, or strips otherwise.
|===

[[rec_geotiff_tile-height-width]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/geotiff/tile-width-height*
^|A |The coverage resource SHOULD support integer multiple of 16 `tile-width` and `tile-height` parameters when a `tiling` parameter is used.
^|B |The Implementation SHOULD return an error if these parameters are provided without a `tiling` parameter, or if their value is not a multiple of 16 greater than 0.
^|C |The GeoTIFF coverage response SHOULD use these tile width and tile height (TileLength in TIFF terminology).
|===

[[rec_geotiff_overview-count]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/geotiff/overview-count*
^|A |The coverage resource SHOULD support a integer `overview-count`.
^|B |The Implementation SHOULD return an error if this parameter is smaller than 0.
^|C |The GeoTIFF coverage response SHOULD generate progressively smaller overviews based on that requested number of overviews.
|===

NOTE: Clients can use a combination of `tiling`, `tile-width`, `tile-height` and `overview-count` to get a GeoTIFF conforming to the https://docs.ogc.org/is/21-026/21-026.html[OGC Cloud Optimize GeoTIFF] standard.
