[[rc_sparse-dimensions-collapse-temporal-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/sparse-dimensions-collapse-temporal
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/subsetting-temporal
|===

=== Requirements

==== Requirement for Slicing Sparse Dimensions

[[req_sparse-dimensions-collapse-temporal_slice-sparse-dimension]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sparse-dimensions-collapse-temporal/slice-sparse-dimension*
^|A |For a slicing operation on the temporal dimension combined with a trimming operation on other axes
(such as latitude and longitude), the Implementation SHALL fill empty portions (NODATA) with data values from other
nearby non-empty values along the temporal dimension.
For example, the closest or last previous time for which data is available for a certain geospatial extent may be returned.
An Earth Observation use case for this permission is to allow retrieving a slice of the last available imagery on or before a
certain date, taking into account that a certain geographic area may only be observed every few days.
|===

IMPORTANT: Slicing (a `subset` specifying a single value for a particular dimension) is mutually exclusive with scaling on that same dimension
(using the `resolution` query parameter as defined in the relevant Scaling requirements class) as per <<subset-temporal-parameter-subset-requirements>>.

NOTE: Clients wishing to avoid this filling behavior can specify a request header such as
`Prefer: interpolation=time([ogc-interpolation:none]),
which most Implementations of this requirements class would support as per the
<<rec_sparse-dimensions-collapse-temporal_slice-prefer-header, recommendation for interpolation preferences>>.

===== Example slicing sparse dimensions

In this example, a client requests a bounding box for (40 N, 30 E)-(70 N, 50 E), while slicing a date:

`datetime=2025-01-01&f=application/x-netcdf&bbox=30,40,50,70`.

Because the primary temporal dimension is sparse due to some satellites only covering some of the Earth's surface on a given day, data is not available for that specific date for some of the
spatial region covered. In this case, the server can use data from a nearby date to fill those regions.

==== Requirement for Flattening Sparse Dimensions

[[req_sparse-dimensions-collapse-temporal_flattening-sparse-dimension]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sparse-dimensions-collapse-temporal/flattening-sparse-dimension*
^|A |For a trimming operation on the temporal dimension combined with a trimming operation on other axes
(such as latitude and longitude), requested for a format which does not support including a temporal dimension in the response,
the Implementation SHALL flatten the resulting coverage, collapsing the temporal dimension while preserving non-empty portions
based on a default or selected <<conventions-interpolation-methods, interpolation method>> preference.
For example, requesting a 2D image in PNG for a specific time interval from a spatiotemporal 3D coverage.
|===

===== Example flattening sparse dimensions

In this example, a trim operation is performed, but because the PNG format is inherently 2D, it implies a "flattening" of the
response such that this permission applies:

[source,http]
----
GET /collections/sentinel2-l2a/coverage?datetime=2025-01-01/2025-01-31&bbox=30,40,50,70
Accept: image/png
----

The server can then perform a mosaic of the month of January with the most recent images displayed on top.

NOTE: See also the <<downsampling-permission,recommendations and permissions>> related to collapsing sparse dimensions and interpolation shared by the Spatial, Temporal and General Scaling Collapsing Sparse Dimensions requirements classes.
