[[rc_jpeg2000]]

[requirements_class]
.JPEG 2000
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/jpeg2000
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
inherit:: https://www.iso.org/standard/78321.html[ISO/IEC 15444-1:2019]
inherit:: https://www.iso.org/standard/84573.html[ISO/IEC 15444-2:2023]
inherit:: https://docs.ogc.org/is/08-085r8/08-085r8.html
requirement:: /req/jpeg2000/coverage
====

==== Requirements

[[requirements-class-jpeg2000-clause]]

===== JPEG 2000 representation

[[req_jpeg2000_coverage]]
[requirement]
====
[%metadata]
identifier:: /req/jpeg2000/coverage
part:: Two-dimensional coverage responses for the coverage resource, as defined in the Coverages API Core requirements class, SHALL support negotiating a https://jpeg.org/jpeg2000/[JPEG 2000] response using the `image/jp2` media type.
part:: The JPEG 2000 response SHALL use the appropriate data types most closely matching the coverage field (e.g., 8 bit or 16-bit integer, 32-bit floating point).
part:: The response SHALL contain all selected fields.
part:: If the response contains multiple fields, the fields SHALL be encoded as bands ordered following the `x-ogc-propertySeq` sequence.
part:: Georeferencing SHALL be included in the response using the https://docs.ogc.org/is/08-085r8/08-085r8.html[GMLJP2] encoding, consistent with the requested subset of the coverage domain.
====
