[[rc_table_fieldselection]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/fieldselection
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

==== Query parameter `properties`

[[req_fieldselection-properties]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/fieldselection/properties*
^|A |The coverage retrieval operation SHALL support a `properties` query parameter where the value is a comma-separated list of field names to be returned.
^|B |The implementation SHALL support selecting a field using the identifier corresponding to the top-level property keys of the coverage fields schema, and return 400 status code for an unrecognized selected field.
^|C |Only the selected fields of the coverage SHALL be returned in the coverage response.
^|D |If the coverage response can self-describes its list of fields (as with the CIS _range type_), the field description SHALL be adjusted accordingly to the new selected fields.
^|E |If the negotiated format of the response has a concept of field order, then the fields SHALL be in the same order as the requested list of selected fields.
|===

==== Query parameter `exclude-properties`

[[req_fieldselection-exclude-properties]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/fieldselection/exclude-properties*
^|A |The coverage retrieval operation SHALL support an `exclude-properties` query parameter where the value is a comma-separated list of fields not to be returned.
^|B |The Implementation SHALL support selecting fields not to return using the identifier corresponding to the top-level property keys of the coverage fields schema, and return 400 status code for an unrecognized selected field.
^|C |All but the selected fields SHALL be returned from the zone data request (including fields potentially not included in the `defaultFields` of the collection description).
^|D |The Implementation SHALL return a 4xx error when using the both the `properties` and `exclude-properties` query parameters in the same request.
^|E |If the negotiated format of the response has a concept of field order, then the fields SHALL be in the sequence order of the `x-ogc-propertySeq` of the fields listed in the logical schema (ignoring the excluded fields).
^|F |The Implementation SHALL interpret an empty value for this the `exclude-properties` query parameter as a request for all fields listed in the logical schema (e.g., in the case where the `defaultFields` are a subset of the fields available).
|===

==== Mismatched resolution without scaling support

[[req_fieldselection-mismatched-resolution]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/fieldselection/mismatched-resolution*
^|A |For requests including multiple fields which have different resolutions (as specified in the schema's `x-ogc-resolution`) in output formats which do not support returning those
different fields together at these different resolutions, the Implementation SHALL return a 4xx error if it does not support the Scaling requirements class.
|===
