[[rc_sparse-dimensions-collapse-spatial-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/sparse-dimensions-collapse-spatial
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/subsetting-spatial
|===

=== Requirements

==== Requirement for Slicing Sparse Dimensions

[[req_sparse-dimensions-collapse-spatial_slice-sparse-dimension]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sparse-dimensions-collapse-spatial/slice-sparse-dimension*
^|A |For a slicing operation on spatial dimension(s) combined with a trimming operation on other axes
(such as time), the Implementation SHALL fill empty portions (NODATA) with data values from other
nearby non-empty values along the spatial dimensions.
For example, the closest spatial location for which data is available for a certain temporal instant may be returned.
|===

IMPORTANT: Slicing (a `subset` specifying a single value for a particular dimension) is mutually exclusive with scaling on that same dimension
(using the `resolution` query parameter as defined in the relevant Scaling requirements class) as per <<subset-spatial-parameter-subset-requirements>>.

===== Example of slicing on sparse dimensions

In this example, the slicing dimension is space while the trim is performed on the temporal dimension:

[source,http]
----
GET /collections/temperature/coverage?datetime=2025-01-01/2025-12-31&subset=Lat(30),Lon(40)
Accept: application/x-netcdf
----

The weather data is requested for a specific position of some weather station over the year 2025. For some particular dates, there is no data available from that station,
but observations are available for nearby stations. The server can then use the nearest station (e.g., at `Lat(31),Lon(42)`) to fill the gaps within the time series returned.

NOTE: Clients wishing to avoid this filling behavior can specify a request header such as
`Prefer: interpolation=Lat([ogc-interpolation:none]),Lon([ogc-interpolation:none])` (for a geographic CRS), or
`Prefer: interpolation=E([ogc-interpolation:none]),N([ogc-interpolation:none])` (for a projected CRS),
which most Implementations of this requirements class would support as per the
<<rec_sparse-dimensions-collapse-spatial_slice-prefer-header, recommendation for interpolation preferences>>.

==== Requirement for Flattening Sparse Dimensions

[[req_sparse-dimensions-collapse-spatial_flattening-sparse-dimension]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sparse-dimensions-collapse-spatial/flattening-sparse-dimension*
^|A |For a trimming operation on the spatial dimension combined with a trimming operation on other axes
(such as time), requested for a format which does not support including a spatial dimension in the response,
the Implementation SHALL flatten the resulting coverage, collapsing the spatial dimension while preserving non-empty portions
based on a default or selected <<conventions-interpolation-methods, interpolation method>> preference.
For example, requesting a time series image for a specific bounding box from a spatiotemporal 3D coverage.
|===

NOTE: See also the <<downsampling-permission,recommendations and permissions>> related to collapsing sparse dimensions and interpolation shared by the Spatial, Temporal and General Scaling Collapsing Sparse Dimensions requirements classes.
