[[rc_json]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/cisjson
|Target type |Web API
|Dependency |<<rc_core,Requirements Class "API-Common Core">>
|Dependency |http://www.opengis.net/spec/ogcapi-common-1/1.0/req/json[API-Common JSON]
|Pre-conditions |
1) The API advertises conformance to the CIS JSON Conformance Class +
2) The client negotiates use of the JSON or CIS JSON encoding.
|===

==== Requirements

[[requirements-class-cisjson-clause]]

The following requirements apply to an OGC API-Coverage implementation when the following conditions apply:

. The API advertises conformance to the CIS JSON Conformance Class
. The client negotiates a JSON or CIS JSON format

The CIS JSON Requirements Class restricts requirements defined in the `GeoData-Coverage` Requirements Class by imposing encoding-specific requirements. At this time, these additional requirements only apply to the HTTP response payloads. The sections below identify the scope of each new requirement and the `GeoData-Coverage` requirements which lay within each scope.

===== Coverage

This section covers the <<coverage-clause,Coverage>> response for the
`{datasetAPI}/collections/{collectionId}/coverage` operation.

[[req_cisjson_coverage-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cisjson/coverage-success*
^|**Restricts** |/req/core/coverage-success
^|A |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|B |The response SHALL be a CIS JSON document which validates against the JSON schema link:https://raw.githubusercontent.com/opengeospatial/ogcapi-coverages/master/standard/openapi/schemas/coverage.json[coverage.json].
|===

===== Coverage Domain Set

// TODO: This will be adjusted to describe a `profile=domainset` query parameter

This section covers the <<coverage-domainset-clause,Coverage Domain Set>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/domainset` operation.

[[req_cisjson_domainset-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cisjson/domainset-success*
^|**Restricts** |/req/core/domainset-success
^|A |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|B |The response SHALL be a CIS JSON document which validates against the JSON schema link:https://raw.githubusercontent.com/opengeospatial/ogcapi-coverages/master/standard/openapi/schemas/coverage_domainset.json[coverage_domainset.json].
|===

===== Coverage Range Type

// TODO: This will be adjusted to describe a `profile=rangetype` query parameter

This section covers the <<coverage-rangetype-clause,Coverage Range Type>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/rangetype` operation.

[[req_cisjson_rangetype-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cisjson/rangetype-success*
^|**Restricts** |/req/core/rangetype-success
^|A |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|B |The response SHALL be a CIS JSON document which validates against the JSON schema link:https://raw.githubusercontent.com/opengeospatial/ogcapi-coverages/master/standard/openapi/schemas/coverage_rangetype.json[coverage_rangetype.json].
|===

===== Coverage Range Set

// TODO: This will be adjusted to describe a `profile=rangeset` query parameter

This section covers the <<coverage-rangeset-clause,Coverage Range Set>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/rangeset` operation.

[[req_cisjson_rangeset-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cisjson/rangeset-success*
^|**Restricts** |/req/core/rangeset-success
^|A |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|B |The response SHALL be a CIS JSON document which validates against the JSON schema link:https://raw.githubusercontent.com/opengeospatial/ogcapi-coverages/master/standard/openapi/schemas/coverage_rangeset.json[coverage_rangeset.json].
|===

[[req_domainset_subset-subset-select]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cisjson/domainset-subset-select*
^|A |The `subset` parameter SHALL be applied to the domainset
^|B |Only that part of the domainset addressed SHALL be selected that falls within the bounds of the subset expression whereby a `*` (asterisk) in the position of a lower or upper limit along an axis denotes the DomainSet's minimum or maximum extent along this axis, respectively. The DomainSet shall be adjusted accordingly to the new boundaries (in case of trimming) and the reduced dimension (in case of slicing).
|===

===== Coverage Metadata

// TODO: This will be adjusted to describe a `profile=metadata` query parameter

This section covers the <<coverage-metadata-clause,Coverage Metadata>> response for the
`{datasetAPI}/collections/{collectionId}/coverage/metadata` operation.

[[req_cisjson_metadata-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cisjson/metadata-success*
^|**Restricts** |/req/core/metadata-success
^|A |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|B |The response SHALL be a JSON document which validates against the JSON schema link:https://raw.githubusercontent.com/opengeospatial/ogcapi-coverages/master/standard/openapi/schemas/coverage_metadata.json[coverage_metadata.json].
|===
