[[rc_core-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|Target type   |Web API
|Dependency    |https://www.opengis.net/spec/ogcapi-common-1/1.0/req/core
|Dependency    |https://www.opengis.net/spec/ogcapi-common-2/1.0/req/collections
|Dependency    |https://www.opengis.net/spec/ogcapi-common-2/1.0/req/umd-collection
|Dependency    |https://www.opengis.net/spec/ogcapi-common-3/1.0/req/schemas
|Dependency    |https://www.opengis.net/spec/ogcapi-common-3/1.0/req/returnables-and-receivables
|===

=== Requirements

==== Conformance declaration

To support "generic" clients that want to access implementations of multiple OGC API Standards and extensions — and not "just" a specific API / server,
the deployed API must declare the conformance classes it implements and conforms to.

The conformance declaration response mainly consists of a list of links.

[[req_core_conformance_success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/conformance-success*
^|A |If the API instance has a mechanism to advertise conformance classes, the list of conformance classes SHALL include the ones defined in this Standard and listed in <<table_conformance_urls>> that are supported by this API implementation instance.
|===

In the JSON format, the conformance resource is an array of links following the link schema defined in OGC API — Common — Part 1: Core.
Below is an example fragment of a conformance information page of an API implementation conformant to OGC API — Coverages.

```json
{
  "conformsTo": [
    "https://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "https://www.opengis.net/spec/ogcapi-common-1/1.0/conf/landing-page",
    "https://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/core"
  ]
}
```

==== Collection description

This "Core" requirements class of OGC API - Coverages depends on the https://docs.ogc.org/DRAFTS/20-024.html#rc-umd-collection-section["Uniform Multi-dimension Collection" requirements class] defined in
_Common - Part 2: Geospatial data_, in addition to the basic https://docs.ogc.org/DRAFTS/20-024.html#rc-collections-section["Collections" requirements class], allowing to describe the domain of the coverage,
akin to the CIS DomainSet.
If the coverage represents gridded data, the grid description requirements apply, allowing to describe regular and regular grids for each gridded dimension.
For both regular and irregular grids, a `cellsCount` property specifies the number of cells.
For regular grids, a `firstCoordinate` and `resolution` is specified, with optional `relativeBounds`.
For irregular grids, a list of `coordinates` is specified, with optional `boundsCoordinates` pairs.
The collection description will also include a link to the logical schema describing the coverage fields avilable as JSON Schema using the link relation type https://www.opengis.net/def/rel/ogc/1.0/schema.

[[req_core-collection_description]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collection-description*
^|A |For every collection accessible using the _Coverages API_, the description  SHALL
include in its `links` array a link to a coverage resource, typically at `/collections/{collectionId}/coverage`, using the link relation type `[ogc-rel:coverage]`.
This `links` array SHALL be present within the elements of the `collections` array of the `/collections` resource, as well as at the `/collections/{collectionId}` resource.
^|B |At least one collection SHALL be accessible as a coverage.
^|C |If the collection is available more efficiently (e.g., if it is stored in the server in that CRS) using a particular CRS (the native CRS, also _called storage CRS_) that is not
https://www.opengis.net/def/crs/OGC/1.3/CRS84, a `storageCrs` property in the collection object of a geospatial collection SHALL be the URI or safe CURIE for that CRS.
This `storageCrs` also corresponds to the default output CRS (used when the `crs` query parameter is not specified and/or the CRS requirements class is not supported).
^|D |If a `storageCrs` property is used and that is not https://www.opengis.net/def/crs/OGC/1.3/CRS84, an overall bounding box (and optional inner bounding boxes for sparse data)
SHALL be provided in a `storageCrsBbox` property within the `spatial` dimension of the `extent` following the same schema as the CRS84 `bbox`.
|===

NOTE: A CURIE `{authority}[-{objectType}]:{id}` would map to the following OGC URI: `https://www.opengis.net/def/{objectType}/{authority}/0/{id}`. If `-{objectType}` is missing, the default object type is _crs_.

NOTE: The schema for the collection resource is available at https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/common-geodata/collectionDesc.yaml.

NOTE: A property indicating for which planetary body a CRS is applicable is being considered as part of CRS definitions, which will facilitate validating the requirement
for Earth-referenced data collections to be described using OGC:CRS84.

TODO: Discuss the ability to include a https://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] definition and/or
https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/common-geodata/projJSON.yaml[PROJ-JSON] definition of the CRS instead of a URI.

[[rec_core-coverage_dimensions_variable_type]]
[width="90%",cols="2,6"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/coverage-dimensions-variable-type*
^|A |Additional dimensions beyond space and time based on a variable SHOULD include a `variableType` property with values `continuous`, `categoricalOrdinal`, `categoricalNominal`, `numericalOrdinal`,
or `numericalNominal` providing useful information relevant to how to properly perform interpolation along that dimension.
|===

==== Collection schema (`/collections/{collectionId}/schema`)

This "Core" requirements class of OGC API - Coverages depends on the "Schemas" requirements class defined in _OGC API - Common - Part 3: Schemas_
(identical to https://docs.ogc.org/DRAFTS/23-058r1.html[OGC API - Features - Part 5: Schemas]),
in addition to the basic "Collections" requirements class, allowing to describe the fields of the coverage, akin to the CIS RangeType.

This logical schema describing the fields is available via an HTTP GET request, linked from the collection description using the link relation type https://www.opengis.net/def/rel/ogc/1.0/schema,
with the resource typically available at `/collections/{collectionId}/schema`. The client can negotiate a JSON Schema using the media type `application/schema+json`.

[[req_core-coverage_fields_schema]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/coverage-fields-schema*
^|A |The content of the schema response SHALL include a list of the fields for the coverage, including an identifier (the property key), a `title`, a `type` and an optional `description`.
^|B |Each field SHALL include an `x-ogc-propertySeq` property with an integer value establishing a sequential order for the fields.
^|C |If some fields are available at different resolutions than others, each field SHALL include an `x-ogc-resolution` property with an object property mapping a value for each dimension
which differs from the resolution specified in the collection's grid description to the name of the dimension (e.g., "Lon" for longitude, "E" for easting, "time" for the primary temporal dimension).
^|D |If the implementation supports field selection, and not all fields described in the collection schema are returned by default, a `defaultFields` property in the collection description SHALL
list all fields being returned by default in the order that they are returned in the response of the coverage (for formats where this is applicable).
|===

////
TODO: Review and include an example
{
 "B08" : {
      "title" : "Band 8 (nir) - wavelength: 0.6901-0.9801 μm",
      "type" : "number",
      "x-ogc-propertySeq" : 9,
      "x-ogc-resolution": { "Lat": 0.00001, "Lon": 0.00001, "time": "P1D" }
   }
}
////

NOTE: This schema is a logical schema, and not intended to be used directly for validation.
The use of JSON Schema is therefore not limited to describe only coverages encoded in JSON-based encodings.

NOTE: A meta-schema for JSON Schema used as part of the _2D Tile Matrix Set and Tileset Metadata standard_ suitable for this resource is available at
https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/tms/propertiesSchema.yaml .

[[rec_core-coverage_schema_variable_type]]
[width="90%",cols="2,6"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/coverage-schema-variable-type*
^|A |The logical schema for the collection SHOULD include an `x-ogc-variableType` for each field with possible values `continuous`, `categoricalOrdinal`, `categoricalNominal`, `numericalOrdinal`,
or `numericalNominal` providing useful information relevant to how to properly perform interpolation for that field.
|===

==== Coverage data retrieval

[[req_core-get_coverage]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/get-coverage*
^|A |The implementation SHALL support the HTTP GET operation to retrieve the coverage (from the coverage resource linked to as `[ogc-rel:coverage]`, typically `/collections/{collectionId}/coverage`).
^|B |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|C |The content of that response SHALL be the coverage data, along with the suported self-description capabilities of the negotiated content type.
^|D |The response SHALL be encoded using the format(s) negotiated through the HTTP protocol.
^|E |If no format is negotiated, then the response SHALL be encoded using the format associated with the media type described in the link object which links to this resource, contained within the coverage (collection) resource.
^|F |The coverage response SHALL be in the native (`storageCrs`) specified in the collection description, or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if none is specified, unless overridden by a specific query parameter (see <<rc_crs>>).
^|G |If the coverage response format has a concept of field order (for lack of descriptive field metadata, as in GeoTIFF 1.0), that order SHALL match the fields being requested, either based on the selected fields
(see Field Selection requirements class), the `defaultFields` if specified in the collection description, or otherwise the `x-ogc-propertySeq` in the collection schema.
|===

==== Response headers

[[req_core-coverage_response_headers]]
[width="90%",cols="2,6"]
|===
^|A |The coverage response headers SHALL include a `Content-Crs:` header with the URI of the CRS of the coverage response, except if the content is in the https://www.opengis.net/def/crs/OGC/1.3/CRS84 CRS.
^|B |If the returned coverage has a spatial extent, the headers of the response SHALL include a `Content-Bbox:` header with the actual geospatial boundary of the coverage.
^|C |If applicable, the `Content-Bbox:` coordinates SHALL be in the response CRS (indicated in `Content-Crs:`, or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if it is not present) and SHALL contain
four or six comma-separated numbers representing the lower-left and upper right corners of the response honoring the CRS coordinates order.
^|D |If the coverage includes a temporal dimension which can be expressed in RFC3339 format, the headers of the response SHALL include a `Content-Datetime:` header in that format with the actual datetime instant
(if returning a temporal slice) or datetime interval (if the response includes a temporal dimension) of the returned coverage.
|===

==== Query parameter `resolution` (empty values for native resolution)

[[req_core-native-resolution]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/native-resolution*
^|A |An implementation SHALL accept a `resolution` query parameter for a GET operation on the coverage resource,
for empty resolution values (e.g., `resolution=Lat(),Lon(),time()`) indicating a request for the native resolution of the corresponding dimension(s),
whether the implementation supports or not the <<rc_scaling_spatial, "Spatial Scaling">>, <<rc_scaling_spatial, "Temporal Scaling">> and/or <<rc_scaling_spatial, "General Scaling">> requirements classes.
^|B |An implementation not supporting scaling for a dimension for which a non-empty value has been specified using the `resolution` query parameter SHALL return a 4xx error.
|===

NOTE: An implementation not supporting scaling for any dimension (not conforming to any of the scaling requirements classes) can simply ignore the `resolution` query parameter, and return the data at the
native resolution as if the query parameter was not used. The implementation would return an error if the selected subset or the whole coverage requested exceeds the server limits at this native resolution.

IMPORTANT: Clients wishing to ensure they always retrieve a native resolution coverage can include in their coverage data request a `resolution` query parameter specifying all dimensions with empty values:
`resolution=Lat(),Lon(),time()` (including any additional dimension), regardless of whether the server implements any of the Scaling requirements classes. For most large datasets, these clients
would also need to include subsetting parameters (`subset`, `bbox` and/or `datetime`, assuming the server supports the corresponding subsetting requirements classes) to avoid an error response due
to requesting more data than allowed by the server limits.

==== Server limits recommendations

[[rec_core-limits]]
[width="90%",cols="2,6"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/limits*
^|A |The implementation SHOULD advertise maximum limits for individual dimensions and/or combined data size that it is willing to return in a `coverage` object property of
an `x-OGC-limits` property of the service metadata `info` object property of a JSON document linked to from the landing page using the `service-meta` link relation.
^|B |The implementation SHOULD include in this `coverage` property of the service metadata `x-OGC-limits`: `maxWidth`, `maxHeight` and `maxCells` integer properties for
implementations supporting gridded coverages, and/or a `maxPoints` integer property for implementations supporting point clouds coverages.
^|C |The implementation SHOULD return a 4xx error (e.g., 400 Generic client error, or 413 Content too large) for coverage requests exceeding any of those limits.
|===

NOTE: An example of service metadata is provided in https://docs.ogc.org/is/19-072/19-072.html#service-metadata-examples[_OGC API – Common – Part 1: Core_].
The service metadata might be embedded directly within an OpenAPI API definition, meaning that the `service-meta` and `service-desc` links may point to the same JSON document.
