[[rc_sparse-dimensions-collapse-temporal-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/sparse-dimensions-collapse-temporal
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/subsetting-temporal
|===

=== Requirements

==== Requirement for Slicing Sparse Dimensions

[[req_sparse-dimensions-collapse-temporal_slice-sparse-dimension]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sparse-dimensions-collapse-temporal/slice-sparse-dimension*
^|A |For a slicing operation on the temporal dimension combined with a trimming operation on other axes
(such as latitude and longitude), the Implementation SHALL fill empty portions (NODATA) with data values from other
nearby non-empty values along the temporal dimension.
For example, the closest or last previous time for which data is available for a certain geospatial extent may be returned.
An Earth Observation use case for this permission is to allow retrieving a slice of the last available imagery on or before a
certain date, taking into account that a certain geographic area may only be observed every few days.
|===

IMPORTANT: Slicing (a `subset` specifying a single value for a particular dimension) is mutually exclusive with scaling on that same dimension
(using the `resolution` query parameter as defined in the relevant Scaling requirements class) as per <<subset-temporal-parameter-subset-requirements>>.

NOTE: Clients wishing to avoid this filling behavior can specify a request header such as
`Prefer: interpolation=time([ogc-interpolation:none]),
which most Implementations of this requirements class would support as per the
<<rec_sparse-dimensions-collapse-temporal_slice-prefer-header, recommendation for interpolation preferences>>.

===== Example slicing sparse dimensions

In this example, a client requests a bounding box for (40 N, 30 E)-(70 N, 50 E), while slicing a date:

`datetime=2025-01-01&f=application/x-netcdf&bbox=30,40,50,70`.

Because the primary temporal dimension is sparse due to some satellites only covering some of the Earth's surface on a given day, data is not available for that specific date for some of the
spatial region covered. In this case, the server can use data from a nearby date to fill those regions.

==== Requirement for Flattening Sparse Dimensions

[[req_sparse-dimensions-collapse-temporal_flattening-sparse-dimension]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sparse-dimensions-collapse-temporal/flattening-sparse-dimension*
^|A |For a trimming operation on the temporal dimension combined with a trimming operation on other axes
(such as latitude and longitude), requested for a format which does not support including a temporal dimension in the response,
the Implementation SHALL flatten the resulting coverage, collapsing the temporal dimension while preserving non-empty portions
based on a default or selected <<conventions-interpolation-methods, interpolation method>> preference.
For example, requesting a 2D image in PNG for a specific time interval from a spatiotemporal 3D coverage.
|===

===== Example flattening sparse dimensions

In this example, a trim operation is performed, but because the PNG format is inherently 2D, it implies a "flattening" of the
response such that this permission applies:

[source,http]
----
GET /collections/sentinel2-l2a/coverage?datetime=2025-01-01/2025-01-31&bbox=30,40,50,70
Accept: image/png
----

The server can then perform a mosaic of the month of January with the most recent images displayed on top.

==== Recommendation for default interpolation method

[[rec_sparse-dimensions-collapse-temporal_slice-default-interpolation]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/sparse-dimensions-collapse-temporal/slice-default-interpolation*
^|A | For the purpose of slicing or flattening sparse dimensions, the default
<<conventions-interpolation-methods, interpolation method>> used
SHOULD be either `[ogc-interpolation:previous]` or `[ogc-interpolation:nearest-neighbor]`.
|===

==== Recommendation for interpolation preference

[[rec_sparse-dimensions-collapse-temporal_slice-prefer-header]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/sparse-dimensions-collapse-temporal/slice-prefer-header*
^|A |The Implementation SHOULD understand a `Prefer:` request header
(as defined in https://datatracker.ietf.org/doc/html/rfc7240[RFC 7240]) value provided by the client hinting at the preferred
<<conventions-interpolation-methods, interpolation method>>.
^|B |The implementation SHOULD support an `interpolation=` value for that `Prefer:` header selecting one specific interpolation method using a safe CURIEs or URI, such as from the OGC
definition server (https://www.opengis.net/def/interpolation/OGC/1), for specific dimensions being sliced. Example: `Prefer: interpolation=time([ogc-interpolation:linear])`
^|C |The implementation SHOULD support a `properties-interpolation=` value for that `Prefer:` header selecting one specific interpolation method for specifics field being returned,
which will override interpolation methods specified in any `interpolation` preference for any dimension, using a safe CURIEs or URI, such as from the OGC
definition server (https://www.opengis.net/def/interpolation/OGC/1). Example: `Prefer: properties-interpolation=landCover([ogc-interpolation:nearest-neighbor])`.
^|D |The implementation SHOULD also support in the context of that `properties-interpolation=` value the selection of an interpolation method for a specific
field and dimension, which will override interpolation for that field only for that dimension, using the `dimension:URI` syntax inside the parentheses, for example:
`Prefer: properties-interpolation=landCover(time:[ogc-interpolation:nearest-neighbor])`.
^a|E | The implementation SHOULD consider supporting the following interpolations methods, with the following meaning in the context of the slicing and flattening sparse dimensions requirements:

- `[ogc-interpolation:next]`: Use the next available data point from the sliced dimension,
- `[ogc-interpolation:previous]`: Use the previous available data point from the sliced dimension,
- `[ogc-interpolation:nearest-neighbor]`: Use the nearest data point from the sliced dimension,
- `[ogc-interpolation:linear]`: Perform a linear interpolation between the previous and next available data point from the sliced dimension,
- `[ogc-interpolation:quadratic]`: Perform a quadratic interpolation among data points around the slicing point along the dimension,
- `[ogc-interpolation:cubic]`: Perform a cubic interpolation among data points around the slicing point along the dimension,
- `[ogc-interpolation:none]`: Only return a value if the sliced dimension corresponds exactly to an available data point, return NODATA otherwise (hit or miss)
|===

==== Requirement for indicating a preference has been applied

[[req_sparse-dimensions-collapse-temporal_slice-preference-applied]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sparse-dimensions-collapse-temporal/slice-preference-applied*
^|A | If an Implementation supports <<req_sparse-dimensions-collapse-temporal_slice-prefer-header, client preferences for interpolation>>,
the Implementation SHALL use a response header `Preference-Applied:` when it applied the preference specified by the client, for example,
`Preference-Applied: interpolation=time([ogc-interpolation:linear])` and `Preference-Applied: properties-interpolation=landcover([ogc-interpolation:nearest-neighbor])`.
|===

==== Requirement for strict or lenient preference handling

[[req_sparse-dimensions-collapse-temporal_slice-preference-handling]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sparse-dimensions-collapse-temporal/slice-preference-handling*
^|A | If an Implementation supports <<req_sparse-dimensions-collapse-temporal_slice-prefer-header, client preferences for interpolation>>,
the Implementation SHALL support the `Prefer: handling` parameter defined in https://www.rfc-editor.org/rfc/rfc7240#section-4.4[RFC 7240 Section 4.4] where a value of `handling=lenient` would simply ignore an unsupported preference, while a
value of `handling=strict` SHALL return a 4xx error if the server is not able to fulfill the preference of the client
(note that the handling parameter applies to the request as a whole, rather than to any specific preference).
^|B | If no handling preference is specified, the Implementation SHALL default to lenient handling for the purpose of
interpolation preferences.
|===
