[[rc_geotiff]]

[requirements_class]
.GeoTIFF
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/geotiff
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
inherit:: https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf
inherit:: https://docs.ogc.org/is/19-008r4/19-008r4.html
requirement:: /req/geotiff/coverage
requirement:: /req/geotiff/raster-type
====

// [[GeoTIFF]] OGC 19-008: *OGC GeoTIFF Standard*, Version 1.1, http://docs.opengeospatial.org/is/19-008r4/19-008r4.html
// [[[TIFF_V6,TIFF V6.0]]], Adobe Developers Association: TIFF Specification Revision 6.0. (1992) https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf[https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf]

==== Requirements

[[requirements-class-geotiff-clause]]

===== GeoTIFF representation

[[req_geotiff_coverage]]
[requirement]
====
[%metadata]
identifier:: /req/geotiff/coverage
part:: Two-dimensional coverage responses for the coverage resource as defined in the Coverages API Core requirements class SHALL support negotiating a https://docs.ogc.org/is/19-008r4/19-008r4.html[GeoTIFF] response using the `image/tiff; application=geotiff` media type.
part:: The response SHALL be a GeoTIFF document which validates against the GeoTIFF and TIFF standard.
part:: If the response contains multiple fields, the fields SHALL be encoded as bands ordered following the `x-ogc-propertySeq` sequence.
====

[[req_geotiff_raster_type]]
[requirement]
====
[%metadata]
identifier:: /req/geotiff/raster-type
part:: If the bounds of the coverage response's <<term-grid-cell,grid cells>> are defined as the entire area between <<term-grid,grid>> lines, the GeoTIFF coverage response SHALL include a `GTRasterTypeGeoKey` (Tag 1025) with a value set to `RasterPixelIsArea` (1).
part:: If the bounds of the coverage response's <<term-grid-cell,grid cells>> are defined as a zero-dimensional point at the intersections of grid lines, the GeoTIFF coverage response SHALL include a `GTRasterTypeGeoKey` (Tag 1025) with a value set to `RasterPixelIsPoint` (2).
====

NOTE: If the server uses a GeoTIFF as its native backing store, the `GTRasterTypeGeoKey` configuration is to be used to inform which <<term-cell,cells>>
are extracted during <<term-subsetting,subsetting>> operations, and that key is to be preserved and propagated in the resulting response.

[[rec_geotiff_nodata]]
[recommendation]
====
[%metadata]
identifier:: /rec/geotiff/nodata
part:: Where applicable, regions of no data in the coverage SHOULD be represented using a single no data value (shared by all fields / bands), identified with the `GDAL_NODATA` TIFF tag (42113).
part:: For imagery data where pure black is not necessary for the image itself, a no data value of 0 SHOULD be used (using only the existing RGB channels).
part:: For RGB imagery data where pure black should be preserved, a separate alpha channel SHOULD be used to encode the lack of data, with values either at full opacity or full translucency,
except for anti-aliasing along the edges between both.
====

===== GeoTIFF query parameters

[[rec_geotiff_compression]]
[recommendation]
====
[%metadata]
identifier:: /rec/geotiff/compression
part:: The coverage resource SHOULD support a `compression` query parameter.
part:: The possible values for the `compression` parameter SHOULD be `none`, `packbits`, `huffman`, `lzw`, `deflate`.
part:: The GeoTIFF coverage response SHOULD use the compression method specified.
====

[[rec_geotiff_predictor]]
[recommendation]
====
[%metadata]
identifier:: /rec/geotiff/predictor
part:: The coverage resource SHOULD support a `predictor` query parameter.
part:: The possible values for the `compression` parameter SHOULD be `none`, `horizontal`, `floating-point`.
part:: The GeoTIFF coverage response SHOULD use the predictor specified.
====

[[rec_geotiff_interleave]]
[recommendation]
====
[%metadata]
identifier:: /rec/geotiff/interleave
part:: The coverage resource SHOULD support a `interleave` query parameter.
part:: The possible values for the `interleave` parameter SHOULD be `pixel` (PlanarConfiguration value 1 for chunky, PLANARCONFIG_CONTIG in libtiff) and `band`
(PlanarConfiguration value 2 for planar configuration, PLANARCONFIG_SEPARATE in libtiff).
part:: The GeoTIFF coverage response SHOULD use the interleave setting specified (corresponding to the PlanarConfiguration in TIFF terminology).
====

[[rec_geotiff_tiling]]
[recommendation]
====
[%metadata]
identifier:: /rec/geotiff/tiling
part:: The coverage resource SHOULD support a boolean `tiling` query parameter.
part:: The GeoTIFF coverage response SHOULD use tiling if `tiling` is true, or strips otherwise.
====

[[rec_geotiff_tile-height-width]]
[recommendation]
====
[%metadata]
identifier:: /rec/geotiff/tile-width-height
part:: The coverage resource SHOULD support integer multiple of 16 `tile-width` and `tile-height` query parameters when a `tiling` parameter is used.
part:: An implementation SHOULD return an error if these parameters are provided without a `tiling` parameter, or if their value is not a multiple of 16 greater than 0.
part:: The GeoTIFF coverage response SHOULD use these tile width and tile height (TileLength in TIFF terminology).
====

[[rec_geotiff_overview-count]]
[recommendation]
====
[%metadata]
identifier:: /rec/geotiff/overview-count
part:: The coverage resource SHOULD support an integer `overview-count` query parameter.
part:: An implementation SHOULD return an error if this parameter is smaller than 0.
part:: The GeoTIFF coverage response SHOULD generate progressively smaller overviews based on that requested number of overviews.
====

NOTE: Clients can use a combination of `tiling`, `tile-width`, `tile-height` and `overview-count` to get a GeoTIFF conforming to the https://docs.ogc.org/is/21-026/21-026.html[OGC Cloud Optimized GeoTIFF] standard (see also <<rc_encoding-cog>>).
