[[rc_png]]

[requirements_class]
.PNG
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/png
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
inherit:: https://www.w3.org/TR/png/
requirement:: /req/png/coverage
====

==== Requirements

[[requirements-class-png-clause]]

===== PNG representation

[[req_png_coverage]]
[requirement]
====
[%metadata]
identifier:: /req/png/coverage
part:: Two-dimensional coverage responses for the coverage resource, as defined in the Coverages API Core requirements class, SHALL support negotiating a https://www.w3.org/TR/png/[PNG] response using the `image/png` media type.
part:: The PNG response SHALL use 16-bit values for fields requiring more than 8-bit to encode accurately.
part:: An implementation SHALL return a 400 error for requests for any number of fields other than 1 or 3.
part:: If the response contains multiple fields, the fields SHALL be encoded as bands ordered following the `x-ogc-propertySeq` sequence.
part:: A `Values-Scale:` response header with a numeric real value SHALL be returned indicating the factor by which values were multiplied before an offset was added to result in the encoded 8-bit or 16-bit PNG unsigned integer values.
part:: A `Values-Offset:` response header with a numeric real value SHALL be returned indicating the offset which was added after multiplying values by the scale factor to result in the encoded 8-bit or 16-bit PNG unsigned integer values.
====

[[rec_png_scale_offset]]
[recommendation]
====
[%metadata]
identifier:: /rec/png/scale-offset
part:: An implementation SHOULD support a `values-scale` query parameter on coverage resources when requesting a PNG output to indicate the value scale factor, as described in the `Values-Scale:` response header part of the content requirement.
part:: An implementation SHOULD support a `values-offset` query parameter on coverage resources when requesting a PNG output to indicate the value offset, as described in the `Values-Offset:` response header part of the content requirement.
====
