[[rc-core-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|Target type   |Web API
|Dependency    |http://www.opengis.net/spec/ogcapi-common-2/1.0/req/collections
|===

=== Requirements

==== Extended collection list response (`/collections`)

[[req_core-collection_list]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collection-list*
^|A |For every collection accessible using the _Coverages API_, the content of the elements of `collections` for the `/collections` resource SHALL include in its `links` array a link to a coverage resource at `/collections/{collectionId}/coverage` using the link relation type `[ogc-rel:coverage]`.
^|B |At least one collection SHALL be accessible as a coverage.
|===

==== Extended collection description response (`/collections/{collectionId}`)

[[req_core-collection_description]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/collection-description*
^|A |For every collection accessible using the _Coverages API_, the collection description resource SHALL include in its `links` array a link to a coverage resource at `/collections/{collectionId}/coverage` using the link relation type `[ogc-rel:coverage]`.
^|B |Each of these collection resources SHALL also include in its `links` array a link to a coverage schema at `/collections/{collectionId}/schema` using the link relation type `[ogc-rel:coverage-schema]`.
^|C |Each of these collection resources SHALL use the uniform additional dimensions schema to describe its domain as part of the `extent` property of that collection.
This implies using an `interval` array property to describe the overall envelope and optionally sub-intervals for sparsely populated data.
The first element of the array is the overall envelope, while any additional elements detail where data is available within that overall interval.
Each of these elements are themselves an array of start and end bound values.
^|D |Each additional dimension SHALL include in a `crs`, `vrs`, or `trs` property a URI or safe CURIE corresponding to the CRS associated with that dimension.
^|E |The name (JSON dictionary key) of each additional dimension SHALL correspond to the axis abbreviation for the CRS of that axis, to valid axis names for use with query parameters defined in optional requirements classes such as `subset` and `scale-axes`, as well as to axis names in the coverage response, if applicable.
^|F |If a particular dimension of the coverage is gridded, the description of that dimension in the extent SHALL describe this grid using the `grid` property, providing a `cellsCount`, as well as a `resolution` for regular grid or a set of `coordinates` for irregular grids.
^|G |For data referenced in relation to planet Earth, the coordinates in the `bbox` of the `spatial` dimensions of the `extent` SHALL be provided either as WGS 84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84[http://www.opengis.net/def/crs/OGC/1.3/CRS84]) or as WGS 84 longitude/latitude/ellipsoidal height (http://www.opengis.net/def/crs/OGC/0/CRS84h[http://www.opengis.net/def/crs/OGC/0/CRS84h]).
^|H |The `storageCRS` property SHALL be set to the native CRS of the coverage, also correspondin to the default output CRS (used when the `crs` parameter is not specified and/or the CRS requirements class is not supported).
|===

NOTE: A schema for this extended collection resource is available at https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/common-geodata/collectionInfo.yaml.

NOTE: A property indicating for which planetary body a CRS is applicable is being considered as part of CRS definitions, which will facilitate validating this requirement.

TODO: Discuss the ability to include a http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] definition and/or
https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/common-geodata/projJSON.yaml[PROJ-JSON] definition of the CRS instead of a URI.

==== Collection schema response (`/collections/{collectionId}/schema`)

[[req_core-coverage_schema]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/coverage-schema*
^|A |The API SHALL support the HTTP GET operation at the path `/collections/{collectionId}/schema` to retrieve the schema of the coverage fields.
^|B |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|C |The content of that response SHALL include a list of the fields for the coverage, including an identifier (the property key), a `title`, a `type` and an optional `description`.
|===

NOTE: A meta-schema for JSON Schema used as part of the _2D Tile Matrix Set and Tileset Metadata standard_ suitable for this resource is available at https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/schemas/tms/propertiesSchema.yaml .
This resource should also match the draft https://github.com/opengeospatial/ogcapi-features/projects/11[_OGC API - Features - Part 5: Schemas_].

==== Coverage data retrieval (`/collections/{collectionId}/coverage`)

[[req_core-get_coverage]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/core/get-coverage*
^|A |The implementation SHALL support the HTTP GET operation at the path `/collections/{collectionId}/coverage` to retrieve the coverage.
^|B |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|C |The content of that response SHALL be the coverage data, along with the suported self-description capabilities of the negotiated content type.
^|D |The response SHALL be encoded using the format(s) negotiated through the HTTP protocol.
^|E |If no format is negotiated, then the response SHALL be encoded using the format associated with the media type described in the link object which links to this resource, contained within the coverage (collection) resource.
|===

[[per_core-cis-metadata]]
[width="90%",cols="2,6"]
|===
^|*Permission {counter:per-id}* |*/per/core/cis-metadata*
^|A |The implementation MAY omit the CIS domain-specific metadata by default as part of the coverage response.
|===
