[[rc_table_scaling_temporal]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/scaling-temporal
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

==== Query parameter `resolution`

[[req_scaling-temporal_resolution]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling-temporal/resolution*
^|A |For data with a temporal aspect, the coverage retrieval operation SHALL support a `resolution` query parameter specifying the resolution for the primary temporal dimension using ISO 8601 period notation
(as well as potentially supporting additional dimensions specified by other requirements classes).
^|B |The server SHALL support as a value for this parameter a comma-separated list of dimensions names followed by a resolution value in parentheses.
^|C |The server SHALL support an empty resolution value as referring to the native resolution for that particular dimension.
^|D |Axis name `time` SHALL be supported if the collection describes a temporal dimension in its extent.
^|E |A 400 error status code SHALL be returned for an axis name other than `time`, an alias for `time`, or any other axis supported in the context of other requirements classes (such as spatial and general scaling).
^|F |For a regularly gridded coverage, the resolution (the distance between two samples along that dimension) for each of the listed dimension(s) SHALL correspond to the specified value.
^|G |For an irregularly gridded coverage, the distance between two samples along each of the listed dimension(s) SHALL be at minimum the value specified as the resolution for the corresponding dimension.
^|H |For a non-gridded coverage, when explicitly listing each dimension, the distance between two samples along each of the listed dimension(s) SHALL be at minimum the value specified as the resolution
for the corresponding dimension.
|===

[[scaling-temporal-interpolation-recommendation]]
==== Recommendation for interpolation guidance

This Core part of the OGC API - Coverages Standard does not require the server to implement a mechanism allowing a client to request a specific interpolation method,
but it does recommend supporting a `Prefer:` request header for the client to indicate a preference.
The following recommendation also provides guidance for implementations such as some important considerations to take into account when performing interpolation.
This guidance applies whether the resampling is performed as a result of the use of the scaling query parameters by the client,
or for automatic resampling in order to avoid returning too much data (as described in the downsampling permission below).

This guidance also applies to interpolation which could also be performed by clients.
Including an accurate description of the domain and range in a coverage response provided by the server allows to select a proper interpolation method.
The collection description and the collection logical schema also provides this information for all fields and dimensions of the coverage,
such as the `x-ogc-variableType` of a particular field, as well as a description of the gridded dimensions,
including the region of validity of individual grid cells where applicable.

[[rec_scaling-temporal-interpolation]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:per-id}* |*/rec/scaling-temporal/interpolation*
^|A | Implementations SHOULD NOT perform interpolation using a method other than _nearest neighbor_ for fields of a variable type other than `continuous`.
^|B | Implementations SHOULD use the best available interpolation method which will not significantly degrade response time or put too much strain on the server resources.
^|C | When interpolating gridded data, implementations SHOULD take into account the region of validity of values for individual grid cells, as identified in `relativeBounds` or `boundsCoordinates` of
the dimension's grid description (within the collection description's `extent`), typically considering the center of that region of validity for interpolation calculations.
When `relativeBounds` (for regular grids) or `boundsCoordinates` (for irregular grids) are omitted,
the coordinates (`firstCoordinate + n * resolution` for regular grids, `coordinates` for irregular grids) are assumed as being centered within the region of validity.
^|D | Implementations SHOULD include in all coverage responses an accurate description of the domain and range of the returned coverage, as well as a description of any interpolation
applied to the source data to produce that output, to the extent that the negotiated output format supports carrying that information.
|===

==== Downsampling permission

[[per_scaling-temporal_downsampling]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/scaling-temporal/downsampling*
^|A |In the case where a response to a request without a `resolution` parameter would be larger than an advertised server limit, an implementation
MAY automatically downsample the coverage to a suitable resolution instead of returning a 4xx client error.
|===

NOTE: A client retrieving a coverage from an implementation advertising support for this "Temporal Scaling" requirements class should explicitly use `resolution=time()` if it wants to ensure
retrieving the coverage in its native temporal resolution and prefers receiving an error instead of a downsampled version of the data.

[[scaling-temporal-parameter-aliases-recommendation]]

==== Recommendation for `time` dimension aliases

For convenience, this Standard recommends that Implementations recognize the different case variation and the shorthand `t` as an alias for the `time` dimension.
Generic clients intended to be interoperable with all Implementations of this Standard should not use these aliases,
but should always use `time` to refer to the primary temporal dimension as specified in the above requirement.

[[rec_scaling-temporal_resolution-temporal-aliases]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/scaling-temporal/resolution-temporal-aliases*
^|A | The axis names `t` (lowercase/uppercase) and `Time` case variation SHOULD be interpreted as aliases for `time` (the primary temporal dimension).
|===

IMPORTANT: To ensure interoperability, clients should always use the prescribed primary temporal axis name (`time`) and not rely on any of the aliases.

==== Recommendation for interpolation preference when scaling temporally

[[rec_scaling-temporal_prefer-header]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/scaling-temporal/prefer-header*
^|A |When supporting scaling on a temporal dimension, the Implementation SHOULD understand a `Prefer:` request header
(as defined in https://datatracker.ietf.org/doc/html/rfc7240[RFC 7240]) value provided by the client hinting at the preferred
<<conventions-interpolation-methods, interpolation method>>.
^|B |The implementation SHOULD support an `interpolation=` value for that `Prefer:` header selecting one specific interpolation method using a safe CURIEs or URI, such as from the OGC
definition server (https://www.opengis.net/def/interpolation/OGC/1), for specific dimensions being scaled. Example: `Prefer: interpolation=time([ogc-interpolation:nearest-neighbor])`
^|C |The implementation SHOULD support a `properties-interpolation=` value for that `Prefer:` header selecting one specific interpolation method using a safe CURIEs or URI, such as from the OGC
definition server (https://www.opengis.net/def/interpolation/OGC/1), for specific fields being returned. Example: `Prefer: properties-interpolation=landCover([ogc-interpolation:nearest-neighbor])`.
^|D |The implementation SHOULD also support in the context of that `properties-interpolation=` value the selection of an interpolation method for a specific
field and dimension, which will override interpolation for that field only for that dimension, using the `dimension:URI` syntax inside the parentheses, for example:
`Prefer: properties-interpolation=temperature(time:[ogc-interpolation:linear])`.
^a|E | The implementation SHOULD consider supporting the following interpolations methods, with the following meaning in the context of the dimension being scaled:

- `[ogc-interpolation:linear]`: Perform a linear interpolation (weighted average) between the values being represented along the scaled dimension,
- `[ogc-interpolation:nearest-neighbor]`: Use the available value nearest to the center within the values being represented along the scaled dimension,
- `[ogc-interpolation:quadratic]`: Perform a quadratic interpolation between the previous and next available data point from the scaled dimension,
- `[ogc-interpolation:mean]`: Use the mean of all values being represented along the scaled dimension,
- `[ogc-interpolation:minimum]`: Use the minimum of all values being represented along the scaled dimension,
- `[ogc-interpolation:maximum]`: Use the maximum of all values being represented along the scaled dimension,
- `[ogc-interpolation:median]`: Use the median of all values being represented along the scaled dimension,
|===

==== Recommendation for default interpolation method when scaling temporally

[[rec_scaling-temporal_default-interpolation]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/scaling-temporal/default-interpolation*
^|A | The implementation SHOULD default to a weighted interpolation method,
such as `[ogc-interpolation:linear]` or `[ogc-interpolation:quadratic]`,
when no preference is specified by the client for fields with a variable
type `continuous`, and `[ogc-interpolation:nearest-neighbor]` otherwise.
|===

==== Requirement for indicating a preference has been applied when scaling temporally

[[req_scaling-temporal_preference-applied]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling-temporal/preference-applied*
^|A | If an Implementation supports <<rec_scaling-temporal_prefer-header, client preferences for interpolation>>,
the implementation SHALL use a response header `Preference-Applied:` when it applied the preference specified by the client, for example,
`Preference-Applied: interpolation=time([ogc-interpolation:linear])` and `Preference-Applied: properties-interpolation=landcover([ogc-interpolation:nearest-neighbor])`.
|===

==== Requirement for strict or lenient preference handling when scaling temporally

[[req_scaling-temporal_preference-handling]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling-temporal/preference-handling*
^|A | If an Implementation supports <<rec_scaling-temporal_prefer-header, client preferences for interpolation>>,
the Implementation SHALL support the `Prefer: handling` parameter defined in https://www.rfc-editor.org/rfc/rfc7240#section-4.4[RFC 7249 Section 4.4] where a value of `handling=lenient` would simply ignore an unsupported preference, while a
value of `handling=strict` SHALL return a 4xx error if the server is not able to fulfill the preference of the client
(note that the handling parameter applies to the request as a whole, rather than to any specific preference).
^|B | If no handling preference is specified, the Implementation SHALL default to lenient handling for the purpose of
interpolation preferences.
|===

==== Permission to only support certain resolutions

[[per_scaling-temporal_specific-resolutions]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/scaling-temporal/specific-resolutions*
^|A |Implementations MAY support only specific resolutions listed in the `availableResolutions` sub-property of the `grid` property
(as defined in the https://docs.ogc.org/DRAFTS/20-024.html#rc-uad-collections-section[Uniform Additional Dimensions of OGC API - Common - Part 2])
of the dimension being scaled (any resolution is considered available if the sub-property is missing).
The units of each resolution are the units of the Temporal Reference System (`trs`), just like the `resolution` sub-property.
^|B |When `availableResolutions` is not present, implementations MAY return a 4xx error for a requested resolution more detailed than the native `resolution` declared for the dimension.
^|C |When `availableResolutions` is present, Implementations MAY return a 4xx client error for a requested resolution not matching (within some rounding error tolerance) any listed available resolution.
|===

NOTE: A common use case for the Scaling requirements classes is the ability for clients to request downsampled (coarser resolution)
data compared to the native resolution. For the purpose of upsampling finer than the native resolution using, for example, a linear
or cubic interpolation, it is usually more efficient to perform this upsampling client-side, saving both bandwidth and server
processing resources. The server is therefore allowed to reject requests for data upsampled beyond the native resolution,
or beyond a certain scaling factor past the native resolution. However, for some use cases, support for data upsampling server-side
might make sense, for example when this upsampling capability implies downscaling a subset of the data available with a
climate forecast model using computational fluid dynamics.

Example of specific temporal resolutions available (using ISO-8601 periods for the Gregorian Calendar / UTC default here):

[source,json]
----
   "temporal":
   {
      "interval" : [ [ "2025-01-01T00:00:00Z", "2025-12-31T23:00:00Z" ] ],
      "grid": { "cellsCount": 8760, "resolution": "P1H", "availableResolutions" : [ "P1H", "P1D", "P1M" ] }
   },
----

==== Permission to support legacy scaling query parameters

[[per_scaling-temporal_legacy]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/scaling-temporal/legacy*
^|A |Implementations MAY additionally support the `scale-factor` and `scale-axes` legacy query parameters expressing resolution as the factor by which the data's native resolution has been downsampled (a factor of 2 meaning two times coarser).
^|B |Implementations MAY additionally support the `scale-size` legacy query parameter expressing the number of samples expected in the output for each dimension.
|===

IMPORTANT: To ensure interoperability, clients should use the `resolution` query parameter rather than the legacy ones.
