[[rc-subset-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/coverage-subset
|Target type |Web API
|Dependency |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/geodata-coverage
|Dependency |<<CIS_1_1,OGC Coverage Implementation Schema (CIS)>>
|===

=== Requirements

==== Parameters

The OGC API - Common - Part 2: Geospatial Data Standard identifies query parameters that have been standardized for use in OGC API standards. This Requirements Class defines how three of those parameters are used to create subsets of a hosted CIS Coverage.

* <<bbox-parameter-subset-requirements,bbox>>: Bounding Box
* <<datetime-parameter-subset-requirements,datetime>>: Date and Time
* <<subset-parameter-subset-requirements,subset>>: Subset

The behavior generated by these parameters is specific to the operation and resource upon which they are applied. The behaviors specific to the `Coverage Subset` Requirements Class are defined in the <<subset-target-resource-requirements,Target Resource Requirements>> section.

The use of these parameters should be documented in the API definition.

[[rec-coverage-subset-parameter-documentation]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:Rec-id}* |*/rec/coverage-subset/parameter-documentation*
^|A |Implementers of the `coverage-subset` Requirements Class should document their supported parameters in the API definition as describe in file:///C:/Workspace/GitHub/oapi_common/collections/20-024.html#apicore[API-Core].
|===

[[bbox-parameter-subset-requirements]]
==== Parameter `bbox`

[[rm_bbox]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Module*
2+|http://www.opengis.net/spec/ogcapi-common-2/1.0/rm/bbox
|Target type |Web API Query Parameter
|===

The `bbox` parameter is used to select resources based on the geospatial footprint or extent.

The `bbox` parameter is defined as follows:

[[req_collections_rc-bbox-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/collections/rc-bbox-definition* 
^|A|The `bbox` parameter SHALL possess the following characteristics (using an OpenAPI Specification 3.0 fragment):

[source,YAML]
----
name: bbox
in: query
required: false
schema:
  type: array
  oneOf:
  - minItems: 4
    maxItems: 4
  - minItems: 6
    maxItems: 6
  items:
    type: number
style: form
explode: false
----

^|B|The bounding box SHALL be provided as four or six numbers, depending on whether the coordinate reference system includes a vertical axis (height or depth):

* Lower left corner, coordinate axis 1
* Lower left corner, coordinate axis 2
* Minimum value, coordinate axis 3 (optional)
* Upper right corner, coordinate axis 1
* Upper right corner, coordinate axis 2
* Maximum value, coordinate axis 3 (optional)

^|C|If the bounding box consists of four numbers, the coordinate reference system of the values SHALL be interpreted as WGS 84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate reference system is specified in a parameter `bbox-crs`.
^|D|If the bounding box consists of six numbers, the coordinate reference system of the values SHALL be interpreted as WGS 84 longitude/latitude/ellipsoidal height (http://www.opengis.net/def/crs/OGC/0/CRS84h) unless a different coordinate reference system is specified in a parameter `bbox-crs`.
|===


While the processing of the `bbox` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

[[req_collections_rc-bbox-response]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/collections/rc-bbox-response*
^|A|If the ``bbox`` parameter is provided by the client and supported by the server, then only resources that have a spatial geometry that intersects the bounding box SHALL be part of the result set.
^|B|If a resource has multiple spatial geometry properties, it is the decision of the server whether only a single spatial geometry property is used to determine the extent or all relevant geometries.
^|C|The `bbox` parameter SHALL also match all resources in the collection that are not associated with a spatial geometry.
|===


"Intersects" means that a coordinate that is part of the spatial geometry of the resource falls within the area specified in the parameter `bbox`. This includes the boundaries of the geometries. For curves the boundary includes the start and end position. For surfaces the boundary includes the outer and inner rings.

In case of a degenerate bounding box, the resulting geometry is used. For example, if the lower left corner is the same as the upper right corner, all resources match where the geometry intersects with this point.

This standard does not specify requirements for the parameter `bbox-crs`. Those requirements will be specified in a later version of this standard.

The bounding box for WGS 84 longitude/latitude is, in most cases, the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the box spans the anti-meridian (180th meridian) the first value (west-most box edge) is larger than the third value (east-most box edge).

.The bounding box of the New Zealand Exclusive Economic Zone
=================
The bounding box of the New Zealand Exclusive Economic Zone in WGS84 (from 160.6째E to 170째W and from 55.95째S to 25.89째S) would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89`.
=================

Note that the server will return an error if a latitude value of ``160.0`` is used.

If the vertical axis is included, the third and the sixth number are the bottom and the top of the 3-dimensional bounding box.

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/parameters/bbox.yaml[bbox.yaml].

[[datetime-parameter-subset-requirements]]
==== Parameter `datetime`

[[rm_datetime]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Module*
2+|http://www.opengis.net/spec/ogcapi-common-2/1.0/rm/datetime
|Target type |Web API Query Parameter
|===

The `datetime` parameter selects resources based on their temporal extent. The definition of temporal extent is specific to the resource type being filtered.

The `datetime` parameter is defined as follows:

[[req_collections_rc-datetime-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/collections/rc-datetime-definition* 
^|A |The `datetime` parameter SHALL have the following characteristics (using an OpenAPI Specification 3.0 fragment):

[source,YAML]
----
name: datetime
in: query
required: false
schema:
  type: string
style: form
explode: false
----

^|B |Temporal geometries are either a date-time value or a time interval. The parameter value SHALL conform to the following syntax (using link:https://tools.ietf.org/html/rfc5234[ABNF]):

[source]
----
interval-closed     = date-time "/" date-time
interval-open-start = [".."] "/" date-time
interval-open-end   = date-time "/" [".."]
interval            = interval-closed / interval-open-start / interval-open-end
datetime            = date-time / interval
----
^|C |The syntax of `date-time` is specified by link:https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339, 5.6].
^|D |Open ranges in time intervals at the start or end are supported using a double-dot (`..`) or an empty string for the start/end..
|===

While the processing of the `datetime` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

[[req_collections_rc-datetime-response]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/collections/rc-datetime-response* 
^|A |If the `datetime` parameter is provided by the client and supported by the server, then only resources that have a temporal geometry that intersects the temporal information in the `datetime` parameter SHALL be part of the result set. If a resource has multiple temporal properties, it is the decision of the server whether only a single temporal property is used to determine the extent or all relevant temporal properties.
^|B |The ``datetime`` parameter SHALL match all resources in the collection that are not associated with a temporal geometry.
|===

"Intersects" means that the time (instant or period) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the resource (again, a time instant or period). For time periods this includes the start and end time.

[width="90%",cols="2,6a"]
|====
| Note | ISO 8601-2 distinguishes open start/end timestamps (double-dot) and unknown start/end timestamps (empty string). For queries, an unknown start/end has the same effect as an open start/end.
|====

.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`datetime=2018-02-12T23%3A20%3A52Z`
=================

For resources with a temporal property that is a timestamp (like `lastUpdate`), a date-time value would match all resources where the temporal property is identical.

For resources with a temporal property that is a date or a time interval, a date-time value would match all resources where the timestamp is on that day or within the time interval.

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z`
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/parameters/datetime.yaml[datetime.yaml].


[[subset-parameter-subset-requirements]]
==== Parameter `subset`

[cols="1,4",width="90%"]
|===
2+|*Requirements Module*
2+|http://www.opengis.net/spec/ogcapi-common-2/1.0/rm/subset
|Target type |Web API Query Parameter
|===

The `subset` parameter is used to select a subset of a geospatial resource.

The `subset` parameter is defined as follows:

[[req_coverage_subset-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-subset/definition*
^|A |The operation SHALL support a parameter `subset` with the following characteristics (using an Extended Backus Naur Form (EBNF) fragment):

[source,EBNF]
----
  SubsetSpec:       "subset"=axisName(intervalOrPoint)
  axisName:         {text}
  intervalOrPoint:  interval \| point
  interval:         low : high
  low:              point \| *
  high:             point \| *
  point:            {number} \| "{text}"

  Where:
     \" = double quote = ASCII code 0x42,
     {number} is an integer or floating-point number, and
     {text} is some general ASCII text (such as a time and date notation in ISO 8601).
----
^|B |The axis name SHALL correspond to one of the axis of the Coordinate Reference System (CRS) of the target resource or else return a 400 status code.
^|C |If the intervalOrPoint values fall entirely outside the range of valid values defined for the identified axis, a 204 status code SHALL be returned
^|D |For a CRS where an axis can wrap around, such as subsetting across the dateline (anti-meridian) in a geographic CRS, a `low` value greater than `high` SHALL
be supported to indicate an extent crossing that wrapping point.
|===

NOTE: When the intervalOrPoint values fall partially outside of the range of valid values defined by the CRS for the identified axis,
the service is expected to return the non-empty portion of the coverage resulting from the subset.
For subsetting on the range set, and for coverage media types with no geo-referencing mechanisms (e.g. PNG), NO_DATA values or transparency should be used.
If a georeferencing mechanism is available within the negotiated media type, the service could decide whether to use NO_DATA values
or simply return the properly geo-referenced values within the domain set.

While the processing of the `subset` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

[[req_coverage_subset-subset-response]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-subset/subset-response*
^|A |Only that part of the resource that falls within the bounds of the subset expression SHALL be returned.
^|B |If an lower limit of the subset expression is populated with an asterix "*" THEN the mainumum extent of the resource along that axis SHALL be selected.
^|C |If an upper limit of the subset expression is populated with an asterix "*" THEN the maximum extent of the resource along that axis SHALL be selected.
|===

==== Permission for Slicing Sparse Dimensions

[[per_slice_sparse_dimension]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/coverage-subset/slice-sparse-dimension*
^|A |The empty portions in a coverage resulting from a slice operation on an axis (e.g. time), combined with a trimming operations on other axes (e.g. latitude and longitude)
 which would either be empty or not cover the full extent of the trim operation MAY be filled with data values from the same trim operation
 combined with a slicing operation on a different value of the slicing axis which would return non-empty values.
 For example, the closest or last previous time for which data is available for a certain geospatial extent may be returned.
 An Earth Observation use case for this permission is to allow retrieving a slice of the last available imagery on or before a certain date,
 taking into account that a certain geographic area may only be observed every few days.
^|B |This permission applies to both explicit slice operations using subset, as well as to implicit slicing from requesting an output format only supporting
 a lower dimensionality than the data (e.g. requesting a 2D image from a 3D coverage as PNG or GeoTIFF).
^|C |A query parameter defined by a custom or standardized extension MAY be made available to enable, disable or alter that behavior.
|===

////
[[subset-target-resource-requirements]]
==== Target resource Requirements

The target of the parameters defined in this Requirements Class is a CIS Coverage. The purpose of these parameters is to extract a subset of the <<coverage-clause,Coverage>> resource to be returned in the response to a <<coverage-clause,/coverage>> request.

===== General Requirements

The payload shall be either a CIS document encoded per (encoding vs schema chart) or a reference to such a document.

NOTE: Is this a new coverage? Should we return the coverage ID rather than coverage itself?

NOTE: Can a service truncate the return if it is too big?  How should this truncation be done and what is returned to the user.

* Consider returing a URI instead of the content if the content is too large.
* Or - return a reduced resolution coverage with a URI to the full resolution response

NOTE: What are the error conditions and corresponding status codes?

===== Domain Subsetting

Strategy: select the domainset for this coverage then send it to domainset subsetting to process.

===== Metadata Subsetting

Strategy: Update the UAD_Extent to reflect the new domainset. Make any modifications to the CIS metadata (which is undifined) to bring it in line with the new coverage.

===== RangeType Subsetting

No changes to the range type are required.

===== RangeSet Subsetting

This should be done, but may not be possible in all cases.

===== Building the Response

What requirements (if any) are applicable to building a response from the pieces generated above?
////

==== Subsetting Examples

See also <<subsetting-examples, examples of subsetting requests>> in an annex.
