[[rc_subsetting-general-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/subsetting-general
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

[[subset-general-parameter-subset-requirements]]
==== Parameter `subset`

[[req_coverage_subset_general-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting-general/subset*
^|A |The coverage request operation SHALL support a parameter `subset` to subset one or more of the dimensions of the coverage (as described in the collection information)
with the following characteristics (using an Extended Backus Naur Form (EBNF) fragment):

[source,EBNF]
----
  SubsetSpec:       "subset"=axisName(intervalOrPoint)
  axisName:         {text}
  intervalOrPoint:  interval \| point
  interval:         low : high
  low:              point \| *
  high:             point \| *
  point:            {number} \| "{text}"

  Where:
     \" = double quote = ASCII code 0x42,
     {number} is an integer or floating-point number, and
     {text} is some general ASCII text (such as a time and date notation in ISO 8601).
----

^|B   |Only that part of the coverage that falls within the bounds of the subset expression SHALL be returned.
^|C   |If a single point is provided for an axis, the coverage response SHALL be the result of a slicing operation for the dimension corresponding to that axis, reducing the dimension.
^|D   |If an interval is provided for an axis, the coverage response SHALL be the result of a trimming operation for the dimension corresponding to that axis, preserving the dimension.
^|E	|Any name of the additional dimensions in the extent of the collection SHALL be supported as axis name.
^|F	|A 400 error status code SHALL be returned if an axis name in the subset parameter value does not correspond to an additional dimension described in the collection extent, or to any other axis supported in the context of other requirements classes (such as spatial and general subsetting).
^|G	|If the _intervalOrPoint_ values fall entirely outside the range of valid values defined for the identified axis, a 204 or 404 status code SHALL be returned.
^|H   |If a lower limit of the subset interval is populated with an asterisk `*`, then the minimum extent of the coverage along that axis SHALL be selected.
^|I   |If a upper limit of the subset interval is populated with an asterisk `*`, then the maximum extent of the coverage along that axis SHALL be selected.
^|J	|Multiple subset parameters SHALL be interpreted, as if all dimension subsetting values were provided in a single subset parameter (comma separated)^1^.

2+|1 Example: subset=Lat(-90:90)&subset=Lon(-180:180)&subset=time("2018-02-12T23:20:52Z")&subset=atm_pressure_hpa(500) is equivalent to subset=Lat(-90:90),Lon(-180:180),time("2018-02-12T23:20:52Z"),atm_pressure_hpa(500)
2 Note that this is only valid of the spatial dimensions. The ‘additional’ dimensions rely on the names of the extent of the collection.
|===

NOTE: When the _intervalOrPoint_ values fall partially outside of the range of valid values defined by the CRS for the identified axis,
the service is expected to return the non-empty portion of the coverage resulting from the subset.
For subsetting on the range set, and for coverage media types with no geo-referencing mechanisms (e.g. PNG), NO_DATA values or transparency should be used.
If a georeferencing mechanism is available within the negotiated media type, the service could decide whether to use NO_DATA values
or simply return the properly geo-referenced values within the domain set.

==== Permission for Slicing Sparse Dimensions

[[per_slice_sparse_dimension_general]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/subsetting-general/slice-sparse-dimension*
^|A |The empty portions in a coverage resulting from a slice operation on an axis (e.g. time), combined with a trimming operations on other axes (e.g. latitude and longitude)
 which would either be empty or not cover the full extent of the trim operation MAY be filled with data values from the same trim operation
 combined with a slicing operation on a different value of the slicing axis which would return non-empty values.
 For example, the closest or last previous time for which data is available for a certain geospatial extent may be returned.
 An Earth Observation use case for this permission is to allow retrieving a slice of the last available imagery on or before a certain date,
 taking into account that a certain geographic area may only be observed every few days.
^|B |This permission applies to both explicit slice operations using subset, as well as to implicit slicing from requesting an output format only supporting
 a lower dimensionality than the data (e.g. requesting a 2D image from a 3D coverage as PNG or GeoTIFF).
^|C |A query parameter defined by a custom or standardized extension MAY be made available to enable, disable or alter that behavior.
|===
