[[rc_netcdf]]

[requirements_class]
.netCDF
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/netcdf
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
inherit:: https://docs.ogc.org/is/10-090r3/10-090r3.pdf[OGC 10-090r3 Network Common Data Form Core Encoding Standard 1.0]
requirement:: /req/netcdf/coverage
====

==== Requirements

[[requirements-class-netCDF-clause]]

===== netCDF representation

[[req_netcdf_coverage]]
[requirement]
====
[%metadata]
identifier:: /req/netcdf/coverage
part:: The coverage resource as defined in the Coverages API Core requirements class SHALL support negotiating a https://docs.ogc.org/is/10-090r3/10-090r3.pdf[netCDF] response using the `application/x-netcdf` media type.
part:: The response SHALL be a netCDF document which validates against the OGC netCDF standard.
part:: For dimensions that do not have a well-defined netCDF `standard_name`, the name of the corresponding variable SHALL match the name of the dimension in the collection description's extent.
====

NOTE: The https://docs.ogc.org/is/11-038r2/11-038r2.pdf[OGC netCDF Enhanced Data Model Extension] can be fully encoded using the
https://docs.ogc.org/is/18-043r3/18-043r3.html[OGC Hierarchical Data Format Version 5 (HDF5®) Standard].

[[rec_netcdf_profile-handling]]
[recommendation]
====
[%metadata]
identifier:: /rec/scaling-general/netcdf-profile-handling
part:: An implementation SHOULD support negotiating a specific netCDF profile version using HTTP headers `Accept-Profile:` / `Content-Profile:` values,
and/or via a `profile` query parameter for coverage retrieval requests, supporting:
* `https://www.opengis.net/def/profile/ogc/0/netcdf3` or `netcdf3` for classic netCDF 3 and 64-bit offset format.
* `https://www.opengis.net/def/profile/ogc/0/netcdf4` or `netcdf4` for netCDF 4 format based on the OGC HDF5 standard.
part:: An implementation SHOULD return a link to the default or selected profile as a `Link` HTTP response header, for example `Link: <https://www.opengis.net/def/profile/ogc/0/netcdf4>; rel="profile"`.
====
