[[rc_subsetting-temporal-table]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/subsetting-temporal
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

[[subset-temporal-parameter-subset-requirements]]
==== Query parameter `subset`

The `subset` parameter allows to retrieve a temporal subset of a coverage by slicing or trimming the primary temporal dimension named `time`.
If this primary temporal dimension can be mapped to UTC and the Gregorian calendar, then the server needs to support RFC 3339 notation.
Implementations may also allow clients to omit any time components such as seconds, minutes, hours.
If this primary temporal dimension cannot be mapped to UTC / Gregorian calendar (e.g., geological time), then the collection description temporal property would specify a different `trs` defining the valid input.

When performing a slice operation, the slicing temporal instant value is assumed to have no thickness.
When performing a trimming operation (specifying two temporal instants), the starting (first) temporal instant is taken exactly as-is with any omitted time components assumed to be 0,
whereas the ending (second) temporal instant is assumed to extend until the very end of that time component.
For example, `subset=time("2020-01-01")` is equivalent to `subset=time("2020-01-01T00:00:00.000Z")`, whereas `subset=time("2020-01-01":"2020-01-31")` is equivalent to
`subset=time("2020-01-01T00:00:00.000Z":"2020-01-31T23:59:59.999Z")`.

[[req_subsetting-temporal_subset]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting-temporal/subset*
^|A |The coverage request operation SHALL support a parameter `subset` to subset the primary temporal dimension of the coverage (corresponding to the `temporal` section of the collection description's extent)
with the following characteristics (using an Extended Backus Naur Form (EBNF) fragment):

[source,EBNF]
----
  SubsetSpec:       "subset"=axisName(intervalOrPoint)
  axisName:         {text}
  intervalOrPoint:  interval \| point
  interval:         low : high
  low:              point \| *
  high:             point \| *
  point:            {number} \| "{text}"

  Where:
     \" = double quote = ASCII code 0x42,
     {number} is an integer or floating-point number, and
     {text} is some general ASCII text (such as a time and date notation in ISO 8601).
----

^|B |Only that part of the coverage that falls within the bounds of the subset expression SHALL be returned.
^|C |If a single point is provided for an axis, the coverage response SHALL be the result of a slicing operation for the dimension corresponding to that axis, reducing the dimension.
^|D |If an interval is provided for an axis, the coverage response SHALL be the result of a trimming operation for the dimension corresponding to that axis, preserving the dimension.
^|E |Axis name `time` SHALL be supported if the collection describes a temporal dimension in its extent.
^|F |A 400 error status code SHALL be returned for an axis name other than `time`, an alias for `time`, or any other axis supported in the context of other requirements classes (such as spatial and general subsetting).
^|G |If the _intervalOrPoint_ values fall entirely outside the range of valid values defined for the identified axis, a 204 or 404 status code SHALL be returned.
^|H |For the `time` axis, coordinates SHALL be interpreted as values for the named axis of the `trs` specified in the collection's temporal extent, or Gregorian UTC time (as specified in RFC 3339) if it is not specified in the temporal extent.
^|I |If the subset parameter includes the `time` dimension while the `datetime` parameter is also specified, the server SHALL return a 400 client error.
^|J |If a lower limit of the subset interval is populated with an asterisk `*`, then the minimum extent of the coverage along that axis SHALL be selected.
^|K |If a upper limit of the subset interval is populated with an asterisk `*`, then the maximum extent of the coverage along that axis SHALL be selected.
^|L |Multiple subset parameters SHALL be interpreted, as if all dimension subsetting values were provided in a single subset parameter (comma-separated)^1^.

2+|1 Example: subset=Lat(-90:90)&subset=Lon(-180:180)&subset=time("2018-02-12T23:20:52Z")&subset=atm_pressure_hpa(500) is equivalent to subset=Lat(-90:90),Lon(-180:180),time("2018-02-12T23:20:52Z"),atm_pressure_hpa(500)
|===

NOTE: When the _intervalOrPoint_ values fall partially outside of the range of valid values defined by the TRS for the identified axis,
the service is expected to return the non-empty portion of the coverage resulting from the subset.
For subsetting on the range set, and for coverage media types with no geo-referencing mechanisms (e.g. PNG), NO_DATA values or transparency should be used.
If a georeferencing mechanism is available within the negotiated media type, the service could decide whether to use NO_DATA values
or simply return the properly geo-referenced values within the domain set.

[[subset-temporal-parameter-aliases-recommendation]]
==== Recommendation for `time` dimension aliases

For convenience, this Standard recommends that Implementations recognize the different case variation and the shorthand `t` as an alias for the `time` dimension.
Generic clients intended to be interoperable with all Implementations of this Standard should not use these aliases,
but should always use `time` to refer to the primary temporal dimension as specified in the above requirement.

[[rec_subsetting-temporal_subset-temporal-aliases]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/subsetting-temporal/subset-temporal-aliases*
^|A | The axis names `t` (lowercase/uppercase) and `Time` case variation SHOULD be interpreted as aliases for `time` (the primary temporal dimension).
|===

IMPORTANT: To ensure interoperability, clients should always use the prescribed primary temporal axis name (`time`) and not rely on any of the aliases.

==== Permission for omitting last time components

[[per_subsetting-temporal_subset-components-omission]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/subsetting-temporal/subset-components-omission*
^|A | Implementations MAY support the omission of any number of the last time components of RFC 3339 temporal instants.
In such cases, the implementations will interpret these omitted components as 0 for the start of an interval or a slicing instant, and as the latest possible values for the ending instant of a temporal interval.
^|B | Implementations MAY support the omission of the `Z` and time zone offset. In such cases, the implementations will interpret the temporal instant as UTC.
|===

[[datetime-parameter-subset-requirements]]
==== Query parameter `datetime`

The `datetime` convenience parameter maps to a trimming or slicing operation (which could also be expressed using `subset`).
When using a single temporal instant, the parameter corresponds to a slicing operation, whereas when using a pair of instants separated by a forward slash (`/`), the parameter corresponds to a trimming operation.
The temporal instants are specified using UTC and Gregorian calendar, based on RFC 3339, also allowing for omission of some temporal components as with `subset`.
For example, the query parameter `datetime=2020-01-01` is equivalent to `subset=time("2020-01-01")`, and the query parameter `datetime=2020-01-01/2020-01-31` is equivalent to `subset=time("2020-01-01":"2020-01-31")`.

[[req_subsetting-temporal_datetime]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting-temporal/datetime*
^|A |The implementation SHALL support a `datetime` parameter expressed corresponding to either a date-time instant or a time interval, conforming to the following syntax (using link:https://tools.ietf.org/html/rfc5234[ABNF]):

[source]
----
interval-closed     = date-time "/" date-time
interval-open-start = [".."] "/" date-time
interval-open-end   = date-time "/" [".."]
interval            = interval-closed / interval-open-start / interval-open-end
datetime            = date-time / interval
----
The syntax of `date-time` is specified by link:https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339, 5.6].
^|B |Only the portions of the coverage within the specified interval SHALL be part of coverage response, performing a trim operation for an interval or a slicing operation for an instant.
^|C |The implementation SHALL support a double-dot (`..`) or an empty string for the start/end as indicating an unbounded or half-bounded interval (only having a start or end).
^|D |If a `datetime` parameter is specified requesting a coverage without any temporal dimension, the parameter SHALL either be ignored, or a 4xx client error generated.
|===

[width="90%",cols="2,6a"]
|====
| Note | ISO 8601-2 distinguishes unbounded start/end timestamps (double-dot) and unknown start/end timestamps (empty string). For queries, an unspecified start/end has the same effect as an unbounded start/end.
|====

.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`datetime=2018-02-12T23:20:52Z`
=================

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00:00:00Z/2018-03-18T12:31:12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00:00:00Z/..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=../2018-03-18T12:31:12Z`
=================

==== Permission for Slicing Sparse Dimensions

[[per_subsetting-temporal_slice-sparse-dimension]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/subsetting-temporal/slice-sparse-dimension*
^|A |The empty portions in a coverage resulting from a slice operation on an axis (e.g. time), combined with a trimming operations on other axes (e.g. latitude and longitude)
 which would either be empty or not cover the full extent of the trim operation MAY be filled with data values from the same trim operation
 combined with a slicing operation on a different value of the slicing axis which would return non-empty values.
 For example, the closest or last previous time for which data is available for a certain geospatial extent may be returned.
 An Earth Observation use case for this permission is to allow retrieving a slice of the last available imagery on or before a certain date,
 taking into account that a certain geographic area may only be observed every few days.
^|B |This permission applies to both explicit slice operations using subset, as well as to implicit slicing from requesting an output format only supporting
 a lower dimensionality than the data (e.g. requesting a 2D image from a 3D coverage as PNG or GeoTIFF).
^|C |A query parameter defined by a custom or standardized extension MAY be made available to enable, disable or alter that behavior.
|===

IMPORTANT: Slicing (a `subset` specifying a single value for a particular dimension) is mutually exclusive with scaling on that same dimension
as per <<req_subsetting-spatial_subset>> (using the `resolution` query parameter as defined in the relevant Scaling requirements class).

===== Example of applying the permission for slicing on sparse dimensions

In this first example, a client requests a bounding box for (40 N, 30 E)-(70 N, 50 E), while slicing a date:

`datetime=2025-01-01&f=image/tiff&bbox=30,40,50,70`.

Because the primary temporal dimension is sparse due to some satellites only covering some of the Earth's surface on a given day, data is not available for that specific date for some of the
spatial region covered. In this case, the server can use data from a nearby date to fill those regions.

In this second example, the subsetting operation is a trim, but because the GeoTIFF format is inherently 2D, it implies a "flattening" of the response such that this permission
also applies:

[source,http]
----
GET /collections/sentinel2-l2a/coverage?datetime=2025-01-01/2025-01-31&bbox=30,40,50,70
Accept: image/tiff
----

The server can then perform a mosaic of the month of January with the most recent images displayed on top.

==== Recommendation for interpolation preference when supporting slicing on sparse dimensions

[[rec_subsetting-temporal_slice-prefer-header]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/subsetting-temporal/slice-prefer-header*
^|A |When supporting slicing on sparse dimensions, the Implementation SHOULD understand a `Prefer:` request header
(as defined in https://datatracker.ietf.org/doc/html/rfc7240[RFC 7240]) value provided by the client hinting at the preferred
<<conventions-interpolation-methods, interpolation method>>.
^|B |The implementation SHOULD support an `interpolation=` value for that `Prefer:` header selecting one specific interpolation method using a safe CURIEs or URI, such as from the OGC
definition server (https://www.opengis.net/def/interpolation/OGC/1), for specific dimensions being sliced. Example: `Prefer: interpolation=time([ogc-interpolation:linear])`
^|C |The implementation SHOULD support a `properties-interpolation=` value for that `Prefer:` header selecting one specific interpolation method for specifics field being returned,
which will override interpolation methods specified in any `interpolation` preference for any dimension, using a safe CURIEs or URI, such as from the OGC
definition server (https://www.opengis.net/def/interpolation/OGC/1). Example: `Prefer: properties-interpolation=landCover([ogc-interpolation:nearest-neighbor])`.
^|D |The implementation SHOULD also support in the context of that `properties-interpolation=` value the selection of an interpolation method for a specific
field and dimension, which will override interpolation for that field only for that dimension, using the `dimension:URI` syntax inside the parentheses, for example:
`Prefer: properties-interpolation=landCover(time:[ogc-interpolation:nearest-neighbor])`.
^a|E | The implementation SHOULD consider supporting the following interpolations methods, with the following meaning in the context of the slicing sparsed dimensions permission:

- `[ogc-interpolation:next]`: Use the next available data point from the sliced dimension,
- `[ogc-interpolation:previous]`: Use the previous available data point from the sliced dimension,
- `[ogc-interpolation:nearest-neighbor]`: Use the nearest data point from the sliced dimension,
- `[ogc-interpolation:linear]`: Perform a linear interpolation between the previous and next available data point from the sliced dimension,
- `[ogc-interpolation:quadratic]`: Perform a quadratic interpolation among data points around the slicing point along the dimension,
- `[ogc-interpolation:cubic]`: Perform a cubic interpolation among data points around the slicing point along the dimension,
- `[ogc-interpolation:none]`: Only return a value if the sliced dimension corresponds exactly to an available data point, return NODATA otherwise (hit or miss)
|===

==== Recommendation for default interpolation method when supporting slicing on sparse dimensions

[[rec_subsetting-temporal_slice-default-interpolation]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/subsetting-temporal/slice-default-interpolation*
^|A | The implementation SHOULD use either `[ogc-interpolation:previous]` or `[ogc-interpolation:nearest-neighbor]`
when no preference is specified by the client.
|===

==== Requirement for indicating a preference has been applied when supporting slicing on sparse dimensions

[[req_subsetting-temporal_slice-preference-applied]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting-temporal/slice-preference-applied*
^|A | If an Implementation supports <<req_subsetting-temporal_slice-prefer-header, client preferences for interpolation>>,
the Implementation SHALL use a response header `Preference-Applied:` when it applied the preference specified by the client, for example,
`Preference-Applied: interpolation=time([ogc-interpolation:linear])` and `Preference-Applied: properties-interpolation=landcover([ogc-interpolation:nearest-neighbor])`.
|===

==== Requirement for strict or lenient preference handling when supporting slicing on sparse dimensions

[[req_subsetting-temporal_slice-preference-handling]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting-temporal/slice-preference-handling*
^|A | If an Implementation supports <<req_subsetting-temporal_slice-prefer-header, client preferences for interpolation>>,
the Implementation SHALL support the `Prefer: handling` parameter defined in https://www.rfc-editor.org/rfc/rfc7240#section-4.4[RFC 7249 Section 4.4] where a value of `handling=lenient` would simply ignore an unsupported preference, while a
value of `handling=strict` SHALL return a 4xx error if the server is not able to fulfill the preference of the client
(note that the handling parameter applies to the request as a whole, rather than to any specific preference).
^|B | If no handling preference is specified, the Implementation SHALL default to lenient handling for the purpose of
interpolation preferences.
|===
