[[rc_table_crs]]

[requirements_class]
.Coordinate Reference System by Reference
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/crs
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
requirement:: /req/crs/output-crs
====

=== Requirements

==== Query parameter `crs`
A successful GET response is described in the Coverages API core class (https://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/core).

[[req_crs_crs-definition]]
[requirement]
====
[%metadata]
identifier:: /req/crs/output-crs
part:: The coverage retrieval operation SHALL support a query parameter `crs` specifying the output CRS using a URI or safe CURIE referencing a registered CRS
e.g., `https://www.opengis.net/def/crs/OGC/1.3/CRS84` or `[OGC:CRS84]`.
part:: The list of supported output CRSs SHALL be included in the `crs` property of the collection description at `/collections/{collectionId}` as URIs.
All of these listed CRSs SHALL be supported as output CRSs by the server for that collection.
If the list of supported CRSs is not present, the native CRS (`storageCrs` in the collection description) SHALL be supported, which defaults to
`https://www.opengis.net/def/crs/OGC/1.3/CRS84` if not specified.
part:: If present, the list of output CRSs SHALL include the default output CRS, which is the `storageCrs` if specified, or `https://www.opengis.net/def/crs/OGC/1.3/CRS84` otherwise.
part:: If the spatial subsetting requirements class is supported, the `bbox-crs` and the `subset-crs` SHALL additionally support the value specified in the `crs` parameter.
part:: CRSs expressed as URIs or as safe CURIEs SHALL be supported.
part:: The content of that response SHALL be consistent with the requested CRS.
part:: If the parameter value for `crs` is not valid for requested coverage, the status code of the response SHALL be 400.
====

NOTE: When no `crs` parameters are specified, the default output CRS is the native (`storageCrs`), which is CRS84 if none is specified (see <<rc_core,Core requirement class>> for additional details).

NOTE: A CURIE `{authority}[-{objectType}]:{id}` would map to the following OGC URI: `https://www.opengis.net/def/{objectType}/{authority}/0/{id}`. If `-{objectType}` is missing, the default object type is crs.

See how to determine the native (storage) CRS for the coverage in <<rc_core>>.

NOTE: The default CRS of the BBOX is https://www.opengis.net/def/crs/OGC/1.3/CRS84 but the default CRS of the coverage is the native (storage) CRS

[[per_crs_crs-curie]]
[permission]
====
[%metadata]
identifier:: /per/crs/crs-curie
part:: Un-safe CURIE without square brackets MAY be supported.
====

NOTE: This makes the notation compatible with WCS with the exception of CRS:84 which should be OGC:CRS84 for OGC API - Coverages.
