[[rc_cog]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/cog
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|Dependency  |https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf
|Dependency  |https://docs.ogc.org/is/19-008r4/19-008r4.html
|Dependency  |https://docs.ogc.org/is/21-026/21-026.html
|===

// [[GeoTIFF]] OGC 19-008: *OGC GeoTIFF Standard*, Version 1.1, http://docs.opengeospatial.org/is/19-008r4/19-008r4.html
// [[[TIFF_V6,TIFF V6.0]]], Adobe Developers Association: TIFF Specification Revision 6.0. (1992) https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf[https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf]

==== Requirements

[[requirements-class-cog-clause]]

===== Cloud Optimized GeoTIFF access

[[req_cog_http-range]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cog/http-range*
^|A |The coverage resource (`/coverage`), as defined in the Core requirement class, SHALL support HTTP range requests as specified in
the https://docs.ogc.org/is/21-026/21-026.html#HTTPRangeSupportRequirements[`/req/http-range` requirement class of COG].
|===

[[req_cog_cloud-optimized]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cog/cloud-optimized*
^|A |The coverage resource, as defined in the Core requirement class, SHALL support content negotiation of a https://docs.ogc.org/is/19-008r4/19-008r4.html[GeoTIFF] using the cloud-optimized profile,
(`Accept-Profile:`/`Content-Profile:` http://www.opengis.net/def/profile/geotiff/cloud-optimized`, `Accept:`/`Content-Type:` `image/tiff; application=geotiff` media type).
^|B |The response SHALL be a GeoTIFF document which validates against the GeoTIFF and TIFF standard.
^|C |If the response contains multiple fields, the fields SHALL be encoded as bands ordered following the `x-OGC-property-seq` sequence.
|===
