[[rc_table_scaling_general]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/scaling-general
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

==== Query parameter `resolution`

[[req_scaling-general-resolution]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling-general/resolution*
^|A |For data with additional dimensions beyond spatial and a primary temporal dimension, the coverage retrieval operation SHALL support a `resolution` query parameter
specifying the resolution for the additional dimensions in the units specified for those dimensions.
For a dimension whose values are expressed as a single number, the resolution value will always be a positive number.
^|B |For categorical values whose semantic definition supports multiple levels of classification, the Implementation SHALL support the name of those levels as the resolution
(which could be explicitly listed in the `availableResolutions` of that dimension grid definition).
^|C |The server SHALL support as a value for this parameter a comma-separated list of dimensions names followed by a resolution value in parentheses.
^|D |The server SHALL support an empty resolution value as referring to the native resolution for that particular dimension.
^|E |The server SHALL support as axis name all of the additional dimensions listed in the collection description's extent other than `spatial` and `temporal`.
^|F |A 400 error status code SHALL be returned if an axis name in the `resolution` parameter value does not correspond to an additional dimension described in the collection extent,
or to any other axis supported in the context of other requirements classes (such as spatial and temporal scaling).
^|G |For a regularly gridded coverage, the resolution (the distance between two samples along that dimension) for each of the listed dimension(s) SHALL correspond to the specified value.
^|H |For an irregularly gridded coverage, the distance between two samples along each of the listed dimension(s) SHALL be at minimum the value specified as the resolution for the corresponding dimension.
^|I |For a non-gridded coverage, when explicitly listing each dimension, the distance between two samples along each of the listed dimension(s) SHALL be at minimum the value specified as the resolution
for the corresponding dimension.
^|J |For additional dimensions where a `trs` of `https://www.opengis.net/def/crs/OGC/0/GregorianDateTime` is specified, the implementation SHALL support an ISO 8601 period notation.
|===

NOTE: This `resolution` query parameter also allows to combine resolutions for other dimensions specified by
the <<rc_table_scaling_temporal, temporal>> and <<rc_table_scaling_spatial, spatial>> requirements classes.

[[scaling-general-interpolation-guidance-recommendation]]
==== Recommendation for interpolation guidance when scaling on a general dimension

This Core part of the OGC API - Coverages Standard does not require the server to implement a mechanism allowing a client to request a specific interpolation method,
but it does recommend supporting a `Prefer:` request header for the client to indicate a preference.
Describing the inner workings of interpolation methods is out of scope for this document.
Some interpolation methods are described in https://docs.ogc.org/as/07-011r2/07-011r2.pdf[informative annex B of OGC Topic 6.1].
The following recommendation also provides guidance for implementations such as some important considerations to take into account when performing interpolation.
This guidance applies whether the resampling is performed as a result of the use of the scaling query parameters by the client,
or for automatic resampling in order to avoid returning too much data (as described in the downsampling permission below).

This guidance also applies to interpolation which could also be performed by clients.
Including an accurate description of the domain and range in a coverage response provided by the server allows to select a proper interpolation method.
The collection description and the collection logical schema also provides this information for all fields and dimensions of the coverage,
such as the `variableType` of a particular dimension, the `x-ogc-variableType` of a particular field, as well as a description of the gridded dimensions,
including the region of validity of individual grid cells where applicable.

[[rec_scaling-general-interpolation]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:per-id}* |*/rec/scaling-general/interpolation*
^|A | Implementations SHOULD default to the best available interpolation method which will not significantly degrade response time or
put too much strain on the server resources.
^|B | When interpolating gridded data, implementations SHOULD take into account the region of validity of values for
ndividual grid cells, as identified in `relativeBounds` or `boundsCoordinates` of
the dimension's grid description (within the collection description's `extent`), typically considering the center of that
region of validity for interpolation calculations.
When `relativeBounds` (for regular grids) or `boundsCoordinates` (for irregular grids) are omitted,
the coordinates (`firstCoordinate + n * resolution` for regular grids, `coordinates` for irregular grids) are assumed as being
centered within the region of validity.
^|C | Implementations SHOULD include in all coverage responses an accurate description of the domain and range of the returned
coverage, as well as a description of any interpolation
applied to the source data to produce that output, to the extent that the negotiated output format supports carrying that
information.
|===

[[scaling-general-default-interpolation-recommendation]]
==== Recommendation for default interpolation method when scaling on a general dimension

Two different aspects of a coverage needs to be considered in interpolation: the dimensions of the domain,
and the the field values of the range. Each of these aspects can be either categorical or continouous.
The interpolation is always applied to the field values of the range.
However, since those values are interpolated along specific dimensions, the nature of the dimensions also plays a role in
the validitity of the interpolation method selected.

For fields with a continuous variable type, the interpolation performed should respect the gradual change in the values
so that the more detailed values is a best guess of what values might actually lie in between.

For fields with a categorical variable type, the interpolation performed should only produce valid values that are directly related to
the source values. For example, averaging the numerical values associated with categories is not valid.

For categorical dimensions, only some aggregation methods are appropriate, which may also depend on the variable types of the fields.

[[rec_scaling-general_default-interpolation]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/scaling-general/default-interpolation*
^|A | For fields with a continuous variable type along a continuous dimension,
the implementation SHOULD default to a continuous interpolation method,
such as `[ogc-interpolation:linear]`, `[ogc-interpolation:quadratic]` or `[ogc-interpolation:cubic]`,
when no preference is specified by the client.
^|B | For fields with a continuous variable type along a non-continuous dimension,
the implementation SHOULD default to `[ogc-interpolation:mean]` or `[ogc-interpolation:median]` interpolation method,
when no preference is specified by the client.
^|C | For fields with a non-continuous variable type along a continuous dimension,
the implementation SHOULD default to `[ogc-interpolation:nearest-neighbor]` or `[ogc-interpolation:modal]` interpolation method,
when no preference is specified by the client.
^|D | For fields with a non-continuous variable type along a non-continuous dimension,
the implementation SHOULD default to `[ogc-interpolation:modal]` interpolation method, when no preference is specified by the client.
|===

==== Downsampling permission

[[per_scaling-general-downsampling]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/scaling-general/downsampling*
^|A |In the case where a response to a request without a `resolution` parameters would be larger than an advertised server limit, an implementation
MAY automatically downsample the coverage to a suitable resolution instead of returning a 4xx client error.
|===

NOTE: A client retrieving a coverage from an implementation advertising support for this "General Scaling" requirements class should explicitly use e.g., `resolution=pressure()` if it wants to ensure
retrieving the coverage in its native resolution and prefers receiving an error instead of a downsampled version of the data.

==== Recommendation for interpolation preference when scaling on a general dimension

[[rec_scaling-general_prefer-header]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/scaling-general/prefer-header*
^|A |When supporting scaling on a general dimension (dimension other than spatial or temporal), the Implementation SHOULD understand a `Prefer:` request header
(as defined in https://datatracker.ietf.org/doc/html/rfc7240[RFC 7240]) value provided by the client hinting at the preferred
<<conventions-interpolation-methods, interpolation method>>.
^|B |The implementation SHOULD support an `interpolation=` value for that `Prefer:` header selecting one specific interpolation method using a safe CURIEs or URI, such as from the OGC
definition server (https://www.opengis.net/def/interpolation/OGC/1), for specific dimensions being scaled. Example: `Prefer: interpolation=pressure([ogc-interpolation:nearest-neighbor])`
^|C |The implementation SHOULD support a `properties-interpolation=` value for that `Prefer:` header selecting one specific interpolation method using a safe CURIEs or URI, such as from the OGC
definition server (https://www.opengis.net/def/interpolation/OGC/1), for specific fields being returned. Example: `Prefer: properties-interpolation=landCover([ogc-interpolation:nearest-neighbor])`.
^|D |The implementation SHOULD also support in the context of that `properties-interpolation=` value the selection of an interpolation method for a specific
field and dimension, which will override interpolation for that field only for that dimension, using the `dimension:URI` syntax inside the parentheses, for example:
`Prefer: properties-interpolation=temperature(pressure:[ogc-interpolation:linear])`.
^a|E | The implementation SHOULD consider supporting the following interpolations methods, with the following meaning in the context of the dimension being scaled:

- `[ogc-interpolation:linear]`: Perform a linear interpolation among the values being represented along the scaled dimension,
- `[ogc-interpolation:nearest-neighbor]`: Use the available value nearest to the center within the values being represented along the scaled dimension,
- `[ogc-interpolation:quadratic]`: Perform a quadratic interpolation among the values being represented along the scaled dimension,
- `[ogc-interpolation:cubic]`: Perform a cubic interpolation among the values being represented along the scaled dimension,
- `[ogc-interpolation:mean]`: Use the mean of all values being represented along the scaled dimension,
- `[ogc-interpolation:minimum]`: Use the minimum of all values being represented along the scaled dimension,
- `[ogc-interpolation:maximum]`: Use the maximum of all values being represented along the scaled dimension,
- `[ogc-interpolation:median]`: Use the median of all values being represented along the scaled dimension,
- `[ogc-interpolation:modal]`: Use the most frequent value of all values represented along the scaled dimension,
|===

NOTE: In the examples mentioned above, `pressure` is an additional dimension described by the
https://docs.ogc.org/DRAFTS/20-024.html#rc-uad-collections-section[Uniform Additional Dimensions]
(with a semantic definition such as `"definition": "https://qudt.org/vocab/quantitykind/AtmosphericPressure"`),
while `landcover` and `temperature` are fields described by the https://docs.ogc.org/DRAFTS/23-058r2.html[collection schema].

==== Requirement for indicating a preference has been applied when scaling on a general dimension

[[req_scaling-general_preference-applied]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling-general/preference-applied*
^|A | If an Implementation supports <<rec_scaling-general_prefer-header, client preferences for interpolation>>,
the Implementation SHALL use a response header `Preference-Applied:` when it applied the preference specified by the client, for example,
`Preference-Applied: interpolation=pressure([ogc-interpolation:linear])` and `Preference-Applied: properties-interpolation=landcover([ogc-interpolation:nearest-neighbor])`.
|===

==== Requirement for strict or lenient preference handling when scaling on a general dimension

[[req_scaling-general_preference-handling]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling-general/preference-handling*
^|A | If an Implementation supports <<rec_scaling-general_prefer-header, client preferences for interpolation>>,
the Implementation SHALL support the `Prefer: handling` parameter defined in https://www.rfc-editor.org/rfc/rfc7240#section-4.4[RFC 7249 Section 4.4] where a value of `handling=lenient` would simply ignore an unsupported preference, while a
value of `handling=strict` SHALL return a 4xx error if the server is not able to fulfill the preference of the client
(note that the handling parameter applies to the request as a whole, rather than to any specific preference).
^|B | If no handling preference is specified, the Implementation SHALL default to lenient handling for the purpose of
interpolation preferences.
|===

==== Permission to only support certain resolutions

[[per_scaling-general_specific-resolutions]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/scaling-general/specific-resolutions*
^|A |Implementations MAY support only specific resolutions listed in the `availableResolutions` sub-property of the `grid` property
(as defined in the https://docs.ogc.org/DRAFTS/20-024.html#rc-uad-collections-section[Uniform Additional Dimensions of OGC API - Common - Part 2]) of the dimension being scaled (any resolution is considered available if the sub-property is missing).
The units of each resolution are the units specified in the `unit` property of the dimension, the units implied by the semantic `definition`, the units implied
by the Temporal Reference System (`trs`), or the units implied by the Vertical Reference System (`vrs`), just like the `resolution` sub-property.
^|B |When `availableResolutions` is not present, Implementations MAY return a 4xx error for a requested resolution more detailed than the native `resolution` declared for the dimension.
^|C |When `availableResolutions` is present, Implementations MAY return a 4xx client error for a requested resolution not matching (within some rounding error tolerance) any listed available resolution.
|===

NOTE: A common use case for the Scaling requirements classes is the ability for clients to request downsampled (coarser resolution)
data compared to the native resolution. For the purpose of upsampling finer than the native resolution using, for example, a linear
or cubic interpolation, it is usually more efficient to perform this upsampling client-side, saving both bandwidth and server
processing resources. The server is therefore allowed to reject requests for data upsampled beyond the native resolution,
or beyond a certain scaling factor past the native resolution. However, for some use cases, support for data upsampling server-side
might make sense, for example when this upsampling capability implies downscaling a subset of the data available with a
climate forecast model using computational fluid dynamics.

Example of specific resolutions available for a pressure dimension (using hectopascals here):

[source,json]
----
      "pressure" : {
         "definition": "https://qudt.org/vocab/quantitykind/AtmosphericPressure",
         "unit" : "hPa",
         "interval" : [ [ 1.0, 1001.0 ] ],
         "grid" : {
            "cellsCount" : 21,
            "resolution": 50,
            "availableResolutions": [ 50, 100, 250 ]
         }
      }
   }
----

==== Permission to support legacy scaling query parameters

[[per_scaling-general_legacy]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/scaling-general/legacy*
^|A |Implementations MAY additionally support the `scale-factor` and `scale-axes` legacy query parameters expressing resolution as the factor by which the data's native resolution has been downsampled (a factor of 2 meaning two times coarser).
^|B |Implementations MAY additionally support the `scale-size` legacy query parameter expressing the number of samples expected in the output for each dimension.
|===

IMPORTANT: To ensure interoperability, clients should use the `resolution` query parameter rather than the legacy ones.
