[[rc_table_scaling]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/scaling
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|===

=== Requirements

==== Parameter `scale-factor`

[[req_coverage_scaling-factor]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-scaling/factor*
^|A |The operation SHALL support a `scale-factor` numeric parameter for the coverage resource.
^|B |For each axis, the returned coverage SHALL contain the number of original sampled values, divided by the specified factor.
|===


==== Parameter `scale-axes` parameters

[[req_coverage_scaling-axes]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-scaling/axes*
^|A |The operation SHALL support a parameter `scale-axes` for the coverage resource with the following characteristics (using an Extended Backus Naur Form (EBNF) fragment):

[source,EBNF]
----
  ScalingSpec:       "scale-axes"=axisName({factor})[,axisName({factor})]*
  axisName:          {text}

  Where:
     {factor} is an integer or floating-point number, and
     {axisName} refers to a valid axis for the coverage
----

^|B |The implementation SHALL support the name of axes as per the extent of the collection description, which should also correspond to those defined to the abbreviations defined by the CRS
(as defined bythe <gml:axisAbbrev> tags), and to the `axisLabels` defined in the _domain set_ for a CIS representation, and return a 400 error for an unrecognized axis name.
^|C |For each axis specified, the returned coverage SHALL contain the number of original sampled values, divided by the _factor_ specified for that axis, and the original number of sample values for unspecified axes.
|===

==== Parameter `scale-size`

[[req_coverage_scaling-size]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-scaling/size*
^|A |The operation SHALL support a parameter `scale-size` for the coverage resource with the following characteristics (using an Extended Backus Naur Form (EBNF) fragment):

[source,EBNF]
----
  ScalingSpec:       "scale-size"=axisName({number})[,axisName({number})]*
  axisName:          {text}

  Where:
     {number} is an integer or floating-point number, and
     {axisName} refers to a valid axis for the coverage

----
^|B |The implementation SHALL support the name of axes as per the extent of the collection description, which should also correspond to those defined to the abbreviations defined by the CRS
(as defined bythe <gml:axisAbbrev> tags), and to the `axisLabels` defined in the _domain set_ for a CIS representation, and return a 400 error for an unrecognized axis name.
^|C |The returned coverage SHALL contain exactly the specified number of sample values along each axis which is specified by the `scale-size` parameter, and the original number of sample values for unspecified axes.
^|D |When `scale-size` is used together with subsetting, the requested number of samples SHALL be mapped to the subset dimensions specified, even if those dimensions fall partially outside the extent of the coverage.
|===

==== Parameter `width` and `height`

[[req_coverage_scaling-width_and_height]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/coverage-scaling/width-and-height*
^|A |For coverages with a spatial dimension corresponding to the horizontal spatial axis as reprsented on a 2D map, such as longitude or easting, the operation SHALL support a parameter `width` for the coverage resource taking an integer parameter corresponding to the number of cells that should be returned along that axis.:
^|B |For coverages with a spatial dimension corresponding to the vertical spatial axis as reprsented on a 2D map, such as latitude or northing, the operation SHALL support a parameter `height` for the coverage resource taking an integer parameter corresponding to the number of cells that should be returned along that axis.:
^|C |The returned coverage SHALL contain exactly the specified number of sample values along each axis which is specified by provided scaling  parameters, the original number of sample values for unspecified axes, and any defined server limits.
^|D |When `width` and/or `height` is used together with subsetting, the requested number of samples SHALL be mapped to the subset dimensions specified, even if those dimensions fall partially outside the extent of the coverage.
|===

==== Downsampling permission

[[per_coverage_scaling-permission]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/coverage-scaling/downsampling*
^|A |In the case where a response to a request without a `scale-factor`, `scale-axes`, `scale-size`, `width`, or `height` parameters would be larger than an advertised server limit, an implementation
MAY automatically downsample the coverage to a suitable resolution instead of returning a 4xx client error.
^|B |In the case where a `scale-size`, `scale-axes`, `width` or `height` does not explicitly specify dimensions for all axes of the coverage, an implementation MAY automatically proportionately adjust one or more unspecified dimensions.
|===

NOTE: A client retrieving a coverage from an implementation advertising support for this "Scaling" requirements class should explicitly use `scale-factor=1` if it wants to ensure
retrieving the coverage in its native resolution and prefers receiving an error instead of a downsampled version of the data.
