[[rc_jpeg2000]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/jpeg2000
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|Dependency  |https://www.iso.org/standard/78321.html[ISO/IEC 15444-1:2019]
|Dependency  |https://www.iso.org/standard/84573.html[ISO/IEC 15444-2:2023]
|Dependency  |https://docs.ogc.org/is/08-085r8/08-085r8.html
|===

==== Requirements

[[requirements-class-jpeg2000-clause]]

===== JPEG 2000 representation

[[req_jpeg2000_coverage]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/jpeg2000/coverage*
^|A |Two-dimensional coverage responses for the coverage resource, as defined in the Core requirement class, SHALL support negotiating a https://jpeg.org/jpeg2000/[JPEG 2000] response using the `image/jp2` media type.
^|B |The JPEG 2000 response SHALL use the appropriate data types most closely matching the coverage field (e.g., 8 bit or 16-bit integer, 32-bit floating point).
^|C |The response SHALL contain all selected fields.
^|D |If the response contains multiple fields, the fields SHALL be encoded as bands ordered following the `x-ogc-propertySeq` sequence.
^|E |Georeferencing SHALL be included in the response using the https://docs.ogc.org/is/08-085r8/08-085r8.html[GMLJP2] encoding, consistent with the requested subset of the coverage domain.
|===
