[[rc_netcdf]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/netcdf
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|Dependency  |https://portal.ogc.org/files/?artifact_id=43732[OGC 10-090r3 Network Common Data Form Core Encoding Standard 1.0]
|===

==== Requirements

[[requirements-class-netCDF-clause]]

===== netCDF representation

[[req_netcdf_coverage]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/netcdf/coverage*
^|A |The coverage resource as defined in the Core requirement class SHALL support negotiating a https://portal.ogc.org/files/?artifact_id=43732[netCDF] response using the `application/x-netcdf` media type.
^|B |The response SHALL be a netCDF document which validates against the OGC netCDF standard.
^|C |For dimensions that do not have a well-defined netCDF `standard_name`, the name of the corresponding variable SHALL match the name of the dimension in the collection description's extent.
|===

NOTE: The https://portal.ogc.org/files/?artifact_id=50294[OGC netCDF Enhanced Data Model Extension] can be fully encoded using the
https://docs.ogc.org/is/18-043r3/18-043r3.html[OGC Hierarchical Data Format Version 5 (HDF5®) Standard].

[[rec_netcdf_profile-handling]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/scaling-general/netcdf-profile-handling*
^|A |The Implementation SHOULD support negotiating a specific netCDF profile version using HTTP headers `Accept-Profile:` / `Content-Profile:` values,
and/or via a `profile` query parameter for coverage retrieval requests, supporting:
* `https://www.opengis.net/def/profile/ogc/0/netcdf3` or `netcdf3` for classic netCDF 3 and 64-bit offset format.
* `https://www.opengis.net/def/profile/ogc/0/netcdf4` or `netcdf4` for netCDF 4 format based on the OGC HDF5 standard.
^|B |The Implementation SHOULD return a link to the default or selected profile as a `Link` HTTP response header, for example `Link: <https://www.opengis.net/def/profile/ogc/0/netcdf4>; rel="profile"`.
|===
