[[rc_zarr]]
[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/zarr
|Target type |Web API
|Dependency  |http://www.opengis.net/spec/ogcapi-coverages-1/1.0/req/core
|Dependency  |https://zarr-specs.readthedocs.io/en/latest/v2/v2.0.html[Zarr2, Zarr Storage Specification Version 2]
|Dependency  |<<ZIPISO, ISO/IEC 21320-1:2015 Information technology - Document Container File (Zip)>>
|===

==== Requirements

[[requirements-class-zarr-clause]]

===== Zarr representation

[[req_zarr_coverage]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/zarr/coverage*
^|A |Coverage responses for the coverage resource, as defined in the Core requirement class, SHALL support negotiating a https://zarr-specs.readthedocs.io/en/latest/v2/v2.0.html[Zarr] response packaged in a https://www.iso.org/standard/60101.html[Zip] file using the `application/zarr+zip` media type.
^|B |The Zarr response SHALL use the appropriate data types most closely matching the coverage fields.
^|C |The response SHALL contain all selected fields.
^|D |If the response contains multiple fields, the fields SHALL be encoded as bands ordered following the `x-ogc-propertySeq` sequence.
|===

[[rec_zarr_geozarr]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/zarr/geozarr*
^|A |Georeferencing information SHOULD be included in the response using the https://github.com/zarr-developers/geozarr-spec[GeoZarr] candidate Standard.
|===
