index.adoc


1 Introduction
==============

This OpenAPI - Coverages specification establishes how to access coverages [1] through OpenAPI.

Current limitations:

* Only gridded coverages are addressed, not MultiPoint/Curve/Surface/SOlidCoverages. Reason is that gridded coverages receive most attention today whereas the other types are not currently practically relevant.
* Only GeneralGridCoverage is addressed, other coverage types will follow later. Reason is to have a first version early which shows and allows to evaluate the principles.
* Only coverage extraction functionality is considered, not general processing (as is provided with WCS extensions such as WCPS). Exceptions from this rule are subsetting and data format encoding, given their practical relevance.
 As such, the functionality provided with WCS Core [2] is defined below.


2 Principles
============

OpenAPI establishes URL-based access patterns following a syntax like
        http://www.acme.com/path/to/resource?query-parameters
whereby

* /path/to/resource defines the local path to the resource to be retrieved on the node identified by the head part, http://www.acme.com.
* the query-parameters represent key/value pairs with further parameters passed to the request.

Given the hierarchical nature of the path component it is clear that subsetting does not fit there - after all, all dimensions in a coverage are of same importance. Further, subsetting may reference any axis and leave out any oth
er, which makes positional parameters like established with a path unsuitable. The second query parameter defined currently is the output format; this is (surprisingly) already the case in RESTful approaches, hence no change is i
nflicted here.

As a general rule,

* accessing a coverage component is done in the path section,
* subsetting and format encoding is done in the query parameter section.

As the coverage model normatively is given by the corresponding XML schema (JSON and RDF are built in sync with XML) specification of the OpenAPI access paths follows this schema. Note, though, that OWS Common, while normatively
referenced in CIS, is not followed by OpenAPI, so here deviations will occur.

For path expressions abbreviations (i.e., aliases) may be defined for convenience.

3 OpenAPI Coverage Requests
===========================

This clause defines the basics of accessing OGC coverages via OpenAPI.

3.1 General
-----------

Requirement: 
A service offering OpenAPI coverage access shall be accessible via a URL as service endpoint (subsequently referred to as Base URL).

Example:
        http://acme.com/oapi/coverages

Requirement: 
Coverage access paths, as defined in the next clause, are concatenated to the Base URL via a "/" character, followed (optionally) by a query part.

Example:
        http://acme.com/oapi/coverages/{id}/RangeSet?FORMAT=image/png

A request may be denied for server-specific reasons, such as quota.

3.2 Coverage Access Paths
-------------------------

In this clause, the path component of OpenAPI coverage access is established.

Access paths follow the XML Schema of CIS [1] in their structure.

3.3 Coverage Query Parameters
-----------------------------

In this clause, the query component of OpenAPI coverage access is established.

Subsetting and encoding parameters may be mixed in a query part, in no particular order.

3.3.1 Coverage Subsetting
-------------------------

Without any subsetting parameter the whole coverage extent is the target resource addressed. If a subsetting operation is provided then the coverage subset indicated is the target resource addressed.

Coverage subsetting is indicated through the SUBSET parameter name. The value following the "=" symbol is built as follows:

Each SubsetSpec shall adhere to this EBNF syntax:
    SubsetSpec:            +++<u>SUBSET</u>+++ +++<u>=</u>+++ axisName ( intervalOrPoint )
    axisName:              NCName
    intervalOrPoint:       interval | point
    interval:              low +++<u>:</u>+++ high
    low:                   point | +++<u>*</u>+++
    high:                  point | +++<u>*</u>+++
    point:                 number | +++<u>"</u>+++ text +++<u>"</u>+++    //" = ASCII code 0x42

In case of an interval a trim operation is specified, with lower and upper bound. In case of a point a slicing operation is specified. For the detailed semantics of subsetting, trimming, and slicing see OGC WCS [2].

A coverage access request may have any number of SUBSET parameters, however for each axis of the coverage at most one SUBSET parameter may be provided.

3.3.2 Coverage Encoding
-----------------------

Without any format encoding parameter a representation of the coverage in its Native Format will be returned. If an encoding parameter is provided then a representation of the coverage in the format indicated will be returned.
The syntax for format encoding is
    FORMAT = {format-identifier}

where {format-identifier} is defined elsewhere.

At most one FORMAT aprameter may be present in a coverage access request. The format chosen must be able to represent the output of the request.

For the detailed semantics of format encoding see OGC WCS [2].

4 Examples
==========

This section contains examples for coverage access, subsetting, and encoding. It assumes a service endpoint of http://acme.com/oapi/ .

4.1 Service Metadata
--------------------

The first part is about service metadata. Currently this is wild speculation as it will mainly be defined through OpenAPI Common.
* http://acme.com/oapi/ServiceDescription/FormatsSupported -- returns a list of formats in which coverage representations can be requested

4.2 Coverage Access
-------------------
The second part is about coverage access, which (as described earlier) is driven by the coverage structure and, hence, given:

* http://acme.com/oapi/coverages/MyLittleCoverage -- returns coverage MyLittleCoverage in its Native Format
* http://acme.com/oapi/coverages/MyLittleCoverage/DomainSet -- returns the coverage's domain set definition
* http://acme.com/oapi/coverages/MyLittleCoverage/DomainSet/GeneralGrid/srsName -- returns the srsName value, i.e.: the coverage's (spatio-temporal) CRS
* http://acme.com/oapi/coverages/MyLittleCoverage/DomainSet/GeneralGrid/axisLabels -- returns a list o the coverage's axis names
* http://acme.com/oapi/coverages/MyLittleCoverage/RangeType -- returns the coverage's range type information (i.e., a description of the pixel semantics)
* http://acme.com/oapi/coverages/MyLittleCoverage/Metadata -- returns the coverage's metadata (may be empty) 

4.3 Coverage Subsetting and Format Encoding
-------------------------------------------

The third part is about query parameters:

* http://acme.com/oapi/coverages/MyLittleCoverage?SUBSET=Lat(40,50)&SUBSET=LONG(10,20)  -- returns a coverage coutout between (40,10) and (50,20)
* http://acme.com/oapi/coverages/MyLittleCoverage?SUBSET=time("2019-03-27") -- returns a coverage slice at the timestamp given (in case the coverage is Lat/Long/time the result will be a 2D image)
* http://acme.com/oapi/coverages/MyLittleCoverage?FORMAT=text/json -- returns the coverage in JSON format


5 Open Issues
=============

* establish service parameter access, based on OpenAPI Common
* what is the output format of items typically returnd as XML or JSON, such as DomainSet and RangeType? Should maybe FORMAT be applicable here as well? If so, should it be listed as a possible output format (which might be confusing)?


References
==========

[1] Coverage Implementation Schema (CIS) 1.1
[2] Web Coverge Serviec - Core 2.0 
[3] RFC 3986 "Uniform Resource Identifier (URI): Generic Syntax", https://tools.ietf.org/html/rfc3986 .

