:authors: Stephan Meissl, Chuck Heazel
:authors_email: TBA
:date: YYYY-MM-DD
:title: OGC API - Coverages
:swgname: OGC API - Coverages
:shortname: Coverages API
:resources: coverages
:resource: coverage
:information_model_base: Coverage Implementation Schema (CIS)
:information_model_base_docnum: 09-146r8
:githubrepo: https://github.com/opengeospatial/ogc_api_coverages
:base_swg: Web Coverage Service (WCS) SWG
:target_start_date: July 2020
:target_end_date: December 2020
:dwg_review: Coverages DWG
:dwg_review_meeting: June 2020 Virtual OGC Members' meeting
:conveners: FirstName LastName

== {swgname}

[cols=",",width="75%",options="",align="center"]
|===
|TITLE: a| {swgname} Standards Working Group Charter
|Author Name(s): | {authors}
|Email: | {authors_email}
|DATE: | {date}
|CATEGORY: | SWG Charter
|===

To: OGC members & interested parties

The existing WCS.SWG is renamed and rechartered. The OGC members listed below have proposed the "{swgname} SWG". The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.
The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG’s official charter. Technical discussions may occur no sooner than the SWG’s first meeting.
This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

•	You must be an employee of an OGC member organization or an individual member of OGC;

•	The OGC member must have signed the OGC Membership agreement;

•	You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

•	You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.
Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.
Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

=== Purpose of the {swgname} Standards Working Group

The purpose of this Standards Working Group is to:

•	Develop and maintain the Coverage data model suite, including Coverage encodings.
•	Develop and maintain the Coverage service model standards, including WCS and OAPI-Coverages, with their core and extension specifications.


=== Business Value Proposition

The quarterly Space Foundation https://promo.spacefoundation.org/tsr/quarterly-reports/TheSpaceReport19Q1.pdf[2019 first quarter Space Report] states that 38 percent of the 465 spacecraft deployed in 2018 were deployed for Earth Observation or Remote Sensing missions. A majority of those spacecraft were deployed for commercial purposes. In a separate report by a consulting firm specializing in space markets http://www.euroconsult-ec.com/earthobservation[report], the market for data and services derived from Earth observation (EO) satellites was forecasted to reach $8.5 billion by 2026.

Much of the coverage data produced by EO satellite programs is used by scientists to help understand environmental change and how communities can improve their management of natural resources. Other applications include, for example, competitor analysis in business and geospatial intelligence in defense and security. 

In the European INSPIRE legal framework for a common Spatial Data Infrastructure coverages play a central role. In 9 of the 13 themes data appear modeled as coverages, such as Elevation, Land cover, Orthoimagery, Soil, Energy resources, Species distribution, Natural risk zones, and Geology.

With the volume of coverage data growing daily, there is an significant need to find ways to leverage recent advances in technology that can improve the ability of users to discover and access coverages. The goal of the OGC WCS and API - Coverages standards work is to leverage some of those technological advances, in particular Web APIs.

=== Scope of Work

In scope of this SWG is all standards related work on coverage data and services, including:

- Coverages, as defined in Abstract Topic 6 and Coverage Implementation Schema (CIS), have proven valuable as a unified, comprehensive representation of spatio-temporal grids, point clouds, and meshes. In particular, coverages serve to model "datacubes".
- Web Coverage Service (WCS) with its easy to implement and use core and the manifold extensions has proven a powerful way to access, process, filter, analyse, and combine coverage data, being used on multi-Petabyte satellite image and atmospheric data, among others.
- OAPI-Coverages is a service model base on OpenAPI frameworks. These have helped make describing and sharing API definitions more suitable for interoperability standardization. The concept of a {shortname} was demonstrated in various OGC Innovation Program initiatives.

Regarding OAPI-Coverages, the {swgname} SWG will build on those preliminary efforts to more fully develop and document a {shortname} candidate standard that will provide a modernized, common, and consistent interface to services that aligns with the current architecture of the Web and the Spatial Data on the Web Best Practices (https://www.w3.org/TR/sdw-bp/).

The {swgname} SWG will develop a {shortname} candidate standard which is informed by emerging OGC API best practices and prior API standards examples (e.g., OGC API - Features) to define core API functions for GET, PUT, PATCH, POST, and DELETE applied to {resources} as resources. The {shortname} will also document metadata requirements for {resources} to enhance discovery and exchange of {resources}.

* Architecture: The {swgname} standard will align with prior OGC work for {resources} and Web APIs. The proposed standard will define API building blocks for {resources} in Web API. The {swgname} will be consistent with HTTP and HTTPS.

*	Encodings: The first version of the {shortname} will support JSON and HTML as encodings for descriptions of {resource} resources in the API. No encoding will be mandatory and other encodings may be used as well. The HTTP focus is designed to support the use of multiple formats and defines rules about how servers can return the encoding that the client can best handle (“content negotiation”).

* Information model: The {shortname} standard will conform to OpenAPI models and OGC API best practices. Additionally, the API will align or make use of the {information_model_base}. The conceptual models will consider recommendations from recent and current OGC Innovation Program initiatives such as Testbeds, Pilots, Sprint and others.

* Modularization: {swgname} - Part 1: Core will define a basic set of capabilities organized in multiple conformance classes building on each other. The minimal conformance class will specify a simple interface to access metadata from {resources} that is sufficient for interfaces to exchange and perform basic web functions with the {resources}. Additional conformance classes will define additional capabilities based on the requirements and requirements classes defined in the core to meet the needs of use cases that require such capabilities.

* Reuse: The use of unique {shortname} resources or components will be minimized and, where available, existing industry-standards or patterns that are commonly used by developers will be used instead. The most important example for this is the use of an OpenAPI definition instead of OGC-specific "Capabilities" documents and the use of OGC API - Common components to the maximum extent practicable.

Extensions may be proposed and addressed in revisions to this charter. The primary goal of the {shortname} SWG is to develop the core of "{swgname}" as quickly as possible and work on extensions after that, driven by community interest. An important aspect is to ensure that implementing the standard will lead to efficient implementations, happy developers of both server and client components, and satisfied users of such components.


Before finalizing parts of the future versions of the "{swgname}", completion of goals should be verified:

*	Working implementations of all capabilities must be available and tested.
*	Implementation feedback must be taken into account.

The SWG intends to use a public GitHub repository in the development of this standard as this is the environment many developers are familiar with and use on a daily basis.

In addition, this SWG continues work on the CIS and WCS Core and Extensions, including both maintenance and new specification development.

==== Statement of relationship of planned work to the current OGC standards baseline

The proposed OAPI-Coverages standard is intended to be a major component of the OGC API framework. It will take advantage of Web API patterns identified in OGC API standards (e.g., OGC API – Features) and other ongoing API efforts (e.g. OGC API - Common development in the OWS Common SWG) to better align with current and emerging IT practices.  The {shortname} complements the {information_model_base} and provides a means for sharing {resources} developed under OGC and other {resource} encodings.

==== What is Out of Scope?

Proposals for new parts of {swgname} or change requests to existing parts must identify the user group that will benefit from the proposal and for each proposed conformance class; otherwise the proposal will be considered out-of-scope.

{swgname} is envisioned to be a modular, multi-part standard. Extensions and profiles not identified as in scope in the previous section will require a revision to the SWG charter prior to commencement of work. If a community has a need to develop a profile, the profile should be specified and governed by that community.

The basic resource described in {swgname} are {resources}. The {shortname} describes the interface and exchange of {resources}. The construction of the main components of {resources} is addressed in {information_model_base} and multiple OGC and other {resource} encoding standards.

==== Specific Contribution of Existing Work as a Starting Point

The starting point for the work will be the draft document that is currently on the proposed SWG's repository ({githubrepo}). This charter recognizes the prior work done by the {base_swg}. Upon approval of this Charter, responsibility for {swgname} will be continued by the proposed renamed {swgname} SWG.

The work will also be informed by the following specifications and by recommendations found in:

*	OGC/W3C Spatial Data Working Group on the Web Best Practices (https://www.w3.org/TR/sdw-bp/);
*	OGC Geospatial API White Paper [OGC 16-019r4];
*	OGC API - Features - Part 1: Core standard, [OGC 17-069r3]; and
* {information_model_base},	[OGC {information_model_base_docnum}].
* ISO TC211 WG6 covearge standards, in particular: 19123-1 and 19123-2

==== Is this a persistent SWG?


* [x] Yes
* [ ] No

==== When can SWG be inactivated?

The SWG is a standing one, maintaining the suite through corrigenda, feature extensions, new features, etc. as requested by the membership. Any newly adopted coverage standard will be added to the portfolio of standards maintained.

=== Description of Deliverables

==== Initial Deliverables

Regarding OAPI-Coverages the following deliverables will result from the work of this SWG:

*	A final version of the "{swgname} - Part 1: Core" document for submission to the TC.
*	Identification of at least three prototype implementations of the core based on the standard — although more would be preferred.
*	Zero or more additional parts as time and community interest permits.

Part 1 will cover basic capabilities to GET, PUT, PATCH, POST, and DELETE {resources} and define {resource} metadata. Capabilities for richer {resource} interfaces or extension for unique geospatial resource considerations will be specified in additional parts.

The targeted start date is in {target_start_date} once charter is approved. Formal approval of the core {shortname} is envisaged to take place nearer {target_end_date}.

==== Additional SWG Tasks

Additional extensions will include:

* OGC API - Coverages - Part n: Processing
* OGC API - Coverages - Part n: CRS

The part numbers will be determined later in 2020.

=== IPR Policy for this SWG

* [x] RAND-Royalty Free
* [ ] RAND for fee

=== Anticipated Participants

* Geospatial resource providers.
* Developers implementing services.
* Producers of {resource} data.
* Users of geospatial resources.

=== Domain Working Group Endorsement

The {dwg_review} will review the proof-of-concept at {githubrepo} and this SWG charter. A statement of endorsement will be requested at the  {dwg_review_meeting}.

=== Other Informative Remarks about this SWG

[loweralpha, start=1]
.	Similar or Applicable Standards Work (OGC and Elsewhere).

The following standards work may be applicable to the work of the proposed SWG:

*	17-069, OGC API - Features
*	{information_model_base_docnum}, {information_model_base}
* ISO 19123-1 and 19123-2

Additionally, the proposed SWG will monitor other OGC API work ongoing in various Standards and Innovation Program activities.

[loweralpha, start=2]
.	Details of the First Meeting
The first meeting of the SWG will be within four weeks of approval of the SWG.

[loweralpha, start=3]
.	Projected On-going Meeting Schedule
The work of this SWG will be carried out primarily on GitHub and via email, conference calls, with potential face-to-face meetings at OGC TC meetings as agreed to by the SWG members. The teleconference calls will be scheduled as needed and posted to the OGC portal. Voting on {shortname} content will be limited to SWG members only.

[loweralpha, start=4]
.	Supporters of the Proposal (Charter Members)

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially renamed. Charter Members are shown on the public SWG page.


[cols=",",width="75%",options="header",align="center"]
|===
|Name| Organization
|Stephan Meissl | EOX
|Jerome Jacovella St Louis | Ecere
|Tom Kralidis | Meteorological Service of Canada
|Chuck Heazel | Heazel Tech
|Chris Little | UK Met Office
|Peter Baumann | Jacobs University, rasdaman GmbH
|===


[loweralpha, start=5]
.	Chair(s)

{authors}

NOTE (PB): As it is a renaming the chairs would not change, unless there is a vote on this.  Here is a suggestion: we can have more than 2 chairs in the SWG (cf BigData.DWG), so if Chuck is interested in co-chairing I suggest to elect him as additional co-chair.

NOTE: This template is based on the Charter of the OGC API - Styles SWG
