:authors: Stephan Meissl, Chuck Heazel
:authors_email: TBA
:date: 2020-07-01
:title: OGC Coverages
:swgname: OGC Coverages
:shortname: Coverages SWG
:resources: coverages
:resource: coverage
:information_model_base: Coverage Implementation Schema (CIS)
:information_model_base_docnum: 09-146r8
:githubrepo: https://github.com/opengeospatial/ogc_api_coverages
:base_swg: Web Coverage Service (WCS) SWG
:target_start_date: July 2020
:target_end_date: December 2020
:dwg_review: Coverages DWG
:dwg_review_meeting: June 2020 Virtual OGC Members' meeting
:conveners: Stephan Meissl, Chuck Heazel

== {swgname}

[cols=",",width="75%",options="",align="center"]
|===
|TITLE: a| {swgname} Standards Working Group Charter
|Author Name(s): | {authors}
|Email: | {authors_email}
|DATE: | {date}
|CATEGORY: | SWG Charter
|===

To: OGC members & interested parties

Recharting the Web Coverage Service (WCS) Standards Working Group (SWG).

The OGC members listed below have proposed that the Web Coverage Service SWG be rechartered as the "{swgname} SWG". The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures. The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG’s official charter.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG meetings (see details below) are that:

* You must be an employee of an OGC member organization or an individual member of OGC;
* The OGC member must have signed the OGC Membership agreement;
* You must notify the SWG chair of your intent to participate to the meetings. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

Of course, participants may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

=== Purpose of the {swgname} Standards Working Group

The purpose of this Standards Working Group is to:

* Develop and maintain the OGC Web Coverage Service standards suite.
* Develop and maintain additions and extensions to the WCS standards suite.
* Develop and maintain the OGC API - Coverages standards suite
* Develop and maintain additions and extensions to the OGC API - Coverages standards suite.
* Develop and maintain standards for metadata exposed through Web Coverage Services or APIs.
* Develop and maintain the Coverage data model suite, including Coverage encodings.

=== Business Value Proposition

The quarterly Space Foundation https://promo.spacefoundation.org/tsr/quarterly-reports/TheSpaceReport19Q1.pdf[2019 first quarter Space Report] states that 38 percent of the 465 spacecraft deployed in 2018 were deployed for Earth Observation or Remote Sensing missions. A majority of those spacecraft were deployed for commercial purposes. In a separate report by a consulting firm specializing in space markets http://www.euroconsult-ec.com/earthobservation[report], the market for data and services derived from Earth observation (EO) satellites was forecasted to reach $8.5 billion by 2026.

Much of the coverage data produced by EO satellite programs is used by scientists to help understand environmental change and how communities can improve their management of natural resources. Other applications include, for example, competitor analysis in business and geospatial intelligence in defense and security.

In the European INSPIRE legal framework for a common Spatial Data Infrastructure coverages play a central role. In 9 of the 13 themes data appear modeled as coverages, such as Elevation, Land cover, Orthoimagery, Soil, Energy resources, Species distribution, Natural risk zones, and Geology.

With the volume of coverage data growing daily, there is an significant need to find ways to leverage recent advances in technology that can improve the ability of users to discover and access coverages. The goal of the OGC API - Coverages standards work is to leverage some of those technological advances, in particular Web APIs.

=== Scope of Work

* Coverages, as defined in Abstract Topic 6 and Coverage Implementation Schema (CIS), have proven valuable as a unified, comprehensive representation of spatio-temporal grids, point clouds, and meshes. In particular, coverages serve to model "datacubes".
* Web Coverage Service (WCS) with its easy to implement and use core and the manifold extensions has proven a powerful way to access, process, filter, analyse, and combine coverage data, being used on multi-Petabyte satellite image and atmospheric data, among others.
* OGC API - Coverages is a service model base on OpenAPI frameworks. These have helped make describing and sharing API definitions more suitable for interoperability standardization. The concept of a OGC API - Coverages was demonstrated in various OGC Innovation Program initiatives.

Regarding OGC API - Coverages, the {swgname} SWG will build on those preliminary efforts to more fully develop and document a {shortname} candidate standard that will provide a modernized, common, and consistent interface to services that aligns with the current architecture of the Web and the Spatial Data on the Web Best Practices (https://www.w3.org/TR/sdw-bp/).

Additional tasks for the SWG may be proposed and addressed in revisions to this charter. The process to be used is described in OGC 05-020r27 Technical Committee Policies and Procedures. The SWG may begin work on the new task once TC approval has been received, the charter updated, and the charter has been posted.

NOTE: The following is from the TC P&P (05-020r27). The preceeding paragraph has been updated to reflect these requirements.  This can be deleted once there is concurrence on that text.

   "Any new work from a SWG after the primary deliverable must be approved by the TC as a new Task prior to start of that work. The new work can result in an update, extension, or profile of a standard.

    The proposed Task must be presented to the TC at a plenary. Otherwise, a PowerPoint or video presentation will be developed and posted to the Portal. This presentation should cover the key aspects of the Task, especially the scope of work, the timeline, and the technical discussion related how the work relates to the standard(s) developed by the SWG.

    Once the proposed Task has been presented to the TC, the TCC will initiate a 21 day TC and public review of the proposed Task. If comments are received in the review period, the SWG shall consider the comments and reissue the proposed Task details, if necessary.

    The proposed Task will be voted upon by TC Voting Members in a Closing Plenary (see http://docs.opengeospatial.org/pol/05-020r27/05-020r27.html#voting-at-tc-meetings[Voting at TC Meetings]) or by a two-week email vote (see http://docs.opengeospatial.org/pol/05-020r27/05-020r27.html#tc-or-subgroups-of-the-tc-email-voting[TC or Subgroups of the TC Email Voting]).

    Once approved, the Task will be added to the SWG Charter and the updated Charter posted to the SWG Portal files. The SWG may now begin work on the Task."

Before finalizing parts of the future versions of the Coverage Standards, completion of goals should be verified:

* Working implementations of all capabilities must be available and tested.
* Implementation feedback must be taken into account.

A consequence of this verification is that the period between the availability of what is considered a mature draft and the finalization of the candidate standard may be longer than in the past. The timing is dependent on the availability of evidence about the suitability of the candidate standard based on implementations. Developers should be encouraged as early as possible to implement the draft API specification and provide feedback. An aspect of this is public access to drafts from the beginning. To this end, the SWG intends to use a public GitHub repository in the development of this standard as this is the environment many developers are familiar with and use on a daily basis.

==== Statement of relationship of planned work to the current OGC standards baseline

The proposed API - Coverages standard is intended to be a major component of the OGC API framework. It will take advantage of Web API patterns identified in OGC API standards (e.g., OGC API - Features) and other ongoing API efforts (e.g. OGC API - Common development in the OWS Common SWG) to better align with current and emerging IT practices.  The {shortname} complements the {information_model_base} and provides a means for sharing {resources} developed under OGC and other {resource} encodings.

==== What is Out of Scope?

Proposals for new parts of {swgname} or change requests to existing parts must identify the user group that will benefit from the proposal and for each proposed conformance class; otherwise the proposal will be considered out-of-scope.

OGC API - Coverages is envisioned to be a modular, multi-part standard. Extensions and profiles not identified as in scope in the previous section will require a revision to the SWG charter prior to commencement of work. If a community has a need to develop a profile, the profile should be specified and governed by that community.

The basic resource described in {swgname} are {resources}. The {shortname} describes the interface and exchange of {resources}. The definition of {resources} is given by the {information_model_base} standard and its encoding standards.

==== Specific Contribution of Existing Work as a Starting Point

The starting point for the work will be the draft document that is currently on the proposed SWG's repository ({githubrepo}). This charter recognizes the prior work done by the {base_swg}. Upon approval of this Charter, responsibilities for OGC API - Coverages will be continued by the proposed renamed {swgname} SWG.

The work will also be informed by the following specifications and by recommendations found in:

* OGC/W3C Spatial Data Working Group on the Web Best Practices (https://www.w3.org/TR/sdw-bp/);
* OGC Geospatial API White Paper [OGC 16-019r4];
* OGC API - Features - Part 1: Core standard, [OGC 17-069r3]; and
* {information_model_base},	[OGC {information_model_base_docnum}].

Each of these documents recommends an emphasis on resource-oriented APIs in future OGC standards development including use of tools such as OpenAPI.

==== Is this a persistent SWG?


* [x] Yes
* [ ] No

==== When can SWG be inactivated?

The {swgname} SWG is a standing one, maintaining the suite through corrigenda, feature extensions, new features, etc. as requested by the membership. Any newly adopted coverage standard will be added to the portfolio of standards maintained.

=== Description of Deliverables

==== Initial Deliverables

The following set of deliverables will be provided by this SWG:

* A final version of the "OGC API - Coverages - Part 1: Core" document for submission to the TC.
* Identification of at least three prototype implementations of the core based on the standard — although more would be preferred.
* Zero or more additional parts as time and community interest permits.

Part 1 will cover basic capabilities to GET, PUT, PATCH, POST, and DELETE {resources} and define {resource} metadata. Capabilities for richer {resource} interfaces or extension for unique geospatial resource considerations will be specified in additional parts.

Work on this deliverable has been proceeding under the WCS SWG. This work will transition to the {swgname} once the charter is approved. Formal approval of the core {shortname} is envisaged to take place nearer {target_end_date}.

==== Additional SWG Tasks

The {swgname} work program will also include development of extensions to the OGC API - Coverages Core Standards including:

NOTE: populate this list of extensions

* OGC API - Coverages - Part n: Subsetting
* OGC API - Coverages - Part n: Processing
* OGC API - Coverages - Part n: CRS

The part numbers will be determined later in 2020.

The {swgname} SWG will develop Coverage encodings for:

* CoverageJSON

The {swgname} will explore and specify how the OGC API - Coverages shall support the following coverage format standards:

* GeoTIFF
* JPEG 2000
* JPEG
* HDF5

=== IPR Policy for this SWG

* [x] RAND-Royalty Free
* [ ] RAND for fee

=== Anticipated Participants

* {resource} resource providers.
* Developers implementing services.
* Producers of {resource} data.
* Users of {resource} resources.

=== Domain Working Group Endorsement

The {dwg_review} will review the proof-of-concept at {githubrepo} and this SWG charter. A statement of endorsement will be requested at the  {dwg_review_meeting}.

=== Other Informative Remarks about this SWG

[loweralpha, start=1]
. Similar or Applicable Standards Work (OGC and Elsewhere).

The following standards work may be applicable to the work of the proposed SWG:

* 19-072 OGC API - Common - Part 1: Core
* ISO 19123-1:(working draft) Coverage Fundamentals
* ISO 19123-2:2018 Coverage implementation schema
* OGC Web Coverage Service
* OGC Web Coverage Processing Service
* EO-GeoJSON
* GML in JPEG2000
* GeoTIFF
* HDF5
* LAS
* NetCDF

Additionally, the proposed SWG will monitor other related work ongoing in various Standards and Innovation Program activities.

[loweralpha, start=2]
. Projected On-going Meeting Schedule

The work of this SWG will be carried out primarily on GitHub and via email, conference calls, with potential face-to-face meetings at OGC TC meetings as agreed to by the SWG members. The teleconference calls will be scheduled as needed and posted to the OGC portal. Voting on {shortname} content will be limited to SWG members only.

[loweralpha, start=3]
. Supporters of the Proposal (Charter Members)

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially renamed. Charter Members are shown on the public SWG page.

[cols=",",width="75%",options="header",align="center"]
|===
|Name| Organization
|Stephan Meissl | EOX IT Services GmbH
|Jerome Jacovella St Louis | Ecere
|Tom Kralidis | Meteorological Service of Canada
|Chuck Heazel | Heazel Tech
|Chris Little | UK Met Office
|Peter Baumann | Jacobs University, rasdaman GmbH
|James Passmore | United Kingdom Research Institute (UKRI)
|===

[loweralpha, start=4]
. Convener(s)

{conveners}
