== Clause containing normative material
Paragraph

=== Requirement Class Common
Paragraph – intro text for the requirement class.

Use the following table for Requirements Classes.

include::requirements/requirements_class_common.adoc[]

==== Examples of Common applied to Coverages 

include::examples/examples_boundingbox.adoc[]

=== Requirement Class Path
An API exposes resources though a resource path. 

General Template: 

    {root}/collections/{collectionid}/coverages/{coverageid/{a}
    
    protocol := "http" | "https"
    server   := server DNS name
    root     := {protocol}:{server}
    a := {b} | "rangetype" | "metadata" | "rangeset"
    b := /domainset | /domainset/{c}
    c := generalgrid/{d}
    d := "srsname" | "axislabels"

Use the following table for Requirements Classes.

include::requirements/requirements_class_path.adoc[]

=== Requirement Class Subset
Without any subsetting parameter the whole coverage extent is the target resource addressed. If a subsetting operation is provided then the coverage subset indicated is the target resource addressed.

Coverage subsetting is indicated through the SUBSET parameter name. The value following the "=" symbol is built as follows:

    SubsetSpec:            SUBSET = axisName (intervalOrPoint)
    axisName:              {NCName}
    intervalOrPoint:       interval | point
    interval:              low : high
    low:                   point | *
    high:                  point | *
    point:                 {number} | "{text}"
    
    Where:
    " = double quote = ASCII code 0x42,
    {NCName} is an XML-style identifier not containing ":" (colon) characters, 
    {number} is an integer or floating-point number, and
    {text} is some general ASCII text (such as a time and date notation in ISO 8601). 
    
include::requirements/requirements_class_subset.adoc[]

==== Subsetting Examples

include::examples/examples_subsetting.adoc[]

=== Requirements Class Encodings

include::requirements/requirements_class_encoding.adoc[]




