== OAPI - Coverages Processing Extension

This extension allows sending a WCPS request to a server for server-side filtering, processing, and fusion, generally: analytics on a coverage server.

To this end, the Processing Extension adds `/wcps` as a query branch to the paths available:
    {api-endpoint}/wcps

This path expects a query parameter of the shape

    q={wcps-query}

where {wcps-query} is a syntactically and semantically correct WCPS query.

The response is a (possibly empty) list of coverages or scalars, depending on the query result type.

Example:

    {api-endpoint}/wcps?q=for $c in (ERA5-cube) return max( $c.temperature )

Note that the query parameter is operating on collection level as any number of server coverages can be combined.

Example:

    http://acme.com/oapi/wcps?q=for $c in (ERA5-cube), $d in (DEM) return encode( $c.temperature > 20 and $d > 100, "image/png" )

Error conditions:

*    The query must be syntactically and semantically correct wrt. the service addressed (cf. WCPS specification).

A WCPS query can have an arbitrary number of parameters passed as part of the request, but outside the query. Such parameters are numbered starting from 1. Inside the query parameters are embedded by referencing them through their resp. number together with a "$" prefix. Before evaluation of the WCPS query in the server all parameters are expanded textually in the query, substituting the "$i" variables with the value provided in the request.

Examples:

    {api-endpoint}/wcps?q=for $c in (ERA5-cube) return max( $c.$1 ) & 1=temperature
    {api-endpoint}/wcps?q=for $c in (Sentinel-2) return ($c.red-$c.nir)/($c.red+$c.nir) > $1 ) & 1=0.6

WCPS requests may use GET as well as POST requests. 

Note:

    In practice, POST requests are preferred when such a parameter is a large string, such as the encoding of a complete coverage provided as input parameter. 
    
== OAPI Definition (draft)

NOTE: this section is not up to date, it needs to be adjusted to the above specification.

The following is a working OAPI definition file for the demonstration service available at http://54.93.148.198:8080/rasdaman. It executes the WCPS query `for $c in (S2_NDVI_84) return encode($c[Lat(51.9:52.1), Long(-4.1:-3.9), ansi("2018-11-14")], "jpeg" )` on the server and returns an image result. This can be tested by pasting the contents of the text box below into the link:http://editor.swagger.io/[swagger editor].
....
{ 
  "openapi": "3.0.1",
  "info": {
    "title": "WCPS",
    "description": "This is a sample WCPS server.",
    "contact": {
      "email": "baumann@rasdaman.com"
    },
    "version": "1.0.0"
  },
  "externalDocs": {
    "description": "Find out more about WCPS",
    "url": "http://doc.rasdaman.org/05_geo-services-guide.html#wcps"
  },
  "servers": [
    {
      "url": "http://54.93.148.198:8080/rasdaman/"
    }
  ],
  "paths": {
    "/collections": {
      "get": {
        "parameters": [
          {
            "name": "q",
            "in": "query",
            "description": "WCPS query to be executed by the server",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "for $c in (S2_NDVI_84) return encode($c[Lat(51.9:52.1), Long(-4.1:-3.9), ansi(\"2018-11-14\")], \"jpeg\")"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "image/jpeg": {
                "example": null
              },
              "application/json": {
                "example": null
              },
              "text/plain": {
                "schema": {
                  "type": "string",
                  "example": 42
                }
              },
              "application/xml": {
                "example": null
              },
              "application/netcdf": {
                "example": null
              },
              "image/tiff": {
                "example": null
              },
              "image/png": {
                "example": null
              },
              "image/jpeg2000": {
                "example": null
              } 
            } 
          },  
          "400": {
            "description": "Invalid query",
            "content": {}
          }     
        }     
      }
    }
  }
}
....
