[[overview]]
== Overview

=== Evolution from OGC Web Services

OGC Web Service (OWS) standards implemented a Remote-Procedure-Call-over-HTTP architectural style using XML for payloads. This was the state-of-the-art when OGC Web Services were originally designed in the late 1990s and early 2000s. The OGC API (OAPI) Common specifies the common kernel of an API approach to services that follows the current Web architecture. In particular, the <<SDWBP,W3C/OGC best practices for sharing Spatial Data on the Web>> as well as the <<DWBP,W3C best practices for sharing Data on the Web>>.

Beside the general alignment with the architecture of the Web (e.g., consistency with HTTP/HTTPS, hypermedia controls), another goal for OGC API standards is modularization. This goal has several facets:

* Clear separation between core requirements and more advanced capabilities. This document specifies the requirements that are relevant for almost everyone who wants to share or use coverage data on a fine-grained level. Additional capabilities that several communities are using today will be specified as extensions to the Core API.
* Technologies that change more frequently are decoupled and specified in separate modules ("requirements classes" in OGC terminology). This enables, for example, the use/re-use of new encodings for spatial data or API descriptions.
* Modularization is not just about a single "service". OGC APIs will provide building blocks that can be reused in APIs in general. In other words, a server supporting the OAPI - Coverages should not be seen as a standalone WCS service.  Rather it should be viewed as a collection of API building blocks which together implement OAPI - Coverages capabilities. A corollary of this is that it should be possible to implement an API that simultaneously conforms to conformance classes from OAPI - Features, OAPI - Coverages and other OGC Web API standards.

This approach intends to support two types of client developers:

* Those that have never heard about OGC. Developers should be able to create a client using the API definition without the need to read an OGC standard (they may need to learn a little bit about geometry, etc.);
* Those that want to write a "generic" client that can access OGC APIs, i.e. are not specific for a particular API.

As a result of this modernization, OGC API implementations are not necessarily always backwards compatible with OWS implementations per se, although - for the protection of implementation and service assets - compatibility will be considered as much as possible. However, a design goal is to define OGC APIs in a way so that an OAPI interface can be mapped to an OWS implementation. OGC APIs are intended to be simpler and more modern, but still an evolution from the previous versions and their implementations.

The OGC coverage data and service model is well prepared for such a step:
* The modular, simple architecture of CIS and WCS has been embraced by developers (link:http://external.opengeospatial.org/twiki_public/CoveragesDWG/WebHome[source]):
 * "Web developers who have not heard of OGC standards before immediately feel at home with these coverage standards" -- Stephan Siemen, ECMWF
 * "WCS is the natural way to deliver and exploit coverage data." -- Jordi Escriu, Facilitator INSPIRE Thematic Cluster #3: Elevation, Orthoimagery, Reference systems and Geographical grids
 * "As a WCS the data is of most value" -- Perry Peterson, Pyxis Innovation
 * "CIS 1.1 is what I've been waiting for." -- Kathi Schleidt, INSPIRE expert 
* Both the coverage data model (CIS) and the service model (WCS) are modular suites of standards, with a focus on simplicity and ease of use in the CIS and WCS Core and a rich ecosystem of coverage-specific structuring and functionality in the extensions. Application Profiles provide specialized services, e.g., for remote sensing imagery.
* The WCS Core provides the very basic functionality, coverage access, subsetting, and format encoding. Hence, WCS Core is an ideal starting point for an OAPI Coverages service.
* The WCS suite has a clear separation in functionality and protocol binding (i.e., request language). For example, all WCS Core and Extension functionality can be expressed equivalently in GET/KVP, POST/XML, and SOAP. Adding an OpenAPI protocol binding, therefore, can easily fit into this ecosystem, thereby avoiding a backwards incompatible change (like "WCS 3.0") and rather establishing incrementally a WCS 2.2.

The modernization is discussed in more detail and from a coverage independent view link:https://github.com/opengeospatial/OAPI_Common/blob/master/overview.md[here].

=== Encodings

[NOTE]
========
Metadata will be returned as well as complete coverages.  For the former, HTML should be included for this purpose, for the latter some format like should be included.  Additional encodings will be needed to support coverage responses, such as GML and RDF already supported by CIS in addition to JSON.
========

This standard does not mandate any particular encoding or format. However, it does provide extensions for encodings which are commonly used in OGC APIs.  In addition to HTML as the standard encoding for human-centric Web content, rules for commonly used encodings for spatial data on the web are provided (GeoJSON, GML).

None of these encodings is mandatory and an implementation of the _Core_ requirements class may implement none of them. Alternatively, an implementation of the _Core_ requirements class may choose to implement completely different encodings instead.

<<rec_html,Support for HTML is recommended>>. HTML is the core language of the World Wide Web. An API that supports HTML will support browsing the spatial resources with a web browser and will also enable search engines to crawl and index those resources.

CAUTION: The search engine point is not valid. HTML describes syntax, not semantics (remember why we introduced XML and RDF?). See link:https://github.com/opengeospatial/ogc_api_coverages/issues/13[Issue 13].

GeoJSON is a commonly used format that is simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using a JSON-based format, it is <<rec_geojson,recommended for APIs which expose feature data>> as long as the data can be represented in GeoJSON for the intended use.

Some examples of cases that are out-of-scope for GeoJSON are:

* When solids are used for geometries (e.g. in a 3D city model),
* Geometries that include non-linear curve interpolations
that cannot be simplified (e.g., use of arcs in authoritative geometries),
* Geometries that have to be represented in a coordinate reference system that is not based on WGS 84 longitude/latitude (e.g. an authoritative national reference system),
* Features that have more than one geometric property.

Among the shortcomings of GeoJSON, which have been debated widely, is the substantially restricted support for multi-dimensional coordinates and coordinate reference systems. For exampele, European ETRS89 is not supported.

The recommendations for using HTML and GeoJSON reflect the importance of HTML and the current popularity of JSON-based data formats. As the practices in the Web community evolve, the recommendations will likely be updated in future versions of this standard to provide guidance on using other encodings.

This part of the OAPI standard does not provide any guidance on other encodings. The supported encodings, or more precisely the media types of the supported encodings, can be determined from the API definition. The desired encoding is selected using HTTP content negotiation.

For example, if the server supports link:https://tools.ietf.org/html/rfc8142[GeoJSON Text Sequences] an encoding that is based on JSON text sequences, and GeoJSON, and supports streaming by making the data incrementally parseable, could use the media type `application/geo+json-seq` in the header of a corresponding request to the server.

In addition, HTTP supports compression. Therefore the standard HTTP compression mechanisms can be used to reduce the size of messages between the server and the client.

=== Examples

[NOTE]
========
Update the following content once a coverage example has been agreed on.
========

This document uses a simple example throughout the document: The dataset contains buildings and the API provides access to them through a single feature collection ("buildings") and two encodings, GeoJSON and HTML.

The buildings have a few (optional) properties: the polygon geometry of the building footprint, a name, the function of the building (residential, commercial or public use), the floor count and the timestamp of the last update of the building feature in the dataset.

This example serves to illustrate the concepts underlying OGC APIs. It does not indicate that OGC APIs are always feature based. Other resource types can and will be implemented as well. But the basic capapablities described in this specification will apply to all.
