== Requirements classes for encodings

[NOTE]
========
The following content is from the OAPI Common specification and should be modified for Coverage APIs. Keep in mind that both coverages and metadata are supplied by the API. link:https://github.com/opengeospatial/ogc_api_coverages/blob/master/CIS%2BWCS-standards/09-146r6_Coverage_Implementation_Schema_CIS_1.1.pdf[OGC CIS] defines how to encode coverages with their data and metadata; for pure metadata responses HTML and GeoJSON encoding may be retained.
========

=== Overview

This clause specifies four pre-defined requirements classes for encodings available for use by an OGC API implementation. These encodings are commonly used encodings for spatial data on the web:

* <<rc_cisjson,OGC CIS JSON>> (OGC CIS 1.1 standard, includes binary encodings)
* <<rc_html,HTML>> (currently undefined)
* <<rc_geojson,GeoJSON>> (GeoJSON currently does not support coverages, and "The GeoJSON format differs from other GIS standards in that it was written and is maintained not by a formal standards organization, but by an Internet working group of developers." link:https://everything.explained.today/GeoJSON/[source])

None of these encodings are mandatory and an implementation of the <<rc_core,Core>> requirements class may also implement none of them but implement another encoding instead, such as GeoTIFF or NetCDF.

<<overview,Clause 6 (Overview)>> includes a discussion about recommended encodings.

=== Requirements class "CIS JSON"
This requirements class relies on the OGC Coverage Implementation Schema and its JSON encoding as defind in the link:http://schemas.opengis.net/cis/1.1/json/coverage-schema.json[JSON schema]. It is "informationally complete": all coverage constituents defined in the standard can be represented, there is no loss of information in this encoding (as opposed to, e.g., image formats which typically cannot carry all coverage metadata). Below examples are given, all from the link:http://schemas.opengis.net/cis/1.1/json/examples/[official OGC schema repository]. Note, however, that a coverage does not need to be delivered in JSON in its entirety; rather, multipart encoding, also defined in OGC CIS, allows having a "canonical" header in XML, JSON, RDF, or similar while components can be factored out and represented in some (more efficient) binary format, such ss TIFF and NetCDF. Any suitable container format (such as zip, miltipart/mime, SAFE, etc.) can "bundle" these components into one coverage file ready for shipping.

.A CIS JSON Coverage Object response (link:http://schemas.opengis.net/cis/1.1/json/examples/10_2D_regular.json[source])
=================

[source,JSON]
----
{
        "@context": ["http://localhost/json-ld/coverage-context.json", {"examples": "http://www.opengis.net/cis/1.1/examples/"}],
        "type": "CoverageByDomainAndRangeType",
        "id": "examples:CIS_10_2D",
        "domainSet":{
                "@context": "http://localhost/json-ld/domainset-context.json",
                "type": "DomainSetType",
                "id": "examples:CIS_DS_10_2D",
                "generalGrid":{
                        "type": "GeneralGridCoverageType",
                        "id": "examples:CIS_DS_GG_10_2D",
                        "srsName": "http://www.opengis.net/def/crs/EPSG/0/4326",
                        "axisLabels": ["Lat", "Long"],
                        "axis": [{
                                "type": "RegularAxisType",
                                "id": "examples:CIS_DS_GG_LAT_10_2D",
                                "axisLabel": "Lat",
                                "lowerBound": -80,
                                "upperBound": -70,
                                "uomLabel": "deg",
                                "resolution": 5
                        },{
                                "type": "RegularAxisType",
                                "id": "examples:CIS_DS_GG_LONG_10_2D",
                                "axisLabel": "Long",
                                "lowerBound": 0,
                                "upperBound": 10,
                                "uomLabel": "deg",
                                "resolution": 5
                        }],
                        "gridLimits": {
                                "type": "GridLimitsType",
                                "id": "examples:CIS_DS_GG_GL_10_2D",
                                "srsName": "http://www.opengis.net/def/crs/OGC/0/Index2D",
                                "axisLabels": ["i", "j"],
                                "axis": [{
                                        "type": "IndexAxisType",
                                        "id": "examples:CIS_DS_GG_GL_I_10_2D",
                                        "axisLabel": "i",
                                        "lowerBound": 0,
                                        "upperBound": 2
                                },{
                                        "type": "IndexAxisType",
                                        "id": "examples:CIS_DS_GG_GL_J_10_2D",
                                        "axisLabel": "j",
                                        "lowerBound": 0,
                                        "upperBound": 2
                                }]
                        }
                }
        },
        "rangeSet": {
                "@context": "http://localhost/json-ld/rangeset-context.json",
                "type": "RangeSetType",
                "id": "examples:CIS_RS_10_2D",
                "dataBlock": {
                        "id": "examples:CIS_RS_DB_10_2D",
                        "type": "VDataBlockType",
                        "values": [1,2,3,4,5,6,7,8,9]
                }
        },
        "rangeType": {
                "@context": "http://localhost/json-ld/rangetype-context.json",
                "type": "DataRecordType",
                "id": "examples:CIS_RT_10_2D",
                "field":[{
                        "type": "QuantityType",
                        "id": "examples:CIS_RT_F_10_2D",
                        "definition": "ogcType:unsignedInt",
                        "uom": {
                                "type": "UnitReference",
                                "id": "examples:CIS_RT_F_UOM_10_2D",
                                "code": "10^0"
                        }
                }]
        }
}
----
=================

.A CIS JSON Coverage Object response with file reference (link:http://schemas.opengis.net/cis/1.1/json/examples/10_2D_regular.json[source])
=================
In the example below, the range set part of the coverage above has been replaced by a file reference (which should be accessible by the coverage recipient, so likely a URL in practice). All other parts (denoted by "...") remain as above.

[source,JSON]
----
...
        "rangeSet": {
                "@context": "http://localhost/json-ld/rangeset-context.json",
                "type": "RangeSetRefType",
                "id": "examples:CIS_RS_11_2D",
                "fileReference": ["regular_fileref.tiff"]
        },
...
----
=================

=== Requirement Class "HTML"

Geographic information that is only accessible in formats like GeoJSON or GML has two issues:

* The data is not discoverable using the most common mechanism for discovering information, that is the search engines of the Web;
* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, it should be done in a way that enables users and search engines to access all data.

This is discussed in detail in
link:https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines[Best Practice 2: Make your spatial data indexable by search engines]
<<SDWBP>>. This standard therefore <<rec_html,recommends supporting HTML as an encoding>>.

include::requirements/requirements_class_html.adoc[]

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::requirements/html/REC_schema-org.adoc[]

=== Requirement Class "GeoJSON"

GeoJSON is a commonly used format for geographic features that is simple to understand and well supported by tools and software libraries; for coverages no support is currently available. 

Instead, JSON coverages can be encoded as defined in the link:https://github.com/opengeospatial/ogc_api_coverages/blob/master/CIS%2BWCS-standards/09-146r6_Coverage_Implementation_Schema_CIS_1.1.pdf[OGC Coverage Implementation Schema] standard which defines a JSON encoding that retains all coverage information; see the previous section for details.

include::requirements/requirements_class_geojson.adoc[]

include::requirements/geojson/REQ_definition.adoc[]

include::requirements/geojson/REQ_content.adoc[]

=== Requirement Class "Geography Markup Language (GML), Simple Features Profile"

[NOTE]
========
The XML encoding of coverages is not defined in GML Simple Features; rather, a GML-oriented coverage representation is defined in OGC CIS, see the link:http://schemas.opengis.net/cis/1.1/gml/[official OGC schema] containing link:http://schemas.opengis.net/cis/1.1/gml/examples-1.1/[many examples].
========
