== Requirements classes for encodings

[NOTE]
========
The following content is from the OAPI Common specification and should be modified for Coverage APIs. Keep in mind that both coverages and metadata are supplied by the API. link:https://github.com/opengeospatial/ogc_api_coverages/blob/master/CIS%2BWCS-standards/09-146r6_Coverage_Implementation_Schema_CIS_1.1.pdf[OGC CIS] defines how to encode coverages with their data and metadata; for pure metadata responses HTML and GeoJSON encoding may be retained.
========

=== Overview

This clause specifies four pre-defined requirements classes for encodings available for use by an OGC API implementation. These encodings are commonly used encodings for spatial data on the web:

* <<rc_html,HTML>>
* <<rc_geojson,GeoJSON>>
* <<rc_gmlsf0,Geography Markup Language (GML), Simple Features Profile, Level 0>> (this is copied from features, does not apply directly)
* <<rc_gmlsf2,Geography Markup Language (GML), Simple Features Profile, Level 2>> (this is copied from features, does not apply directly)
* <<rc_cisjson,CIS JSON>>

None of these encodings are mandatory and an implementation of the <<rc_core,Core>> requirements class may also implement none of them but implement another encoding instead, such as GeoTIFF or NetCDF.

The <<rc_core,Core>> requirements class includes recommendations to support <<rec_html,HTML>> and <<rec_geojson,GeoJSON>> as encodings, where practical. <<overview,Clause 6 (Overview)>> includes a discussion about recommended encodings.

=== Requirement Class "HTML"

Geographic information that is only accessible in formats like GeoJSON or GML has two issues:

* The data is not discoverable using the most common mechanism for discovering information, that is the search engines of the Web;
* The data can not be viewed directly in a browser - additional tools are required to view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent with the Web, it should be done in a way that enables users and search engines to access all data.

This is discussed in detail in
link:https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines[Best Practice 2: Make your spatial data indexable by search engines]
<<SDWBP>>. This standard therefore <<rec_html,recommends supporting HTML as an encoding>>.

include::requirements/requirements_class_html.adoc[]

include::requirements/html/REQ_definition.adoc[]

include::requirements/html/REQ_content.adoc[]

include::requirements/html/REC_schema-org.adoc[]

=== Requirement Class "GeoJSON"

GeoJSON is a commonly used format that is simple to understand and well supported by tools and software libraries. Since most Web developers are comfortable with using a JSON-based format supporting GeoJSON is recommended, if the feature data can be represented in GeoJSON for the intended use; for coverages a corresponding leve of detail is currently not available. Note, though, that the link:https://github.com/opengeospatial/ogc_api_coverages/blob/master/CIS%2BWCS-standards/09-146r6_Coverage_Implementation_Schema_CIS_1.1.pdf[OGC Coverage Implementation Schema] defines a JSON encoding that retains all coverage information, see the examples provided in the link:http://schemas.opengis.net/cis/1.1/json/examples/[official standard repository].

include::requirements/requirements_class_geojson.adoc[]

include::requirements/geojson/REQ_definition.adoc[]

include::requirements/geojson/REQ_content.adoc[]

Templates for the definition of the schemas for the GeoJSON responses in OpenAPI definitions are available at link:https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/featureCollectionGeoJSON.yaml[featureCollectionGeoJSON.yaml] and  link:https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/featureGeoJSON.yaml[featureGeoJSON.yaml].
These are generic schemas that do not include any application schema information about specific feature types or their properties.

.A GeoJSON FeatureCollection Object response
=================
In the example below, only the first and tenth feature is shown. Coordinates are not shown.

[source,JSON]
----
{
  "type" : "FeatureCollection",
  "links" : [ {
    "href" : "http://data.example.com/collections/buildings/items/?f=json",
    "rel" : "self",
    "type" : "application/geo+json",
    "title" : "this document"
  }, {
    "href" : "http://data.example.com/collections/buildings/items/?f=html",
    "rel" : "alternate",
    "type" : "text/html",
    "title" : "this document as HTML"
  }, {
    "href" : "http://data.example.com/collections/buildings/items/?f=json&startIndex=10&limit=10",
    "rel" : "next",
    "type" : "application/geo+json",
    "title" : "next page"
  } ],
  "timeStamp" : "2018-04-03T14:52:23Z",
  "numberMatched" : 123,
  "numberReturned" : 10,
  "features" : [ {
    "type" : "Feature",
    "id" : "123",
    "geometry" : {
      "type" : "Polygon",
      "coordinates" : [ ... ]
    },
    "properties" : {
      "function" : "residential",
      "floors" : "2",
      "lastUpdate" : "2015-08-01T12:34:56Z"
    }
  }, { ...
  }, {
    "type" : "Feature",
    "id" : "132",
    "geometry" : {
      "type" : "Polygon",
      "coordinates" : [ ... ]
    },
    "properties" : {
      "function" : "public use",
      "floors" : "10",
      "lastUpdate" : "2013-12-03T10:15:37Z"
    }
  } ]
}
----
=================

.A GeoJSON Feature Object response
=================
In the example below, coordinates are not shown.

[source,JSON]
----
{
  "type" : "Feature",
  "links" : [ {
    "href" : "http://data.example.com/collections/buildings/items/123/?f=json",
    "rel" : "self",
    "type" : "application/geo+json",
    "title" : "this document"
  }, {
    "href" : "http://data.example.com/collections/buildings/items/123/?f=html",
    "rel" : "alternate",
    "type" : "text/html",
    "title" : "this document as HTML"
  }, {
    "href" : "http://data.example.com/collections/buildings/items",
    "rel" : "collection",
    "type" : "application/geo+json",
    "title" : "the collection document"
  } ],
  "id" : "123",
  "geometry" : {
    "type" : "Polygon",
    "coordinates" : [ ... ]
  },
  "properties" : {
    "function" : "residential",
    "floors" : "2",
    "lastUpdate" : "2015-08-01T12:34:56Z"
  }
}
----
=================

=== Requirement Class "Geography Markup Language (GML), Simple Features Profile, Level 0"

In addition to HTML and GeoJSON, a significant volume of feature data is available XML-based formats, notably  GML. Therefore, this standard specifies requirement classes for GML. The Simple Features Profile, Level 0, is the simplest profile of GML and is typically supported by tools. The GML Simple Features Profile is restricted to data with 2D geometries supported by most tools. In addition, the Level 0 profile is limited to features that can be stored in a tabular data structure.

include::requirements/requirements_class_gmlsf0.adoc[]

include::requirements/gmlsf0/REQ_definition.adoc[]

include::requirements/gmlsf0/REQ_content.adoc[]

[#gml_content,reftext='{table-caption} {counter:table-num}']
.Media types and XML elements for each resource
[cols="30,35,35",options="header"]
!===
|Resource |Path |XML root element
|Landing page |`/` |`wfs:LandingPage`
|Conformance classes |`/conformance` |`wfs:ConformsTo`
|Feature collections metadata |`/collections` |`wfs:Collections`
|Feature collection metadata |`/collections/{collectionId}` |`wfs:Collections`, with just one entry for the collection `collectionId`
|Feature collection |`/collections/{collectionId}/items` |`wfs:FeatureCollection`
|Feature |`/collections/{collectionId}/items/{featureId}` |substitutable for `gml:AbstractFeature`
!===

The namespace prefixes used above are:

* `wfs`: `http://www.opengis.net/wfs/3.0`
* `gml`: `http://www.opengis.net/gml/3.2`
* `atom`: `http://www.w3.org/2005/Atom`
* `xlink`: `http://www.w3.org/1999/xlink`

[NOTE]
========
The above examples should be adapted to coverages, ie: referencing WCS and CIS instead of WSF and GML 3.2.
========

The API definition resource at path `/api` is not included in <<gml_content>>. This requirements class does not prescribe any API definition approach.

The mapping of the content from the responses specified in the <<rc_core,Core requirements class>> to the XML is straightforward. All links are encoded using `atom:link` elements except in GML features where simple Xlinks are used.

<<xml_examples,Annex C>> has example responses in XML.

NOTE: The `wfs:FeatureCollection` element deliberately goes beyond the permitted content specified in the <<GMLSF,GML Simple Features Profile>>, section 8.4.2. This is necessary to support the hypermedia controls and other relevant content for a Web Feature Service API.

=== Requirement Class "Geography Markup Language (GML), Simple Features Profile, Level 2"

The difference between this requirement class and the <<rc_gmlsf0,Level 0>> requirements class is that non-spatial feature properties are not restricted to atomic values (strings, numbers, etc.).

include::requirements/requirements_class_gmlsf2.adoc[]

include::requirements/gmlsf2/REQ_definition.adoc[]

include::requirements/gmlsf2/REQ_content.adoc[]

[NOTE]
========
The coverage GML encoding corresponding to GML Simple Features is defined in OGC CIS.
========

=== Requirements class "CIS JSON"
This requirements class relies on the OGC/ISO Coverage Implementation Schema and its JSON encoding as defind in the link:http://schemas.opengis.net/cis/1.1/json/coverage-schema.json[JSON schema]. It is "informationally complete": all coverage constituents defined in the standard can be represented, there is no loss of information in this encoding (as opposed to, e.g., image formats which typically cannot carry all coverage metadata). Below examples are given, all from the link:http://schemas.opengis.net/cis/1.1/json/examples/[official OGC schema repository]. Note, however, that a coverage does not need to be delivered in JSON in its entirety; rather, multipart encoding, also defined in OGC/ISO CIS, allows having a "canonical" header in XML, JSON, RDF, or similar while components can be factored out and represented in some (more efficient) binary format, such ss TIFF and NetCDF. Any suitable container format (such as zip, miltipart/mime, SAFE, etc.) can "bundle" these components into one coverage file ready for shipping.

.A CIS JSON Coverage Object response (link:http://schemas.opengis.net/cis/1.1/json/examples/10_2D_regular.json[source])
=================

[source,JSON]
----
{
        "@context": ["http://localhost/json-ld/coverage-context.json", {"examples": "http://www.opengis.net/cis/1.1/examples/"}],
        "type": "CoverageByDomainAndRangeType",
        "id": "examples:CIS_10_2D",
        "domainSet":{
                "@context": "http://localhost/json-ld/domainset-context.json",
                "type": "DomainSetType",
                "id": "examples:CIS_DS_10_2D",
                "generalGrid":{
                        "type": "GeneralGridCoverageType",
                        "id": "examples:CIS_DS_GG_10_2D",
                        "srsName": "http://www.opengis.net/def/crs/EPSG/0/4326",
                        "axisLabels": ["Lat", "Long"],
                        "axis": [{
                                "type": "RegularAxisType",
                                "id": "examples:CIS_DS_GG_LAT_10_2D",
                                "axisLabel": "Lat",
                                "lowerBound": -80,
                                "upperBound": -70,
                                "uomLabel": "deg",
                                "resolution": 5
                        },{
                                "type": "RegularAxisType",
                                "id": "examples:CIS_DS_GG_LONG_10_2D",
                                "axisLabel": "Long",
                                "lowerBound": 0,
                                "upperBound": 10,
                                "uomLabel": "deg",
                                "resolution": 5
                        }],
                        "gridLimits": {
                                "type": "GridLimitsType",
                                "id": "examples:CIS_DS_GG_GL_10_2D",
                                "srsName": "http://www.opengis.net/def/crs/OGC/0/Index2D",
                                "axisLabels": ["i", "j"],
                                "axis": [{
                                        "type": "IndexAxisType",
                                        "id": "examples:CIS_DS_GG_GL_I_10_2D",
                                        "axisLabel": "i",
                                        "lowerBound": 0,
                                        "upperBound": 2
                                },{
                                        "type": "IndexAxisType",
                                        "id": "examples:CIS_DS_GG_GL_J_10_2D",
                                        "axisLabel": "j",
                                        "lowerBound": 0,
                                        "upperBound": 2
                                }]
                        }
                }
        },
        "rangeSet": {
                "@context": "http://localhost/json-ld/rangeset-context.json",
                "type": "RangeSetType",
                "id": "examples:CIS_RS_10_2D",
                "dataBlock": {
                        "id": "examples:CIS_RS_DB_10_2D",
                        "type": "VDataBlockType",
                        "values": [1,2,3,4,5,6,7,8,9]
                }
        },
        "rangeType": {
                "@context": "http://localhost/json-ld/rangetype-context.json",
                "type": "DataRecordType",
                "id": "examples:CIS_RT_10_2D",
                "field":[{
                        "type": "QuantityType",
                        "id": "examples:CIS_RT_F_10_2D",
                        "definition": "ogcType:unsignedInt",
                        "uom": {
                                "type": "UnitReference",
                                "id": "examples:CIS_RT_F_UOM_10_2D",
                                "code": "10^0"
                        }
                }]
        }
}
----

