openapi: 3.0.3
info:
  title: 'A sample API conforming to the OGC API - Coverages - Part 1: Core standard'
  description: 'This is a sample OpenAPI definition that conforms to the OGC API - Coverages - Part 1: Core Service specification (conformance classes: "GeoData-Coverage", "Coverage Subset", "CIS JSON", "HTML" and "OpenAPI 3.0").'
  contact:
    name: Open Geospatial Consortium
    url: https://ogc.org
    email: info@ogc.org
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  version: 2.0.0
servers:
  - url: https://dev.example.org
    description: Development server
  - url: https://data.example.org
    description: Production server
tags:
  - name: Capabilities
    description: Essential characteristics of this API including information about the data.
  - name: Coverage
    description: Access to data (coverage).
paths:
  # OGC API - Coverages - Part 1: Core
  /:
    $ref: 'paths/common-core/landingPage.yaml'
  /conformance:
    $ref: 'paths/common-core/conformance.yaml'
  /api:
    $ref: 'paths/common-core/api.yaml'
  /collections:
    $ref: 'paths/coverages-core/collections.yaml'
  /collections/{collectionId}:
    $ref: 'paths/coverages-core/collection.yaml'
  /collections/{collectionId}/coverage:
    $ref: 'paths/coverages-core/coverage.yaml'
  /collections/{collectionId}/coverage/domainset:
    $ref: 'paths/coverages-core/domainset.yaml'
  /collections/{collectionId}/coverage/rangetype:
    $ref: 'paths/coverages-core/rangetype.yaml'
  /collections/{collectionId}/coverage/rangeset:
    $ref: 'paths/coverages-core/rangeset.yaml'
  /collections/{collectionId}/coverage/metadata:
    $ref: 'paths/coverages-core/metadata.yaml'
