
////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////

[abstract]
== Abstract

The OGC API - Coverages - Part 1: Core Standard defines a Web API for requesting coverage data over the Web.
A coverage is a function which returns values from its range for any direct position within its domain.
The coverage data response from this Web API consists of a collection of values usually representing observations or measurements for
one or more fields within a multidimensional domain, often including spatiotemporal dimensions.

Implementations of the OGC API - Coverages Standard are designed for a client to easily:

- Request data values from a specific coverage;
- Select a subset of the domain (space, time, or other dimensions) for which to retrieve values;
- Select specific fields for which to retrieve values;
- Select a particular resolution at which to retrieve the data (such as downsampling from the native resolution);
- Select a particular output coordinate reference system.

A server that implements OGC API - Coverages provides information about which coverages are offered.
OGC API - Coverages use cases are similar to those addressed by the
http://docs.opengeospatial.org/is/17-089r1/17-089r1.html[OGC 17-089r1 OGC® Web Coverage Service (WCS) Interface Standard].

== Preface

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

== Security considerations

Implementations of OGC API - Coverages should apply standard web security practices, including the use of Transport Layer Security (TLS/HTTPS), user authentication, and
granular access control mechanisms to protect sensitive data resources.

In addition to baseline web security, the on-demand data transformation capabilities defined in this standard introduce specific resource consumption risks. Because operations
like spatial-temporal subsetting, scaling, and format translations can be processed dynamically in real time, a server can be exposed to intentional or accidental
Denial of Service (DoS) attacks. For example, a single request combining an immense data footprint with fine-grained resampling or massive output dimensions can trigger
resource exhaustion across server memory and CPU channels.

To protect the infrastructure from resource exhaustion, implementations should explicitly advertise and enforce server processing limits, returning appropriate HTTP `4xx` error
codes when client requests violate those configured structural boundaries.

== Submitters

All questions or concerns regarding this OGC Standard should be submitted as issues to the https://github.com/opengeospatial/ogcapi-coverages[OGC API - Coverages repository].

|===
|*Name*                                |*Affiliation*
|Charles Heazel (Editor)               |HeazelTech
|Jérôme Jacovella-St-Louis (Editor)    |https://ecere.ca[Ecere Corporation]
|Joan Masó Pau (Editor)                |https://www.creaf.cat/[Universitat Autònoma de Barcelona (CREAF)]
|Stephan Meissl                        |https://eox.at[EOX IT Services GmbH]
|Tom Kralidis                          |Meteorological Service of Canada
|Francis Charette-Migneault            |https://luqia.ca[Technologies Luqia]
|Keith Pomakis                         |https://www.cubewerx.com[CubeWerx Inc.]
|Graham Wilkes                         |https://natural-resources.canada.ca[Natural Resources Canada]
|Peter Baumann                         |https://constructor.university[Constructor University]
|===

== Contributors

Additional contributors to this Standard include the following:

Francis Charette-Migneault, https://luqia.ca[Technologies Luqia]

Stephan Meissl, https://eox.at[EOX IT Services GmbH]

Peter Baumann, https://constructor.university[Constructor University]

== Acknowledgements

Some of the work leading to the creation of this OGC Standard was undertaken as part of
GeoConnections 2020-2021 and 2025-2027 projects GNS20-21IFP02 (Modular OGC API Workflows) and
GNS25-27IFP2 (Advancing and Implementing OGC Standards for GeoDataCubes, DGGSs, Data Stores for Digital Twins and Cartographic Symbology).

Financial support for the above mentioned activities was provided by GeoConnections, a national collaborative initiative led by Natural Resources Canada.
GeoConnections supports the modernization of the Canadian Geospatial Data Infrastructure (CGDI).
The CGDI is the collection of geospatial data, standards, policies, applications, and governance that facilitate its
access, use, integration, and preservation.

Additional support was provided through OGC Testbed activities related to GeoDataCubes, in particular Testbed 17 (https://docs.ogc.org/per/21-027.html[OGC 21-026]),
Testbed 19 (https://docs.ogc.org/per/23-047.html[OGC 23-047]) and Testbed 20 (https://docs.ogc.org/per/24-035.html[OGC 24-035]).
