name: Test build OpenAPI bundle

on:
  pull_request:
    branches:
      - master
    paths:
      - 'standard/openapi/**.yaml'

jobs:
  test-build-openapi-bundle:
    name: Generate OpenAPI bundle
    runs-on: ubuntu-latest
    steps:
    - name: Setup npm
      uses: actions/setup-node@v2
    - name: Install dependencies
      run: npm install -g @apidevtools/swagger-cli
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
      #with:
      #  fetch-depth: 0
    - name: Generate OpenAPI bundle
      run: |
        cd standard/openapi
        swagger-cli bundle -o ogcapi-coverages-1.bundled.json ogcapi-coverages-1.yaml
